<template>
  <Layout title="资源管理" back>
    <view class="flex flex-col">
      <view class="bg-white mx-4 mt-3 rounded-lg overflow-hidden"><view class="flex items-center gap-2 p-2"><u-search v-model="keyword" placeholder="搜索资源名称/编码" :show-action="false" @search="onSearch" class="flex-1" /><u-button text="新增" type="primary" icon="plus" @click="openCreate" /></view></view>
      <view v-for="item in records" :key="item.id" class="mx-4 mt-3 bg-white rounded-lg overflow-hidden">
        <view class="flex items-center justify-between px-4 py-3 border-b"><view class="flex flex-col"><text class="text-base font-bold text-gray-900">{{ item.name }}</text><text class="text-xs text-gray-500">{{ item.code || '-' }} · {{ item.resource_type || '-' }}</text></view><view class="flex gap-1"><u-button text="详情" size="mini" plain @click="openDetail(item)" /><u-button text="编辑" size="mini" plain @click="openEdit(item)" /><u-button text="删除" size="mini" plain type="error" @click="confirmDelete(item)" /></view></view>
        <view class="px-4 py-2 flex flex-wrap gap-x-4 gap-y-1 text-xs text-gray-500"><text>路径: {{ item.path || '-' }}</text><text>模块: {{ item.module_id_name || '-' }}</text><text>排序: {{ item.sort ?? '-' }}</text><text>{{ formatDateTime(item.updated_at) }}</text></view>
      </view>
      <u-loadmore :status="loadStatus" />
    </view>
    <u-popup :show="formVisible" mode="bottom" :safe-area-inset-bottom="true" @close="formVisible = false"><view class="bg-white rounded-t-lg p-4" style="max-height: 70vh; overflow-y: auto;"><text class="block text-lg font-bold mb-4">{{ editingId ? '编辑资源' : '新增资源' }}</text><u-form :model="form"><u-form-item label="名称" required><u-input v-model="form.name" placeholder="请输入名称" border="none" /></u-form-item><u-form-item label="编码" required><u-input v-model="form.code" placeholder="请输入编码" border="none" /></u-form-item><u-form-item label="资源类型" required><view class="w-full" @click="openPicker('resource_type', dictOptions('RESOURCE_TYPE'))"><u-input :value="dictLabel('RESOURCE_TYPE', form.resource_type)" placeholder="请选择" disabled border="none" /></view></u-form-item><u-form-item label="父资源ID"><u-input v-model="form.parent_id" placeholder="请输入" border="none" /></u-form-item><u-form-item label="模块ID"><u-input v-model="form.module_id" placeholder="请输入" border="none" /></u-form-item><u-form-item label="路径"><u-input v-model="form.path" placeholder="请输入" border="none" /></u-form-item><u-form-item label="组件"><u-input v-model="form.component" placeholder="请输入" border="none" /></u-form-item><u-form-item label="图标"><u-input v-model="form.icon" placeholder="请输入" border="none" /></u-form-item><u-form-item label="排序"><u-number-box v-model="form.sort" :min="0" /></u-form-item><u-form-item label="显示菜单"><u-switch v-model="form.is_visible" /></u-form-item><u-form-item label="缓存"><u-switch v-model="form.is_cache" /></u-form-item><u-form-item label="固定"><u-switch v-model="form.is_affix" /></u-form-item><u-form-item label="状态"><view class="w-full" @click="openPicker('status', dictOptions('COMMON_STATUS'))"><u-input :value="dictLabel('COMMON_STATUS', form.status)" placeholder="请选择" disabled border="none" /></view></u-form-item><u-form-item label="描述"><u-textarea v-model="form.description" placeholder="请输入描述" border="none" /></u-form-item></u-form><u-button text="保存" type="primary" :loading="saving" @click="doSave" class="mt-4" /></view></u-popup>
    <u-popup :show="detailVisible" mode="bottom" :safe-area-inset-bottom="true" @close="detailVisible = false"><view class="bg-white rounded-t-lg p-4" style="max-height: 70vh; overflow-y: auto;"><text class="block text-lg font-bold mb-4">资源详情</text><u-cell-group :border="false"><u-cell-item v-for="f in detailFields" :key="f" :title="detailLabel(f)" :value="displayVal(detail[f])" :arrow="false" /></u-cell-group></view></u-popup>
    <u-picker :show="pickerShow" :columns="pickerColumns" key-name="label" @confirm="onPickerConfirm" @close="pickerShow = false" />
  </Layout>
</template>
<script setup lang="ts">
import { computed, ref } from 'vue'; import { onLoad, onPullDownRefresh } from '@dcloudio/uni-app'; import Layout from '@/layouts/index.vue'; import { resourceApi } from '@/api'; import { dictList } from '@/utils/dict'; import { displayValue, formatDateTime } from '@/utils/format'; import { fallbackDicts } from '@/config/resource'
const records = ref<any[]>([]); const keyword = ref(''); const current = ref(1); const total = ref(0); const loading = ref(false); const formVisible = ref(false); const detailVisible = ref(false); const saving = ref(false); const editingId = ref(''); const detail = ref<any>({}); const form = ref<Record<string, any>>({}); const pickerShow = ref(false); const pickerField = ref(''); const pickerColumns = ref<any[]>([[]])
const detailFields = ['id', 'module_id_name', 'code', 'name', 'resource_type', 'parent_id', 'path', 'component', 'redirect', 'icon', 'href', 'sort', 'is_visible', 'is_cache', 'is_affix', 'status', 'description', 'created_at', 'updated_at']
const loadStatus = computed(() => loading.value ? 'loading' : records.value.length >= total.value ? 'nomore' : 'loadmore')
onLoad(() => { refresh() }); onPullDownRefresh(async () => { await refresh(); uni.stopPullDownRefresh() })
async function refresh() { current.value = 1; await loadPage(false) }
async function loadPage(a: boolean) { loading.value = true; try { const p: any = { current: current.value, size: 20 }; if (keyword.value) p.code = keyword.value; const pg = await resourceApi.page(p); records.value = a ? [...records.value, ...(pg.records ?? [])] : (pg.records ?? []); total.value = pg.total ?? 0 } finally { loading.value = false } }
function onSearch() { refresh() }; function dictOptions(c: string) { return dictList(c).length ? dictList(c) : fallbackDicts[c] ?? [] }; function dictLabel(c: string, v: any) { return dictOptions(c).find((o: any) => String(o.value) === String(v))?.label ?? v ?? '' }; function displayVal(v: any) { const dt = formatDateTime(v); return displayValue(dt !== v ? dt : v) }; function detailLabel(p: string) { const m: Record<string, string> = { id: 'ID', module_id_name: '模块', code: '编码', name: '名称', resource_type: '资源类型', parent_id: '父资源ID', path: '路径', component: '组件', redirect: '重定向', icon: '图标', href: '外链', sort: '排序', is_visible: '显示菜单', is_cache: '缓存', is_affix: '固定页签', status: '状态', description: '描述', created_at: '创建时间', updated_at: '更新时间' }; return m[p] ?? p }; function openPicker(f: string, o: any[]) { pickerField.value = f; pickerColumns.value = [o]; pickerShow.value = true }; function onPickerConfirm(e: any) { const v = e.value?.[0]; if (pickerField.value && v) form.value[pickerField.value] = v.value; pickerShow.value = false }; function openCreate() { editingId.value = ''; form.value = { sort: 99, status: 'ENABLED', is_visible: true, is_cache: false, is_affix: false }; formVisible.value = true }; function openEdit(item: any) { editingId.value = item.id; form.value = { ...item }; formVisible.value = true }; function openDetail(item: any) { detail.value = item; detailVisible.value = true }; async function doSave() { saving.value = true; try { const p: any = { ...form.value }; if (editingId.value) { await resourceApi.update({ ...p, id: editingId.value }) } else { await resourceApi.create(p) }; formVisible.value = false; await refresh() } finally { saving.value = false } }; function confirmDelete(item: any) { uni.showModal({ title: '确认删除', content: `删除 ${item.name}？`, success: async (r: any) => { if (r.confirm) { await resourceApi.remove({ ids: [item.id] }); await refresh() } } }) }
</script>
