<template>
  <Layout title="通知管理" back>
    <view class="flex flex-col"><view class="bg-white mx-4 mt-3 rounded-lg overflow-hidden"><view class="flex items-center gap-2 p-2"><u-search v-model="keyword" placeholder="搜索标题" :show-action="false" @search="onSearch" class="flex-1" /><u-button text="新增" type="primary" icon="plus" @click="openCreate" /></view></view><view v-for="item in records" :key="item.id" class="mx-4 mt-3 bg-white rounded-lg overflow-hidden"><view class="flex items-center justify-between px-4 py-3 border-b"><view class="flex flex-col"><text class="text-base font-bold text-gray-900">{{ item.title }}</text><text class="text-xs text-gray-500">{{ item.content || '-' }}</text></view><view class="flex gap-1"><u-button text="详情" size="mini" plain @click="openDetail(item)" /><u-button text="编辑" size="mini" plain @click="openEdit(item)" /><u-button v-if="item.status==='DRAFT'" text="发布" size="mini" plain type="primary" @click="doPublish(item)" /><u-button v-if="item.status==='PUBLISHED'" text="撤回" size="mini" plain type="warning" @click="doRevoke(item)" /><u-button text="删除" size="mini" plain type="error" @click="confirmDelete(item)" /></view></view><view class="px-4 py-2 flex flex-wrap gap-x-4 gap-y-1 text-xs text-gray-500"><text>级别: {{ dictLabel('NOTIFICATION_SEVERITY', item.severity) }}</text><text>状态: {{ dictLabel('NOTIFICATION_STATUS', item.status) }}</text><text>{{ formatDateTime(item.updated_at) }}</text></view></view><u-loadmore :status="loadStatus" /></view>
    <u-popup :show="formVisible" mode="bottom" :safe-area-inset-bottom="true" @close="formVisible = false"><view class="bg-white rounded-t-lg p-4" style="max-height: 70vh; overflow-y: auto;"><text class="block text-lg font-bold mb-4">{{ editingId ? '编辑通知' : '新增通知' }}</text><u-form :model="form"><u-form-item label="标题" required><u-input v-model="form.title" placeholder="请输入标题" border="none" /></u-form-item><u-form-item label="内容" required><u-textarea v-model="form.content" placeholder="请输入内容" border="none" /></u-form-item><u-form-item label="级别"><view class="w-full" @click="openPicker('severity', dictOptions('NOTIFICATION_SEVERITY'))"><u-input :value="dictLabel('NOTIFICATION_SEVERITY', form.severity)" placeholder="请选择" disabled border="none" /></view></u-form-item><u-form-item label="目标范围"><view class="w-full" @click="openPicker('target_scope', dictOptions('MESSAGE_TARGET_SCOPE'))"><u-input :value="dictLabel('MESSAGE_TARGET_SCOPE', form.target_scope)" placeholder="请选择" disabled border="none" /></view></u-form-item><u-form-item label="目标账号类型"><view class="w-full" @click="openPicker('target_account_type', dictOptions('ACCOUNT_TYPE'))"><u-input :value="dictLabel('ACCOUNT_TYPE', form.target_account_type)" placeholder="请选择" disabled border="none" /></view></u-form-item><u-form-item label="目标账号ID"><u-input v-model="form.target_account_id" placeholder="请输入" border="none" /></u-form-item><u-form-item label="状态"><view class="w-full" @click="openPicker('status', dictOptions('NOTIFICATION_STATUS'))"><u-input :value="dictLabel('NOTIFICATION_STATUS', form.status)" placeholder="请选择" disabled border="none" /></view></u-form-item></u-form><u-button text="保存" type="primary" :loading="saving" @click="doSave" class="mt-4" /></view></u-popup>
    <u-popup :show="detailVisible" mode="bottom" :safe-area-inset-bottom="true" @close="detailVisible = false"><view class="bg-white rounded-t-lg p-4" style="max-height: 70vh; overflow-y: auto;"><text class="block text-lg font-bold mb-4">通知详情</text><u-cell-group :border="false"><u-cell-item v-for="f in detailFields" :key="f" :title="detailLabel(f)" :value="displayVal(detail[f])" :arrow="false" /></u-cell-group></view></u-popup>
    <u-picker :show="pickerShow" :columns="pickerColumns" key-name="label" @confirm="onPickerConfirm" @close="pickerShow = false" />
  </Layout>
</template>
<script setup lang="ts">
import { computed, ref } from 'vue'; import { onLoad, onPullDownRefresh } from '@dcloudio/uni-app'; import Layout from '@/layouts/index.vue'; import { messageApi } from '@/api'; import { dictList } from '@/utils/dict'; import { displayValue, formatDateTime } from '@/utils/format'; import { fallbackDicts } from '@/config/resource'
const records = ref<any[]>([]); const keyword = ref(''); const current = ref(1); const total = ref(0); const loading = ref(false); const formVisible = ref(false); const detailVisible = ref(false); const saving = ref(false); const editingId = ref(''); const detail = ref<any>({}); const form = ref<Record<string, any>>({}); const pickerShow = ref(false); const pickerField = ref(''); const pickerColumns = ref<any[]>([[]])
const detailFields = ['id', 'title', 'content', 'severity', 'target_scope', 'target_account_type', 'target_account_id', 'status', 'publish_at', 'revoked_at', 'created_at', 'updated_at']
const loadStatus = computed(() => loading.value ? 'loading' : records.value.length >= total.value ? 'nomore' : 'loadmore')
onLoad(() => { refresh() }); onPullDownRefresh(async () => { await refresh(); uni.stopPullDownRefresh() })
async function refresh() { current.value = 1; await loadPage(false) }
async function loadPage(a: boolean) { loading.value = true; try { const p: any = { current: current.value, size: 20 }; if (keyword.value) p.title = keyword.value; const pg = await messageApi.notificationPage(p); records.value = a ? [...records.value, ...(pg.records ?? [])] : (pg.records ?? []); total.value = pg.total ?? 0 } finally { loading.value = false } }
function onSearch() { refresh() }; function dictOptions(c: string) { return dictList(c).length ? dictList(c) : fallbackDicts[c] ?? [] }; function dictLabel(c: string, v: any) { return dictOptions(c).find((o: any) => String(o.value) === String(v))?.label ?? v ?? '' }; function displayVal(v: any) { const dt = formatDateTime(v); return displayValue(dt !== v ? dt : v) }; function detailLabel(p: string) { const m: Record<string, string> = { id: 'ID', title: '标题', content: '内容', severity: '级别', target_scope: '目标范围', target_account_type: '目标账号类型', target_account_id: '目标账号ID', status: '状态', publish_at: '发布时间', revoked_at: '撤回时间', created_at: '创建时间', updated_at: '更新时间' }; return m[p] ?? p }; function openPicker(f: string, o: any[]) { pickerField.value = f; pickerColumns.value = [o]; pickerShow.value = true }; function onPickerConfirm(e: any) { const v = e.value?.[0]; if (pickerField.value && v) form.value[pickerField.value] = v.value; pickerShow.value = false }; function openCreate() { editingId.value = ''; form.value = { severity: 'INFO', target_scope: 'SPECIFIC', status: 'DRAFT' }; formVisible.value = true }; function openEdit(item: any) { editingId.value = item.id; form.value = { ...item }; formVisible.value = true }; function openDetail(item: any) { detail.value = item; detailVisible.value = true }
async function doSave() { saving.value = true; try { const p: any = { ...form.value }; if (editingId.value) { await messageApi.updateNotification({ ...p, id: editingId.value }) } else { await messageApi.createNotification(p) }; formVisible.value = false; await refresh() } finally { saving.value = false } }
function confirmDelete(item: any) { uni.showModal({ title: '确认删除', content: `删除 ${item.title}？`, success: async (r: any) => { if (r.confirm) { await messageApi.removeNotification({ ids: [item.id] }); await refresh() } } }) }
function doPublish(item: any) { uni.showModal({ title: '确认发布', content: `发布 ${item.title}？`, success: async (r: any) => { if (r.confirm) { await messageApi.publishNotification({ id: item.id }); await refresh() } } }) }
function doRevoke(item: any) { uni.showModal({ title: '确认撤回', content: `撤回 ${item.title}？`, success: async (r: any) => { if (r.confirm) { await messageApi.revokeNotification({ id: item.id }); await refresh() } } }) }
</script>
