<!--
  Generated by HEI code generator.
  Author: Charlie
  Generated at: 2026-07-28 20:51:13
-->

<script setup lang="ts">
import type { FormInst, FormRules } from 'naive-ui'
import { ojContestParticipationApi } from '@/api'
import { createRequiredRule, formatDateTime } from '@/utils'
import { computed, reactive, ref } from 'vue'
import { useRoute } from 'vue-router'

const route = useRoute()
const props = defineProps<{ contestId?: string, embedded?: boolean }>()
const contestId = computed(() => String(props.contestId ?? route.query.id ?? ''))

const emit = defineEmits<{
  saved: []
}>()

const formRef = ref<FormInst | null>(null)
const virtualOptions = [
  { label: '正式赛 (LIVE)', value: 0 },
  { label: '观赛 (SPECTATE)', value: -1 },
]

const defaultFormData: Record<string, any> = {
  contest_id: '',
  account_id: '',
  real_start: null,
  score: 0,
  cumtime: 0,
  tiebreaker: 0,
  is_disqualified: false,
  virtual: 0,
  rate_exclude: false,
  format_data: '{}',
}
const state = reactive({
  showModal: false,
  loading: false,
  submitLoading: false,
  dataId: null as string | null,
  formModel: normalizeFormData(),
})

const modalTitle = computed(() => state.dataId ? '编辑竞赛参赛' : '新增竞赛参赛')
const rules = computed<FormRules>(() => ({
  account_id: [
    createRequiredRule('账户ID', 'input'),
  ],
  real_start: [
    createRequiredRule('实际开始参赛时间', 'change'),
  ],
  score: [
    {
      validator: () => typeof state.formModel.score === 'number' && Number.isFinite(state.formModel.score),
      message: '请输入总分',
      trigger: ['input', 'blur'],
    },
  ],
  cumtime: [
    {
      validator: () => typeof state.formModel.cumtime === 'number' && Number.isFinite(state.formModel.cumtime),
      message: '请输入累计时间/罚时（秒）',
      trigger: ['input', 'blur'],
    },
  ],
  tiebreaker: [
    {
      validator: () => typeof state.formModel.tiebreaker === 'number' && Number.isFinite(state.formModel.tiebreaker),
      message: '请输入平分决胜值',
      trigger: ['input', 'blur'],
    },
  ],
  is_disqualified: [
    {
      validator: () => typeof state.formModel.is_disqualified === 'boolean',
      message: '请选择是否取消资格',
      trigger: 'change',
    },
  ],
  virtual: [
    {
      validator: () => typeof state.formModel.virtual === 'number' && Number.isFinite(state.formModel.virtual),
      message: '请选择虚拟状态',
      trigger: 'change',
    },
  ],
  rate_exclude: [
    {
      validator: () => typeof state.formModel.rate_exclude === 'boolean',
      message: '请选择是否排除 Rating',
      trigger: 'change',
    },
  ],
  format_data: [
    {
      validator: () => isValidJsonValue(state.formModel.format_data),
      message: '请输入合法 JSON 对象',
      trigger: ['input', 'blur'],
    },
  ],
}))

async function openModal(id?: string, defaults: Partial<typeof defaultFormData> = {}) {
  state.dataId = id ?? null
  state.formModel = normalizeFormData(defaults)
  state.showModal = true
  if (id) {
    await fetchDetail(id)
  }
}

async function fetchDetail(id: string) {
  state.loading = true
  try {
    const response = await ojContestParticipationApi.detail(contestId.value, { id })
    state.formModel = normalizeFormData(response.data ?? {})
  } finally {
    state.loading = false
  }
}

function normalizeFormData(data: Record<string, any> = {}) {
  return {
    ...defaultFormData,
    ...data,
    real_start: normalizeDateTimeValue(data.real_start),
    format_data: stringifyJsonValue(data.format_data),
  }
}

function normalizeDateTimeValue(value: unknown) {
  return formatDateTime(value, '') || null
}

function normalizeSubmitDateTimeValue(value: unknown) {
  const text = formatDateTime(value, '')
  if (!text) {
    return null
  }
  const date = new Date(`${text.replace(' ', 'T')}+08:00`)
  return Number.isNaN(date.getTime()) ? null : date.toISOString().replace(/\.\d{3}Z$/, 'Z')
}

function normalizeSubmitData(data: Record<string, any>) {
  return {
    ...data,
    real_start: normalizeSubmitDateTimeValue(data.real_start),
    format_data: parseJsonValue(data.format_data),
  }
}

function parseJsonValue(value: unknown) {
  const text = String(value ?? '').trim()
  if (!text) {
    return {}
  }
  const parsed = JSON.parse(text)
  if (Array.isArray(parsed) || typeof parsed !== 'object' || parsed === null) {
    throw new Error('JSON value must be an object')
  }
  return parsed
}

function isValidJsonValue(value: unknown) {
  try {
    parseJsonValue(value)
    return true
  } catch {
    return false
  }
}

function stringifyJsonValue(value: unknown) {
  if (value === undefined || value === null || value === '') {
    return '{}'
  }
  if (typeof value === 'string') {
    try {
      return JSON.stringify(JSON.parse(value), null, 2)
    } catch {
      return value
    }
  }
  return JSON.stringify(value, null, 2)
}

function closeModal() {
  state.showModal = false
  state.submitLoading = false
}

async function submitForm() {
  if (!contestId.value) {
    window.$message.error('缺少父级 ID')
    return
  }
  await formRef.value?.validate()
  state.submitLoading = true
  try {
    const payload = normalizeSubmitData(state.formModel)
    if (state.dataId) {
      await ojContestParticipationApi.update(contestId.value, { ...payload, id: state.dataId })
      window.$message.success('更新成功')
    } else {
      await ojContestParticipationApi.create(contestId.value, { ...payload, contest_id: contestId.value })
      window.$message.success('创建成功')
    }
    emit('saved')
    closeModal()
  } finally {
    state.submitLoading = false
  }
}

defineExpose({
  openModal,
})
</script>

<template>
  <NModal
    v-model:show="state.showModal"
    preset="card"
    draggable
    :mask-closable="false"
    :title="modalTitle"
    style="width: 720px"
    :segmented="{ content: true, action: true }"
  >
    <NSpin :show="state.loading">
      <NScrollbar class="max-h-[min(620px,calc(100vh-300px))] pr-16px">
        <NForm ref="formRef" :model="state.formModel" :rules="rules" label-placement="left" label-width="110" :disabled="state.loading || state.submitLoading">
          <NFormItem label="账户ID" path="account_id">
            <NInput v-model:value="state.formModel.account_id" />
          </NFormItem>
          <NFormItem label="实际开始参赛时间" path="real_start">
            <NDatePicker v-model:formatted-value="state.formModel.real_start" type="datetime" value-format="yyyy-MM-dd HH:mm:ss" class="w-full" clearable />
          </NFormItem>
          <NFormItem label="总分" path="score">
            <NInputNumber v-model:value="state.formModel.score" class="w-full" />
          </NFormItem>
          <NFormItem label="累计时间/罚时（秒）" path="cumtime">
            <NInputNumber v-model:value="state.formModel.cumtime" class="w-full" />
          </NFormItem>
          <NFormItem label="平分决胜值" path="tiebreaker">
            <NInputNumber v-model:value="state.formModel.tiebreaker" class="w-full" />
          </NFormItem>
          <NFormItem label="是否取消资格" path="is_disqualified">
            <NSwitch v-model:value="state.formModel.is_disqualified" />
          </NFormItem>
          <NFormItem label="虚拟状态" path="virtual">
            <NSelect v-model:value="state.formModel.virtual" :options="virtualOptions" class="w-full" />
          </NFormItem>
          <NFormItem label="排除 Rating" path="rate_exclude">
            <NSwitch v-model:value="state.formModel.rate_exclude" />
          </NFormItem>
          <NFormItem label="赛制私有数据" path="format_data">
            <NInput v-model:value="state.formModel.format_data" type="textarea" :autosize="{ minRows: 3, maxRows: 8 }" />
          </NFormItem>
        </NForm>
      </NScrollbar>
    </NSpin>

    <template #action>
      <NSpace justify="end">
        <NButton @click="closeModal">取消</NButton>
        <NButton type="primary" :loading="state.submitLoading" @click="submitForm">确认</NButton>
      </NSpace>
    </template>
  </NModal>
</template>
