"""
Generated by HEI code generator.
Author: Charlie
Generated at: 2026-07-28 20:51:13
"""

from app.platform.module import ModuleSpec, RouteSpec

module = ModuleSpec(
    name="biz.contest.problem",
    routes=(
        RouteSpec(
            version="v1",
            prefix="/admin",
            tags=("admin",),
            router="app.modules.biz.contest.problem.router:router",
        ),
    ),
    order=330,
    depends_on=("biz.contest.contest", "biz.problem.problem",),
    models=("app.modules.biz.contest.problem.model",),
)
