"""
Generated by HEI code generator.
Author: Charlie
Generated at: 2026-07-28 20:51:13
"""

from typing import Annotated

from fastapi import APIRouter, Depends, Query
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config.enums import AccountType
from app.core.response.pagination import Current, PageData, PageQuery, Size
from app.core.response.schema import ApiResponse, success
from app.core.schema.base import Id, IdQuery, IdsRequest
from app.deps.auth import require_account_type, require_permission
from app.deps.db import get_db_session
from app.modules.biz.contest.problem.schema import (
    OjContestProblemAdminPageQuery,
    OjContestProblemCreateRequest,
    OjContestProblemSchema,
    OjContestProblemUpdateRequest,
)
from app.modules.biz.contest.problem.service import (
    OjContestProblemService,
)

router = APIRouter()


@router.post(
    "/biz/contest/problem/create",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("biz:contest:problem:create")),
    ],
    response_model=ApiResponse[None],
)
async def create(
    contest_id: Annotated[Id, Query()],
    payload: OjContestProblemCreateRequest,
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[None]:
    await OjContestProblemService(db).create(contest_id, payload)
    return success()


@router.post(
    "/biz/contest/problem/update",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("biz:contest:problem:update")),
    ],
    response_model=ApiResponse[None],
)
async def update(
    contest_id: Annotated[Id, Query()],
    payload: OjContestProblemUpdateRequest,
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[None]:
    await OjContestProblemService(db).update(contest_id, payload)
    return success()


@router.post(
    "/biz/contest/problem/delete",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("biz:contest:problem:delete")),
    ],
    response_model=ApiResponse[None],
)
async def delete(
    contest_id: Annotated[Id, Query()],
    payload: IdsRequest,
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[None]:
    await OjContestProblemService(db).delete(contest_id, payload)
    return success()


@router.get(
    "/biz/contest/problem/detail",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("biz:contest:problem:detail")),
    ],
    response_model=ApiResponse[OjContestProblemSchema],
)
async def detail(
    contest_id: Annotated[Id, Query()],
    db: Annotated[AsyncSession, Depends(get_db_session)],
    id: Annotated[Id, Query()],
) -> ApiResponse[OjContestProblemSchema]:
    return success(await OjContestProblemService(db).detail(contest_id, IdQuery(id=id)))


@router.get(
    "/biz/contest/problem/page",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("biz:contest:problem:page")),
    ],
    response_model=ApiResponse[PageData[OjContestProblemSchema]],
)
async def page(
    contest_id: Annotated[Id, Query()],
    db: Annotated[AsyncSession, Depends(get_db_session)],
    current: Current = 1,
    size: Size = 20,
    problem_id: str | None = Query(default=None),
    problem_code: str | None = Query(default=None),
) -> ApiResponse[PageData[OjContestProblemSchema]]:
    query = OjContestProblemAdminPageQuery(
        pagination=PageQuery(current=current, size=size),
        problem_id=problem_id,
        problem_code=problem_code,
    )
    return success(await OjContestProblemService(db).page_admin(contest_id, query))
