"""
Generated by HEI code generator.
Author: Charlie
Generated at: 2026-07-28 20:51:13
"""

from typing import Annotated

from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config.enums import AccountType
from app.core.response.pagination import PageData
from app.core.response.schema import ApiResponse, success
from app.core.schema.base import ContestIdsRequest, ContestScopedIdQuery
from app.deps.auth import require_account_type, require_permission
from app.deps.db import get_db_session
from app.modules.biz.contest.problem.schema import (
    OjContestProblemAdminPageQuery,
    OjContestProblemCreateRequest,
    OjContestProblemSchema,
    OjContestProblemUpdateRequest,
)
from app.modules.biz.contest.problem.service import (
    OjContestProblemService,
)

router = APIRouter()


@router.post(
    "/biz/contest/problem/create",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("biz:contest:problem:create")),
    ],
    response_model=ApiResponse[None],
)
async def create(
    payload: OjContestProblemCreateRequest,
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[None]:
    await OjContestProblemService(db).create(payload)
    return success()


@router.post(
    "/biz/contest/problem/update",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("biz:contest:problem:update")),
    ],
    response_model=ApiResponse[None],
)
async def update(
    payload: OjContestProblemUpdateRequest,
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[None]:
    await OjContestProblemService(db).update(payload)
    return success()


@router.post(
    "/biz/contest/problem/delete",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("biz:contest:problem:delete")),
    ],
    response_model=ApiResponse[None],
)
async def delete(
    payload: ContestIdsRequest,
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[None]:
    await OjContestProblemService(db).delete(payload)
    return success()


@router.get(
    "/biz/contest/problem/detail",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("biz:contest:problem:detail")),
    ],
    response_model=ApiResponse[OjContestProblemSchema],
)
async def detail(
    query: Annotated[ContestScopedIdQuery, Depends()],
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[OjContestProblemSchema]:
    return success(await OjContestProblemService(db).detail(query))


@router.get(
    "/biz/contest/problem/page",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("biz:contest:problem:page")),
    ],
    response_model=ApiResponse[PageData[OjContestProblemSchema]],
)
async def page(
    query: Annotated[OjContestProblemAdminPageQuery, Depends()],
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[PageData[OjContestProblemSchema]]:
    return success(await OjContestProblemService(db).page_admin(query))
