<!--
  Generated by HEI code generator.
  Author: codegen_script
  Generated at: 2026-07-24 10:52:11
-->

<script setup lang="ts">
import { msgAnnouncementApi } from '@/api'
import { createTagColor, dictTypeColor, dictTypeData, displayValue, formatDateTime } from '@/utils'
import { reactive } from 'vue'

const state = reactive({
  showModal: false,
  loading: false,
  detail: {} as any,
})

async function openModal(id: string) {
  state.detail = {}
  state.showModal = true
  await fetchDetail(id)
}

async function fetchDetail(id: string) {
  state.loading = true
  try {
    const response = await msgAnnouncementApi.detail({ id })
    state.detail = response.data ?? {}
  } finally {
    state.loading = false
  }
}

function formatJsonValue(value: unknown) {
  if (value === undefined || value === null || value === '') {
    return '{}'
  }
  if (typeof value === 'string') {
    try {
      return JSON.stringify(JSON.parse(value), null, 2)
    } catch {
      return value
    }
  }
  return JSON.stringify(value, null, 2)
}

defineExpose({
  openModal,
})
</script>

<template>
  <NModal v-model:show="state.showModal" preset="card" draggable :mask-closable="false" title="公告管理详情" style="width: 680px">
    <NScrollbar class="max-h-[min(620px,calc(100vh-300px))] pr-16px">
      <NSpin :show="state.loading">
        <NDescriptions label-placement="left" bordered :column="1">
          <NDescriptionsItem label="主键">
            {{ displayValue(state.detail.id) }}
          </NDescriptionsItem>
          <NDescriptionsItem label="标题">
            {{ displayValue(state.detail.title) }}
          </NDescriptionsItem>
          <NDescriptionsItem label="内容">
            {{ displayValue(state.detail.content) }}
          </NDescriptionsItem>
          <NDescriptionsItem label="内容格式">
            {{ displayValue(state.detail.content_type) }}
          </NDescriptionsItem>
          <NDescriptionsItem label="等级">
            {{ displayValue(state.detail.severity) }}
          </NDescriptionsItem>
          <NDescriptionsItem label="目标范围">
            {{ displayValue(state.detail.target_scope) }}
          </NDescriptionsItem>
          <NDescriptionsItem label="目标账户类型">
            {{ displayValue(state.detail.target_account_type) }}
          </NDescriptionsItem>
          <NDescriptionsItem label="发布位置列表">
            <NCode :code="formatJsonValue(state.detail.publish_locations)" language="json" word-wrap />
          </NDescriptionsItem>
          <NDescriptionsItem label="是否置顶">
            {{ displayValue(state.detail.is_pinned) }}
          </NDescriptionsItem>
          <NDescriptionsItem label="置顶截止时间">
            {{ formatDateTime(state.detail.pinned_until) }}
          </NDescriptionsItem>
          <NDescriptionsItem label="发布者账户类型">
            {{ displayValue(state.detail.sender_account_type) }}
          </NDescriptionsItem>
          <NDescriptionsItem label="发布者账户ID">
            {{ displayValue(state.detail.sender_account_id) }}
          </NDescriptionsItem>
          <NDescriptionsItem label="状态">
            <NTag :color="createTagColor(dictTypeColor('COMMON_STATUS', state.detail.status))" :bordered="false">
              {{ dictTypeData('COMMON_STATUS', state.detail.status) || displayValue(state.detail.status) }}
            </NTag>
          </NDescriptionsItem>
          <NDescriptionsItem label="发布时间">
            {{ formatDateTime(state.detail.publish_at) }}
          </NDescriptionsItem>
          <NDescriptionsItem label="撤回时间">
            {{ formatDateTime(state.detail.revoked_at) }}
          </NDescriptionsItem>
          <NDescriptionsItem label="过期时间">
            {{ formatDateTime(state.detail.expire_at) }}
          </NDescriptionsItem>
          <NDescriptionsItem label="查看次数">
            {{ displayValue(state.detail.view_count) }}
          </NDescriptionsItem>
          <NDescriptionsItem label="扩展信息">
            <NCode :code="formatJsonValue(state.detail.extra)" language="json" word-wrap />
          </NDescriptionsItem>
          <NDescriptionsItem label="创建时间">{{ formatDateTime(state.detail.created_at) }}</NDescriptionsItem>
          <NDescriptionsItem label="创建人">{{ displayValue(state.detail.created_by) }}</NDescriptionsItem>
          <NDescriptionsItem label="更新时间">{{ formatDateTime(state.detail.updated_at) }}</NDescriptionsItem>
          <NDescriptionsItem label="更新人">{{ displayValue(state.detail.updated_by) }}</NDescriptionsItem>
        </NDescriptions>
      </NSpin>
    </NScrollbar>
  </NModal>
</template>
