<!--
  Generated by HEI code generator.
  Author: codegen_script
  Generated at: 2026-07-24 10:52:11
-->

<script setup lang="ts">
import type { FormInst, FormRules } from 'naive-ui'
import { msgAnnouncementApi } from '@/api'
import { createRequiredRule, formatDateTime } from '@/utils'
import { computed, reactive, ref } from 'vue'

const emit = defineEmits<{
  saved: []
}>()

const formRef = ref<FormInst | null>(null)
const defaultFormData: Record<string, any> = {
  title: '',
  content: '',
  content_type: '',
  severity: '',
  target_scope: '',
  target_account_type: '',
  publish_locations: '{}',
  is_pinned: false,
  pinned_until: null,
  sender_account_type: '',
  sender_account_id: '',
  status: '',
  publish_at: null,
  revoked_at: null,
  expire_at: null,
  view_count: 0,
  extra: '{}',
}
const state = reactive({
  showModal: false,
  loading: false,
  submitLoading: false,
  dataId: null as string | null,
  formModel: normalizeFormData(),
})

const modalTitle = computed(() => state.dataId ? '编辑公告管理' : '新增公告管理')
const rules = computed<FormRules>(() => ({
  title: [
    createRequiredRule('标题', 'input'),
  ],
  content: [
    createRequiredRule('内容', 'input'),
  ],
  content_type: [
    createRequiredRule('内容格式', 'input'),
  ],
  severity: [
    createRequiredRule('等级', 'input'),
  ],
  target_scope: [
    createRequiredRule('目标范围', 'input'),
  ],
  publish_locations: [
    createRequiredRule('发布位置列表', 'input'),
    {
      validator: () => isValidJsonValue(state.formModel.publish_locations),
      message: '请输入合法 JSON 对象',
      trigger: ['input', 'blur'],
    },
  ],
  is_pinned: [
    {
      validator: () => typeof state.formModel.is_pinned === 'boolean',
      message: '请选择是否置顶',
      trigger: 'change',
    },
  ],
  status: [
    createRequiredRule('状态', 'change'),
  ],
  view_count: [
    {
      validator: () => typeof state.formModel.view_count === 'number' && Number.isFinite(state.formModel.view_count),
      message: '请输入查看次数',
      trigger: ['input', 'blur'],
    },
  ],
  extra: [
    createRequiredRule('扩展信息', 'input'),
    {
      validator: () => isValidJsonValue(state.formModel.extra),
      message: '请输入合法 JSON 对象',
      trigger: ['input', 'blur'],
    },
  ],
}))

async function openModal(id?: string, defaults: Partial<typeof defaultFormData> = {}) {
  state.dataId = id ?? null
  state.formModel = normalizeFormData(defaults)
  state.showModal = true
  if (id) {
    await fetchDetail(id)
  }
}

async function fetchDetail(id: string) {
  state.loading = true
  try {
    const response = await msgAnnouncementApi.detail({ id })
    state.formModel = normalizeFormData(response.data ?? {})
  } finally {
    state.loading = false
  }
}

function normalizeFormData(data: Record<string, any> = {}) {
  return {
    ...defaultFormData,
    ...data,
    pinned_until: normalizeDateTimeValue(data.pinned_until),
    publish_at: normalizeDateTimeValue(data.publish_at),
    revoked_at: normalizeDateTimeValue(data.revoked_at),
    expire_at: normalizeDateTimeValue(data.expire_at),
    publish_locations: stringifyJsonValue(data.publish_locations),
    extra: stringifyJsonValue(data.extra),
  }
}

function normalizeDateTimeValue(value: unknown) {
  return formatDateTime(value, '') || null
}

function normalizeSubmitDateTimeValue(value: unknown) {
  const text = formatDateTime(value, '')
  if (!text) {
    return null
  }
  const date = new Date(`${text.replace(' ', 'T')}+08:00`)
  return Number.isNaN(date.getTime()) ? null : date.toISOString().replace(/\.\d{3}Z$/, 'Z')
}

function normalizeSubmitData(data: Record<string, any>) {
  return {
    ...data,
    pinned_until: normalizeSubmitDateTimeValue(data.pinned_until),
    publish_at: normalizeSubmitDateTimeValue(data.publish_at),
    revoked_at: normalizeSubmitDateTimeValue(data.revoked_at),
    expire_at: normalizeSubmitDateTimeValue(data.expire_at),
    publish_locations: parseJsonValue(data.publish_locations),
    extra: parseJsonValue(data.extra),
  }
}

function parseJsonValue(value: unknown) {
  const text = String(value ?? '').trim()
  if (!text) {
    return {}
  }
  const parsed = JSON.parse(text)
  if (Array.isArray(parsed) || typeof parsed !== 'object' || parsed === null) {
    throw new Error('JSON value must be an object')
  }
  return parsed
}

function isValidJsonValue(value: unknown) {
  try {
    parseJsonValue(value)
    return true
  } catch {
    return false
  }
}

function stringifyJsonValue(value: unknown) {
  if (value === undefined || value === null || value === '') {
    return '{}'
  }
  if (typeof value === 'string') {
    try {
      return JSON.stringify(JSON.parse(value), null, 2)
    } catch {
      return value
    }
  }
  return JSON.stringify(value, null, 2)
}

function closeModal() {
  state.showModal = false
  state.submitLoading = false
}

async function submitForm() {
  await formRef.value?.validate()
  state.submitLoading = true
  try {
    const payload = normalizeSubmitData(state.formModel)
    if (state.dataId) {
      await msgAnnouncementApi.update({ ...payload, id: state.dataId })
      window.$message.success('更新成功')
    } else {
      await msgAnnouncementApi.create(payload)
      window.$message.success('创建成功')
    }
    emit('saved')
    closeModal()
  } finally {
    state.submitLoading = false
  }
}

defineExpose({
  openModal,
})
</script>

<template>
  <NModal
    v-model:show="state.showModal"
    preset="card"
    draggable
    :mask-closable="false"
    :title="modalTitle"
    style="width: 720px"
    :segmented="{ content: true, action: true }"
  >
    <NSpin :show="state.loading">
      <NScrollbar class="max-h-[min(620px,calc(100vh-300px))] pr-16px">
        <NForm ref="formRef" :model="state.formModel" :rules="rules" label-placement="left" label-width="110" :disabled="state.loading || state.submitLoading">
          <NFormItem label="标题" path="title">
            <NInput v-model:value="state.formModel.title" />
          </NFormItem>
          <NFormItem label="内容" path="content">
            <NInput v-model:value="state.formModel.content" type="textarea" :autosize="{ minRows: 3, maxRows: 8 }" />
          </NFormItem>
          <NFormItem label="内容格式" path="content_type">
            <NInput v-model:value="state.formModel.content_type" type="textarea" :autosize="{ minRows: 3, maxRows: 8 }" />
          </NFormItem>
          <NFormItem label="等级" path="severity">
            <NInput v-model:value="state.formModel.severity" />
          </NFormItem>
          <NFormItem label="目标范围" path="target_scope">
            <NInput v-model:value="state.formModel.target_scope" />
          </NFormItem>
          <NFormItem label="目标账户类型" path="target_account_type">
            <NInput v-model:value="state.formModel.target_account_type" />
          </NFormItem>
          <NFormItem label="发布位置列表" path="publish_locations">
            <NInput v-model:value="state.formModel.publish_locations" type="textarea" :autosize="{ minRows: 4, maxRows: 12 }" />
          </NFormItem>
          <NFormItem label="是否置顶" path="is_pinned">
            <NSwitch v-model:value="state.formModel.is_pinned" />
          </NFormItem>
          <NFormItem label="置顶截止时间" path="pinned_until">
            <NDatePicker v-model:formatted-value="state.formModel.pinned_until" type="datetime" value-format="yyyy-MM-dd HH:mm:ss" class="w-full" clearable />
          </NFormItem>
          <NFormItem label="发布者账户类型" path="sender_account_type">
            <NInput v-model:value="state.formModel.sender_account_type" />
          </NFormItem>
          <NFormItem label="发布者账户ID" path="sender_account_id">
            <NInput v-model:value="state.formModel.sender_account_id" />
          </NFormItem>
          <NFormItem label="状态" path="status">
            <DictSelect v-model="state.formModel.status" dict-code="COMMON_STATUS" />
          </NFormItem>
          <NFormItem label="发布时间" path="publish_at">
            <NDatePicker v-model:formatted-value="state.formModel.publish_at" type="datetime" value-format="yyyy-MM-dd HH:mm:ss" class="w-full" clearable />
          </NFormItem>
          <NFormItem label="撤回时间" path="revoked_at">
            <NDatePicker v-model:formatted-value="state.formModel.revoked_at" type="datetime" value-format="yyyy-MM-dd HH:mm:ss" class="w-full" clearable />
          </NFormItem>
          <NFormItem label="过期时间" path="expire_at">
            <NDatePicker v-model:formatted-value="state.formModel.expire_at" type="datetime" value-format="yyyy-MM-dd HH:mm:ss" class="w-full" clearable />
          </NFormItem>
          <NFormItem label="查看次数" path="view_count">
            <NInputNumber v-model:value="state.formModel.view_count" class="w-full" />
          </NFormItem>
          <NFormItem label="扩展信息" path="extra">
            <NInput v-model:value="state.formModel.extra" type="textarea" :autosize="{ minRows: 4, maxRows: 12 }" />
          </NFormItem>
        </NForm>
      </NScrollbar>
    </NSpin>

    <template #action>
      <NSpace justify="end">
        <NButton @click="closeModal">取消</NButton>
        <NButton type="primary" :loading="state.submitLoading" @click="submitForm">确认</NButton>
      </NSpace>
    </template>
  </NModal>
</template>
