/**
 * 静态资源路由表。
 *
 * 这里模拟后端 sys_resource 表返回的数据结构，字段需要与 AppRoute.RowRoute / SysResource 保持一致。
 * 注意：这里的 path 是资源自身路径，不使用 VITE_HOME_PATH；VITE_HOME_PATH 只负责默认首页跳转。
 */
export const staticRoutes: AppRoute.RowRoute[] = [
  {
    // 工作台：普通菜单页面，同时作为固定标签页展示。
    id: '1',
    parent_id: null,
    code: 'dashboard',
    name: '工作台',
    resource_type: 'MENU',
    module: 'system',
    path: '/dashboard',
    component: '/dashboard/index.vue',
    redirect: null,
    icon: 'icon-park-outline:analysis',
    href: null,
    sort: 1,
    is_visible: true,
    is_cache: false,
    is_affix: true,
    status: 'ENABLED',
    description: null,
  },
  {
    // 示例目录：CATALOG 只负责菜单分组，不直接加载页面组件。
    id: '2',
    parent_id: null,
    code: 'demo',
    name: '示例页面',
    resource_type: 'CATALOG',
    module: 'system',
    path: '/demo',
    component: null,
    redirect: null,
    icon: 'icon-park-outline:application-one',
    href: null,
    sort: 20,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    // 系统管理：CATALOG 只负责菜单分组，不直接加载页面组件。
    id: '3',
    parent_id: null,
    code: 'sys',
    name: '系统管理',
    resource_type: 'CATALOG',
    module: 'system',
    path: '/sys',
    component: null,
    redirect: null,
    icon: 'icon-park-outline:setting-two',
    href: null,
    sort: 10,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    // 字典管理：左树右表的本地模拟 CRUD 示例。
    id: '302',
    parent_id: '3',
    code: 'sys-dict',
    name: '字典管理',
    resource_type: 'MENU',
    module: 'system',
    path: '/sys/dict',
    component: '/sys/dict/index.vue',
    redirect: null,
    icon: 'icon-park-outline:file-search',
    href: null,
    sort: 2,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    // 展示图管理：使用后端展示图管理接口的 CRUD 示例。
    id: '303',
    parent_id: '3',
    code: 'sys-banner',
    name: '展示图管理',
    resource_type: 'MENU',
    module: 'system',
    path: '/sys/banner',
    component: '/sys/banner/index.vue',
    redirect: null,
    icon: 'icon-park-outline:ad-product',
    href: null,
    sort: 3,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    id: '4',
    parent_id: null,
    code: 'iam',
    name: '身份权限',
    resource_type: 'CATALOG',
    module: 'system',
    path: '/iam',
    component: null,
    redirect: null,
    icon: 'icon-park-outline:permissions',
    href: null,
    sort: 15,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    id: '401',
    parent_id: '4',
    code: 'iam-account',
    name: '账号管理',
    resource_type: 'MENU',
    module: 'system',
    path: '/iam/account',
    component: '/iam/account/index.vue',
    redirect: null,
    icon: 'icon-park-outline:people',
    href: null,
    sort: 1,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    id: '402',
    parent_id: '4',
    code: 'iam-dept',
    name: '部门管理',
    resource_type: 'MENU',
    module: 'system',
    path: '/iam/dept',
    component: '/iam/dept/index.vue',
    redirect: null,
    icon: 'icon-park-outline:tree-diagram',
    href: null,
    sort: 2,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    id: '403',
    parent_id: '4',
    code: 'iam-group',
    name: '用户组管理',
    resource_type: 'MENU',
    module: 'system',
    path: '/iam/group',
    component: '/iam/group/index.vue',
    redirect: null,
    icon: 'icon-park-outline:group',
    href: null,
    sort: 3,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    id: '404',
    parent_id: '4',
    code: 'iam-position',
    name: '岗位管理',
    resource_type: 'MENU',
    module: 'system',
    path: '/iam/position',
    component: '/iam/position/index.vue',
    redirect: null,
    icon: 'icon-park-outline:people-bottom',
    href: null,
    sort: 4,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    id: '405',
    parent_id: '4',
    code: 'iam-role',
    name: '角色管理',
    resource_type: 'MENU',
    module: 'system',
    path: '/iam/role',
    component: '/iam/role/index.vue',
    redirect: null,
    icon: 'icon-park-outline:peoples',
    href: null,
    sort: 5,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    id: '406',
    parent_id: '4',
    code: 'iam-resource',
    name: '资源管理',
    resource_type: 'MENU',
    module: 'system',
    path: '/iam/resource',
    component: '/iam/resource/index.vue',
    redirect: null,
    icon: 'icon-park-outline:all-application',
    href: null,
    sort: 6,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    // 示例总览：普通菜单页面，并开启页面缓存。
    id: '201',
    parent_id: '2',
    code: 'demo-overview',
    name: '示例总览',
    resource_type: 'MENU',
    module: 'system',
    path: '/demo/overview',
    component: '/demo/overview/index.vue',
    redirect: null,
    icon: 'icon-park-outline:dashboard-one',
    href: null,
    sort: 1,
    is_visible: true,
    is_cache: true,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    // 列表示例：普通菜单页面，详情页会从这里跳转进入。
    id: '202',
    parent_id: '2',
    code: 'demo-list',
    name: '列表示例',
    resource_type: 'MENU',
    module: 'system',
    path: '/demo/list',
    component: '/demo/list/index.vue',
    redirect: null,
    icon: 'icon-park-outline:list-view',
    href: null,
    sort: 2,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    // 表单示例：普通菜单页面。
    id: '203',
    parent_id: '2',
    code: 'demo-form',
    name: '表单示例',
    resource_type: 'MENU',
    module: 'system',
    path: '/demo/form',
    component: '/demo/form/index.vue',
    redirect: null,
    icon: 'icon-park-outline:edit',
    href: null,
    sort: 3,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    // 图表示例：普通菜单页面。
    id: '204',
    parent_id: '2',
    code: 'demo-chart',
    name: '图表示例',
    resource_type: 'MENU',
    module: 'system',
    path: '/demo/chart',
    component: '/demo/chart/index.vue',
    redirect: null,
    icon: 'icon-park-outline:chart-line',
    href: null,
    sort: 4,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    // 详情示例：PAGE 页面可通过路由访问，但 is_visible=false 表示不显示在侧边菜单和搜索中。
    id: '205',
    parent_id: '2',
    code: 'demo-detail',
    name: '详情示例',
    resource_type: 'PAGE',
    module: 'system',
    path: '/demo/detail',
    component: '/demo/detail/index.vue',
    redirect: null,
    icon: 'icon-park-outline:doc-detail',
    href: null,
    sort: 5,
    is_visible: false,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
]
