/**
 * 静态资源路由表。
 *
 * 这里模拟后端 sys_resource 表返回的数据结构，字段需要与 AppRoute.RowRoute / SysResource 保持一致。
 * 注意：这里的 path 是资源自身路径，不使用 VITE_HOME_PATH；VITE_HOME_PATH 只负责默认首页跳转。
 */
export const staticRoutes: AppRoute.RowRoute[] = [
  {
    // 工作台：普通菜单页面，同时作为固定标签页展示。
    id: '1',
    parent_id: null,
    code: 'dashboard',
    name: '运营工作台',
    resource_type: 'MENU',
    module_id: '210001',
    module_id_name: '系统',
    path: '/dashboard',
    component: '/dashboard/index.vue',
    redirect: null,
    icon: 'icon-park-outline:analysis',
    href: null,
    sort: 1,
    is_visible: true,
    is_cache: false,
    is_affix: true,
    status: 'ENABLED',
    description: null,
  },
  {
    // 系统管理：CATALOG 只负责菜单分组，不直接加载页面组件。
    id: '3',
    parent_id: null,
    code: 'sys',
    name: '系统',
    resource_type: 'CATALOG',
    module_id: '210001',
    module_id_name: '系统',
    path: '/sys',
    component: null,
    redirect: null,
    icon: 'icon-park-outline:setting-two',
    href: null,
    sort: 10,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    // 字典管理：左树右表的本地模拟 CRUD 示例。
    id: '302',
    parent_id: '3',
    code: 'sys-dict',
    name: '字典管理',
    resource_type: 'MENU',
    module_id: '210001',
    module_id_name: '系统',
    path: '/sys/dict',
    component: '/sys/dict/index.vue',
    redirect: null,
    icon: 'icon-park-outline:file-search',
    href: null,
    sort: 2,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    // 展示图管理：使用后端展示图管理接口的 CRUD 示例。
    id: '303',
    parent_id: '3',
    code: 'sys-banner',
    name: '展示图管理',
    resource_type: 'MENU',
    module_id: '210001',
    module_id_name: '系统',
    path: '/sys/banner',
    component: '/sys/banner/index.vue',
    redirect: null,
    icon: 'icon-park-outline:ad-product',
    href: null,
    sort: 3,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    // 文件管理：后台上传文件元数据与对象存储文件管理。
    id: '304',
    parent_id: '3',
    code: 'sys-file',
    name: '文件管理',
    resource_type: 'MENU',
    module_id: '210001',
    module_id_name: '系统',
    path: '/sys/file',
    component: '/sys/file/index.vue',
    redirect: null,
    icon: 'icon-park-outline:file-code',
    href: null,
    sort: 4,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    id: '305',
    parent_id: '3',
    code: 'sys-codegen',
    name: '代码生成',
    resource_type: 'MENU',
    module_id: '210001',
    module_id_name: '系统',
    path: '/sys/codegen',
    component: '/sys/codegen/index.vue',
    redirect: null,
    icon: 'icon-park-outline:code',
    href: null,
    sort: 5,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    id: '6',
    parent_id: null,
    code: 'security',
    name: '认证',
    resource_type: 'CATALOG',
    module_id: '210001',
    module_id_name: '系统',
    path: '/security',
    component: null,
    redirect: null,
    icon: 'icon-park-outline:lock',
    href: null,
    sort: 12,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    id: '601',
    parent_id: '6',
    code: 'security-session',
    name: '在线会话',
    resource_type: 'MENU',
    module_id: '210001',
    module_id_name: '系统',
    path: '/security/session',
    component: '/auth/session/index.vue',
    redirect: null,
    icon: 'icon-park-outline:connection',
    href: null,
    sort: 1,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    id: '4',
    parent_id: null,
    code: 'iam',
    name: '身份与权限',
    resource_type: 'CATALOG',
    module_id: '210001',
    module_id_name: '系统',
    path: '/iam',
    component: null,
    redirect: null,
    icon: 'icon-park-outline:permissions',
    href: null,
    sort: 15,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    id: '401',
    parent_id: '4',
    code: 'iam-account',
    name: '账号管理',
    resource_type: 'MENU',
    module_id: '210001',
    module_id_name: '系统',
    path: '/iam/account',
    component: '/iam/account/index.vue',
    redirect: null,
    icon: 'icon-park-outline:people',
    href: null,
    sort: 1,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    id: '402',
    parent_id: '4',
    code: 'iam-dept',
    name: '部门管理',
    resource_type: 'MENU',
    module_id: '210001',
    module_id_name: '系统',
    path: '/iam/dept',
    component: '/iam/dept/index.vue',
    redirect: null,
    icon: 'icon-park-outline:tree-diagram',
    href: null,
    sort: 2,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    id: '403',
    parent_id: '4',
    code: 'iam-group',
    name: '用户组管理',
    resource_type: 'MENU',
    module_id: '210001',
    module_id_name: '系统',
    path: '/iam/group',
    component: '/iam/group/index.vue',
    redirect: null,
    icon: 'icon-park-outline:group',
    href: null,
    sort: 3,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    id: '404',
    parent_id: '4',
    code: 'iam-position',
    name: '岗位管理',
    resource_type: 'MENU',
    module_id: '210001',
    module_id_name: '系统',
    path: '/iam/position',
    component: '/iam/position/index.vue',
    redirect: null,
    icon: 'icon-park-outline:people-bottom',
    href: null,
    sort: 4,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    id: '405',
    parent_id: '4',
    code: 'iam-role',
    name: '角色管理',
    resource_type: 'MENU',
    module_id: '210001',
    module_id_name: '系统',
    path: '/iam/role',
    component: '/iam/role/index.vue',
    redirect: null,
    icon: 'icon-park-outline:peoples',
    href: null,
    sort: 5,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    id: '406',
    parent_id: '4',
    code: 'iam-resource',
    name: '资源管理',
    resource_type: 'MENU',
    module_id: '210001',
    module_id_name: '系统',
    path: '/iam/resource',
    component: '/iam/resource/index.vue',
    redirect: null,
    icon: 'icon-park-outline:all-application',
    href: null,
    sort: 6,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    id: '407',
    parent_id: '4',
    code: 'iam-resourcemodule',
    name: '资源模块管理',
    resource_type: 'MENU',
    module_id: '210001',
    module_id_name: '系统',
    path: '/iam/resource_module',
    component: '/iam/resource_module/index.vue',
    redirect: null,
    icon: 'icon-park-outline:blocks-and-arrows',
    href: null,
    sort: 7,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    id: '5',
    parent_id: null,
    code: 'message',
    name: '消息中心',
    resource_type: 'CATALOG',
    module_id: '210001',
    module_id_name: '系统',
    path: '/message',
    component: null,
    redirect: null,
    icon: 'icon-park-outline:message',
    href: null,
    sort: 18,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    id: '501',
    parent_id: '5',
    code: 'message-notification',
    name: '通知',
    resource_type: 'MENU',
    module_id: '210001',
    module_id_name: '系统',
    path: '/message/notification',
    component: '/message/notification/index.vue',
    redirect: null,
    icon: 'icon-park-outline:tips-one',
    href: null,
    sort: 1,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    id: '502',
    parent_id: '5',
    code: 'message-im',
    name: '站内信',
    resource_type: 'MENU',
    module_id: '210001',
    module_id_name: '系统',
    path: '/message/im',
    component: '/message/im/index.vue',
    redirect: null,
    icon: 'icon-park-outline:message',
    href: null,
    sort: 2,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
    is_fullscreen: true,
  },
  {
    id: '503',
    parent_id: '5',
    code: 'message-todo',
    name: '待办',
    resource_type: 'MENU',
    module_id: '210001',
    module_id_name: '系统',
    path: '/message/todo',
    component: '/message/todo/index.vue',
    redirect: null,
    icon: 'icon-park-outline:checklist',
    href: null,
    sort: 3,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    id: '5202000',
    parent_id: null,
    code: 'oj',
    name: '在线判题',
    resource_type: 'CATALOG',
    module_id: '210001',
    module_id_name: '系统',
    path: '/oj',
    component: null,
    redirect: null,
    icon: 'icon-park-outline:code-computer',
    href: null,
    sort: 20,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: '在线判题管理目录',
  },
  {
    id: '5202001',
    parent_id: '5202000',
    code: 'oj-problem',
    name: '题目管理',
    resource_type: 'MENU',
    module_id: '210001',
    module_id_name: '系统',
    path: '/oj/problem',
    component: '/oj/problem/index.vue',
    redirect: null,
    icon: 'icon-park-outline:book-open',
    href: null,
    sort: 1,
    is_visible: true,
    is_cache: true,
    is_affix: false,
    status: 'ENABLED',
    description: '题目聚合维护',
  },
]
