-- Generated by HEI code generator.
-- Author: Charlie
-- Generated at: 2026-07-28 20:51:13
-- Adjust module_id/parent_id before executing when needed.
BEGIN;

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, path, component, icon, sort, is_visible, is_cache, is_affix, status, description, extra)
VALUES (
  '7487852165730537472',
  NULLIF(NULL, ''),
  'biz_contest_problem',
  '竞赛题目',
  'MENU',
  NULLIF(NULL, ''),
  '/biz/contest/problem',
  '/biz/contest/problem/index.vue',
  'icon-park-outline:code',
  70,
  true,
  false,
  false,
  'ENABLED',
  NULL,
  '{}'
)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name, path = EXCLUDED.path, component = EXCLUDED.component, updated_at = now();

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, sort, is_visible, is_cache, is_affix, status, extra)
VALUES (
  '7487852165730537473',
  '7487852165730537472',
  'biz_contest_problem_page',
  '分页竞赛题目',
  'BUTTON',
  NULLIF(NULL, ''),
  10,
  false,
  false,
  false,
  'ENABLED',
  '{}'
)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, updated_at = now();

INSERT INTO sys_iam_relation (id, subject_type, subject_id, relation_type, target_type, target_id, target_key, grant_mode, effect, data_scope, custom_scope_dept_ids, is_primary, sort, status, description, extra)
VALUES (
  '7487852165730537474',
  'RESOURCE',
  '7487852165730537473',
  'RESOURCE_PERMISSION',
  'PERMISSION',
  '',
  'biz:contest:problem:page',
  'CASCADE',
  'ALLOW',
  'ALL',
  '[]',
  false,
  10,
  'ENABLED',
  '分页竞赛题目',
  '{}'
)
ON CONFLICT (id)
DO UPDATE SET description = EXCLUDED.description, updated_at = now();

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, sort, is_visible, is_cache, is_affix, status, extra)
VALUES (
  '7487852165730537475',
  '7487852165730537472',
  'biz_contest_problem_create',
  '新增竞赛题目',
  'BUTTON',
  NULLIF(NULL, ''),
  20,
  false,
  false,
  false,
  'ENABLED',
  '{}'
)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, updated_at = now();

INSERT INTO sys_iam_relation (id, subject_type, subject_id, relation_type, target_type, target_id, target_key, grant_mode, effect, data_scope, custom_scope_dept_ids, is_primary, sort, status, description, extra)
VALUES (
  '7487852165730537476',
  'RESOURCE',
  '7487852165730537475',
  'RESOURCE_PERMISSION',
  'PERMISSION',
  '',
  'biz:contest:problem:create',
  'CASCADE',
  'ALLOW',
  'ALL',
  '[]',
  false,
  20,
  'ENABLED',
  '新增竞赛题目',
  '{}'
)
ON CONFLICT (id)
DO UPDATE SET description = EXCLUDED.description, updated_at = now();

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, sort, is_visible, is_cache, is_affix, status, extra)
VALUES (
  '7487852165730537477',
  '7487852165730537472',
  'biz_contest_problem_detail',
  '详情竞赛题目',
  'BUTTON',
  NULLIF(NULL, ''),
  30,
  false,
  false,
  false,
  'ENABLED',
  '{}'
)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, updated_at = now();

INSERT INTO sys_iam_relation (id, subject_type, subject_id, relation_type, target_type, target_id, target_key, grant_mode, effect, data_scope, custom_scope_dept_ids, is_primary, sort, status, description, extra)
VALUES (
  '7487852165730537478',
  'RESOURCE',
  '7487852165730537477',
  'RESOURCE_PERMISSION',
  'PERMISSION',
  '',
  'biz:contest:problem:detail',
  'CASCADE',
  'ALLOW',
  'ALL',
  '[]',
  false,
  30,
  'ENABLED',
  '详情竞赛题目',
  '{}'
)
ON CONFLICT (id)
DO UPDATE SET description = EXCLUDED.description, updated_at = now();

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, sort, is_visible, is_cache, is_affix, status, extra)
VALUES (
  '7487852165730537479',
  '7487852165730537472',
  'biz_contest_problem_update',
  '编辑竞赛题目',
  'BUTTON',
  NULLIF(NULL, ''),
  40,
  false,
  false,
  false,
  'ENABLED',
  '{}'
)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, updated_at = now();

INSERT INTO sys_iam_relation (id, subject_type, subject_id, relation_type, target_type, target_id, target_key, grant_mode, effect, data_scope, custom_scope_dept_ids, is_primary, sort, status, description, extra)
VALUES (
  '7487852165730537480',
  'RESOURCE',
  '7487852165730537479',
  'RESOURCE_PERMISSION',
  'PERMISSION',
  '',
  'biz:contest:problem:update',
  'CASCADE',
  'ALLOW',
  'ALL',
  '[]',
  false,
  40,
  'ENABLED',
  '编辑竞赛题目',
  '{}'
)
ON CONFLICT (id)
DO UPDATE SET description = EXCLUDED.description, updated_at = now();

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, sort, is_visible, is_cache, is_affix, status, extra)
VALUES (
  '7487852165730537481',
  '7487852165730537472',
  'biz_contest_problem_delete',
  '删除竞赛题目',
  'BUTTON',
  NULLIF(NULL, ''),
  50,
  false,
  false,
  false,
  'ENABLED',
  '{}'
)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, updated_at = now();

INSERT INTO sys_iam_relation (id, subject_type, subject_id, relation_type, target_type, target_id, target_key, grant_mode, effect, data_scope, custom_scope_dept_ids, is_primary, sort, status, description, extra)
VALUES (
  '7487852165730537482',
  'RESOURCE',
  '7487852165730537481',
  'RESOURCE_PERMISSION',
  'PERMISSION',
  '',
  'biz:contest:problem:delete',
  'CASCADE',
  'ALLOW',
  'ALL',
  '[]',
  false,
  50,
  'ENABLED',
  '删除竞赛题目',
  '{}'
)
ON CONFLICT (id)
DO UPDATE SET description = EXCLUDED.description, updated_at = now();

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, sort, is_visible, is_cache, is_affix, status, extra)
VALUES (
  '7487852165730537483',
  '7487852165730537472',
  'biz_contest_problem_tables',
  '读取数据表竞赛题目',
  'BUTTON',
  NULLIF(NULL, ''),
  60,
  false,
  false,
  false,
  'ENABLED',
  '{}'
)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, updated_at = now();

INSERT INTO sys_iam_relation (id, subject_type, subject_id, relation_type, target_type, target_id, target_key, grant_mode, effect, data_scope, custom_scope_dept_ids, is_primary, sort, status, description, extra)
VALUES (
  '7487852165730537484',
  'RESOURCE',
  '7487852165730537483',
  'RESOURCE_PERMISSION',
  'PERMISSION',
  '',
  'biz:contest:problem:tables',
  'CASCADE',
  'ALLOW',
  'ALL',
  '[]',
  false,
  60,
  'ENABLED',
  '读取数据表竞赛题目',
  '{}'
)
ON CONFLICT (id)
DO UPDATE SET description = EXCLUDED.description, updated_at = now();

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, sort, is_visible, is_cache, is_affix, status, extra)
VALUES (
  '7487852165730537485',
  '7487852165730537472',
  'biz_contest_problem_preview',
  '预览竞赛题目',
  'BUTTON',
  NULLIF(NULL, ''),
  70,
  false,
  false,
  false,
  'ENABLED',
  '{}'
)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, updated_at = now();

INSERT INTO sys_iam_relation (id, subject_type, subject_id, relation_type, target_type, target_id, target_key, grant_mode, effect, data_scope, custom_scope_dept_ids, is_primary, sort, status, description, extra)
VALUES (
  '7487852165730537486',
  'RESOURCE',
  '7487852165730537485',
  'RESOURCE_PERMISSION',
  'PERMISSION',
  '',
  'biz:contest:problem:preview',
  'CASCADE',
  'ALLOW',
  'ALL',
  '[]',
  false,
  70,
  'ENABLED',
  '预览竞赛题目',
  '{}'
)
ON CONFLICT (id)
DO UPDATE SET description = EXCLUDED.description, updated_at = now();

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, sort, is_visible, is_cache, is_affix, status, extra)
VALUES (
  '7487852165730537487',
  '7487852165730537472',
  'biz_contest_problem_download',
  '下载竞赛题目',
  'BUTTON',
  NULLIF(NULL, ''),
  80,
  false,
  false,
  false,
  'ENABLED',
  '{}'
)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, updated_at = now();

INSERT INTO sys_iam_relation (id, subject_type, subject_id, relation_type, target_type, target_id, target_key, grant_mode, effect, data_scope, custom_scope_dept_ids, is_primary, sort, status, description, extra)
VALUES (
  '7487852165730537488',
  'RESOURCE',
  '7487852165730537487',
  'RESOURCE_PERMISSION',
  'PERMISSION',
  '',
  'biz:contest:problem:download',
  'CASCADE',
  'ALLOW',
  'ALL',
  '[]',
  false,
  80,
  'ENABLED',
  '下载竞赛题目',
  '{}'
)
ON CONFLICT (id)
DO UPDATE SET description = EXCLUDED.description, updated_at = now();

COMMIT;
