-- Generated by HEI code generator.
-- Author: Charlie
-- Generated at: 2026-07-28 20:51:12
-- Adjust module_id/parent_id before executing when needed.
BEGIN;

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, path, component, icon, sort, is_visible, is_cache, is_affix, status, description, extra)
VALUES (
  '7487852161095831552',
  NULLIF(NULL, ''),
  'biz_contest_contest',
  '竞赛',
  'MENU',
  NULLIF(NULL, ''),
  '/biz/contest/contest',
  '/biz/contest/contest/index.vue',
  'icon-park-outline:code',
  20,
  true,
  false,
  false,
  'ENABLED',
  NULL,
  '{}'
)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name, path = EXCLUDED.path, component = EXCLUDED.component, updated_at = now();

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, sort, is_visible, is_cache, is_affix, status, extra)
VALUES (
  '7487852161095831553',
  '7487852161095831552',
  'biz_contest_contest_page',
  '分页竞赛',
  'BUTTON',
  NULLIF(NULL, ''),
  10,
  false,
  false,
  false,
  'ENABLED',
  '{}'
)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, updated_at = now();

INSERT INTO sys_iam_relation (id, subject_type, subject_id, relation_type, target_type, target_id, target_key, grant_mode, effect, data_scope, custom_scope_dept_ids, is_primary, sort, status, description, extra)
VALUES (
  '7487852161095831554',
  'RESOURCE',
  '7487852161095831553',
  'RESOURCE_PERMISSION',
  'PERMISSION',
  '',
  'biz:contest:contest:page',
  'CASCADE',
  'ALLOW',
  'ALL',
  '[]',
  false,
  10,
  'ENABLED',
  '分页竞赛',
  '{}'
)
ON CONFLICT (id)
DO UPDATE SET description = EXCLUDED.description, updated_at = now();

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, sort, is_visible, is_cache, is_affix, status, extra)
VALUES (
  '7487852161095831555',
  '7487852161095831552',
  'biz_contest_contest_create',
  '新增竞赛',
  'BUTTON',
  NULLIF(NULL, ''),
  20,
  false,
  false,
  false,
  'ENABLED',
  '{}'
)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, updated_at = now();

INSERT INTO sys_iam_relation (id, subject_type, subject_id, relation_type, target_type, target_id, target_key, grant_mode, effect, data_scope, custom_scope_dept_ids, is_primary, sort, status, description, extra)
VALUES (
  '7487852161095831556',
  'RESOURCE',
  '7487852161095831555',
  'RESOURCE_PERMISSION',
  'PERMISSION',
  '',
  'biz:contest:contest:create',
  'CASCADE',
  'ALLOW',
  'ALL',
  '[]',
  false,
  20,
  'ENABLED',
  '新增竞赛',
  '{}'
)
ON CONFLICT (id)
DO UPDATE SET description = EXCLUDED.description, updated_at = now();

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, sort, is_visible, is_cache, is_affix, status, extra)
VALUES (
  '7487852161095831557',
  '7487852161095831552',
  'biz_contest_contest_detail',
  '详情竞赛',
  'BUTTON',
  NULLIF(NULL, ''),
  30,
  false,
  false,
  false,
  'ENABLED',
  '{}'
)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, updated_at = now();

INSERT INTO sys_iam_relation (id, subject_type, subject_id, relation_type, target_type, target_id, target_key, grant_mode, effect, data_scope, custom_scope_dept_ids, is_primary, sort, status, description, extra)
VALUES (
  '7487852161095831558',
  'RESOURCE',
  '7487852161095831557',
  'RESOURCE_PERMISSION',
  'PERMISSION',
  '',
  'biz:contest:contest:detail',
  'CASCADE',
  'ALLOW',
  'ALL',
  '[]',
  false,
  30,
  'ENABLED',
  '详情竞赛',
  '{}'
)
ON CONFLICT (id)
DO UPDATE SET description = EXCLUDED.description, updated_at = now();

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, sort, is_visible, is_cache, is_affix, status, extra)
VALUES (
  '7487852161095831559',
  '7487852161095831552',
  'biz_contest_contest_update',
  '编辑竞赛',
  'BUTTON',
  NULLIF(NULL, ''),
  40,
  false,
  false,
  false,
  'ENABLED',
  '{}'
)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, updated_at = now();

INSERT INTO sys_iam_relation (id, subject_type, subject_id, relation_type, target_type, target_id, target_key, grant_mode, effect, data_scope, custom_scope_dept_ids, is_primary, sort, status, description, extra)
VALUES (
  '7487852161095831560',
  'RESOURCE',
  '7487852161095831559',
  'RESOURCE_PERMISSION',
  'PERMISSION',
  '',
  'biz:contest:contest:update',
  'CASCADE',
  'ALLOW',
  'ALL',
  '[]',
  false,
  40,
  'ENABLED',
  '编辑竞赛',
  '{}'
)
ON CONFLICT (id)
DO UPDATE SET description = EXCLUDED.description, updated_at = now();

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, sort, is_visible, is_cache, is_affix, status, extra)
VALUES (
  '7487852161095831561',
  '7487852161095831552',
  'biz_contest_contest_delete',
  '删除竞赛',
  'BUTTON',
  NULLIF(NULL, ''),
  50,
  false,
  false,
  false,
  'ENABLED',
  '{}'
)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, updated_at = now();

INSERT INTO sys_iam_relation (id, subject_type, subject_id, relation_type, target_type, target_id, target_key, grant_mode, effect, data_scope, custom_scope_dept_ids, is_primary, sort, status, description, extra)
VALUES (
  '7487852161095831562',
  'RESOURCE',
  '7487852161095831561',
  'RESOURCE_PERMISSION',
  'PERMISSION',
  '',
  'biz:contest:contest:delete',
  'CASCADE',
  'ALLOW',
  'ALL',
  '[]',
  false,
  50,
  'ENABLED',
  '删除竞赛',
  '{}'
)
ON CONFLICT (id)
DO UPDATE SET description = EXCLUDED.description, updated_at = now();

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, sort, is_visible, is_cache, is_affix, status, extra)
VALUES (
  '7487852161095831563',
  '7487852161095831552',
  'biz_contest_contest_tables',
  '读取数据表竞赛',
  'BUTTON',
  NULLIF(NULL, ''),
  60,
  false,
  false,
  false,
  'ENABLED',
  '{}'
)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, updated_at = now();

INSERT INTO sys_iam_relation (id, subject_type, subject_id, relation_type, target_type, target_id, target_key, grant_mode, effect, data_scope, custom_scope_dept_ids, is_primary, sort, status, description, extra)
VALUES (
  '7487852161095831564',
  'RESOURCE',
  '7487852161095831563',
  'RESOURCE_PERMISSION',
  'PERMISSION',
  '',
  'biz:contest:contest:tables',
  'CASCADE',
  'ALLOW',
  'ALL',
  '[]',
  false,
  60,
  'ENABLED',
  '读取数据表竞赛',
  '{}'
)
ON CONFLICT (id)
DO UPDATE SET description = EXCLUDED.description, updated_at = now();

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, sort, is_visible, is_cache, is_affix, status, extra)
VALUES (
  '7487852161095831565',
  '7487852161095831552',
  'biz_contest_contest_preview',
  '预览竞赛',
  'BUTTON',
  NULLIF(NULL, ''),
  70,
  false,
  false,
  false,
  'ENABLED',
  '{}'
)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, updated_at = now();

INSERT INTO sys_iam_relation (id, subject_type, subject_id, relation_type, target_type, target_id, target_key, grant_mode, effect, data_scope, custom_scope_dept_ids, is_primary, sort, status, description, extra)
VALUES (
  '7487852161095831566',
  'RESOURCE',
  '7487852161095831565',
  'RESOURCE_PERMISSION',
  'PERMISSION',
  '',
  'biz:contest:contest:preview',
  'CASCADE',
  'ALLOW',
  'ALL',
  '[]',
  false,
  70,
  'ENABLED',
  '预览竞赛',
  '{}'
)
ON CONFLICT (id)
DO UPDATE SET description = EXCLUDED.description, updated_at = now();

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, sort, is_visible, is_cache, is_affix, status, extra)
VALUES (
  '7487852161095831567',
  '7487852161095831552',
  'biz_contest_contest_download',
  '下载竞赛',
  'BUTTON',
  NULLIF(NULL, ''),
  80,
  false,
  false,
  false,
  'ENABLED',
  '{}'
)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, updated_at = now();

INSERT INTO sys_iam_relation (id, subject_type, subject_id, relation_type, target_type, target_id, target_key, grant_mode, effect, data_scope, custom_scope_dept_ids, is_primary, sort, status, description, extra)
VALUES (
  '7487852161095831568',
  'RESOURCE',
  '7487852161095831567',
  'RESOURCE_PERMISSION',
  'PERMISSION',
  '',
  'biz:contest:contest:download',
  'CASCADE',
  'ALLOW',
  'ALL',
  '[]',
  false,
  80,
  'ENABLED',
  '下载竞赛',
  '{}'
)
ON CONFLICT (id)
DO UPDATE SET description = EXCLUDED.description, updated_at = now();

COMMIT;
