-- Generated by HEI code generator.
-- Author: Charlie
-- Generated at: 2026-07-28 20:51:11
-- Adjust module_id/parent_id before executing when needed.
BEGIN;

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, path, component, icon, sort, is_visible, is_cache, is_affix, status, description, extra)
VALUES (
  '7487852155148308480',
  NULLIF(NULL, ''),
  'biz_problem_languagelimit',
  '题目语言限制',
  'MENU',
  NULLIF(NULL, ''),
  '/biz/problem/language-limit',
  '/biz/problem/language-limit/index.vue',
  'icon-park-outline:code',
  70,
  true,
  false,
  false,
  'ENABLED',
  NULL,
  '{}'
)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name, path = EXCLUDED.path, component = EXCLUDED.component, updated_at = now();

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, sort, is_visible, is_cache, is_affix, status, extra)
VALUES (
  '7487852155148308481',
  '7487852155148308480',
  'biz_problem_languagelimit_page',
  '分页题目语言限制',
  'BUTTON',
  NULLIF(NULL, ''),
  10,
  false,
  false,
  false,
  'ENABLED',
  '{}'
)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, updated_at = now();

INSERT INTO sys_iam_relation (id, subject_type, subject_id, relation_type, target_type, target_id, target_key, grant_mode, effect, data_scope, custom_scope_dept_ids, is_primary, sort, status, description, extra)
VALUES (
  '7487852155148308482',
  'RESOURCE',
  '7487852155148308481',
  'RESOURCE_PERMISSION',
  'PERMISSION',
  '',
  'biz:problem:languagelimit:page',
  'CASCADE',
  'ALLOW',
  'ALL',
  '[]',
  false,
  10,
  'ENABLED',
  '分页题目语言限制',
  '{}'
)
ON CONFLICT (id)
DO UPDATE SET description = EXCLUDED.description, updated_at = now();

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, sort, is_visible, is_cache, is_affix, status, extra)
VALUES (
  '7487852155148308483',
  '7487852155148308480',
  'biz_problem_languagelimit_create',
  '新增题目语言限制',
  'BUTTON',
  NULLIF(NULL, ''),
  20,
  false,
  false,
  false,
  'ENABLED',
  '{}'
)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, updated_at = now();

INSERT INTO sys_iam_relation (id, subject_type, subject_id, relation_type, target_type, target_id, target_key, grant_mode, effect, data_scope, custom_scope_dept_ids, is_primary, sort, status, description, extra)
VALUES (
  '7487852155148308484',
  'RESOURCE',
  '7487852155148308483',
  'RESOURCE_PERMISSION',
  'PERMISSION',
  '',
  'biz:problem:languagelimit:create',
  'CASCADE',
  'ALLOW',
  'ALL',
  '[]',
  false,
  20,
  'ENABLED',
  '新增题目语言限制',
  '{}'
)
ON CONFLICT (id)
DO UPDATE SET description = EXCLUDED.description, updated_at = now();

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, sort, is_visible, is_cache, is_affix, status, extra)
VALUES (
  '7487852155148308485',
  '7487852155148308480',
  'biz_problem_languagelimit_detail',
  '详情题目语言限制',
  'BUTTON',
  NULLIF(NULL, ''),
  30,
  false,
  false,
  false,
  'ENABLED',
  '{}'
)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, updated_at = now();

INSERT INTO sys_iam_relation (id, subject_type, subject_id, relation_type, target_type, target_id, target_key, grant_mode, effect, data_scope, custom_scope_dept_ids, is_primary, sort, status, description, extra)
VALUES (
  '7487852155148308486',
  'RESOURCE',
  '7487852155148308485',
  'RESOURCE_PERMISSION',
  'PERMISSION',
  '',
  'biz:problem:languagelimit:detail',
  'CASCADE',
  'ALLOW',
  'ALL',
  '[]',
  false,
  30,
  'ENABLED',
  '详情题目语言限制',
  '{}'
)
ON CONFLICT (id)
DO UPDATE SET description = EXCLUDED.description, updated_at = now();

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, sort, is_visible, is_cache, is_affix, status, extra)
VALUES (
  '7487852155148308487',
  '7487852155148308480',
  'biz_problem_languagelimit_update',
  '编辑题目语言限制',
  'BUTTON',
  NULLIF(NULL, ''),
  40,
  false,
  false,
  false,
  'ENABLED',
  '{}'
)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, updated_at = now();

INSERT INTO sys_iam_relation (id, subject_type, subject_id, relation_type, target_type, target_id, target_key, grant_mode, effect, data_scope, custom_scope_dept_ids, is_primary, sort, status, description, extra)
VALUES (
  '7487852155148308488',
  'RESOURCE',
  '7487852155148308487',
  'RESOURCE_PERMISSION',
  'PERMISSION',
  '',
  'biz:problem:languagelimit:update',
  'CASCADE',
  'ALLOW',
  'ALL',
  '[]',
  false,
  40,
  'ENABLED',
  '编辑题目语言限制',
  '{}'
)
ON CONFLICT (id)
DO UPDATE SET description = EXCLUDED.description, updated_at = now();

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, sort, is_visible, is_cache, is_affix, status, extra)
VALUES (
  '7487852155148308489',
  '7487852155148308480',
  'biz_problem_languagelimit_delete',
  '删除题目语言限制',
  'BUTTON',
  NULLIF(NULL, ''),
  50,
  false,
  false,
  false,
  'ENABLED',
  '{}'
)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, updated_at = now();

INSERT INTO sys_iam_relation (id, subject_type, subject_id, relation_type, target_type, target_id, target_key, grant_mode, effect, data_scope, custom_scope_dept_ids, is_primary, sort, status, description, extra)
VALUES (
  '7487852155148308490',
  'RESOURCE',
  '7487852155148308489',
  'RESOURCE_PERMISSION',
  'PERMISSION',
  '',
  'biz:problem:languagelimit:delete',
  'CASCADE',
  'ALLOW',
  'ALL',
  '[]',
  false,
  50,
  'ENABLED',
  '删除题目语言限制',
  '{}'
)
ON CONFLICT (id)
DO UPDATE SET description = EXCLUDED.description, updated_at = now();

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, sort, is_visible, is_cache, is_affix, status, extra)
VALUES (
  '7487852155148308491',
  '7487852155148308480',
  'biz_problem_languagelimit_tables',
  '读取数据表题目语言限制',
  'BUTTON',
  NULLIF(NULL, ''),
  60,
  false,
  false,
  false,
  'ENABLED',
  '{}'
)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, updated_at = now();

INSERT INTO sys_iam_relation (id, subject_type, subject_id, relation_type, target_type, target_id, target_key, grant_mode, effect, data_scope, custom_scope_dept_ids, is_primary, sort, status, description, extra)
VALUES (
  '7487852155148308492',
  'RESOURCE',
  '7487852155148308491',
  'RESOURCE_PERMISSION',
  'PERMISSION',
  '',
  'biz:problem:languagelimit:tables',
  'CASCADE',
  'ALLOW',
  'ALL',
  '[]',
  false,
  60,
  'ENABLED',
  '读取数据表题目语言限制',
  '{}'
)
ON CONFLICT (id)
DO UPDATE SET description = EXCLUDED.description, updated_at = now();

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, sort, is_visible, is_cache, is_affix, status, extra)
VALUES (
  '7487852155148308493',
  '7487852155148308480',
  'biz_problem_languagelimit_preview',
  '预览题目语言限制',
  'BUTTON',
  NULLIF(NULL, ''),
  70,
  false,
  false,
  false,
  'ENABLED',
  '{}'
)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, updated_at = now();

INSERT INTO sys_iam_relation (id, subject_type, subject_id, relation_type, target_type, target_id, target_key, grant_mode, effect, data_scope, custom_scope_dept_ids, is_primary, sort, status, description, extra)
VALUES (
  '7487852155148308494',
  'RESOURCE',
  '7487852155148308493',
  'RESOURCE_PERMISSION',
  'PERMISSION',
  '',
  'biz:problem:languagelimit:preview',
  'CASCADE',
  'ALLOW',
  'ALL',
  '[]',
  false,
  70,
  'ENABLED',
  '预览题目语言限制',
  '{}'
)
ON CONFLICT (id)
DO UPDATE SET description = EXCLUDED.description, updated_at = now();

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, sort, is_visible, is_cache, is_affix, status, extra)
VALUES (
  '7487852155148308495',
  '7487852155148308480',
  'biz_problem_languagelimit_download',
  '下载题目语言限制',
  'BUTTON',
  NULLIF(NULL, ''),
  80,
  false,
  false,
  false,
  'ENABLED',
  '{}'
)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, updated_at = now();

INSERT INTO sys_iam_relation (id, subject_type, subject_id, relation_type, target_type, target_id, target_key, grant_mode, effect, data_scope, custom_scope_dept_ids, is_primary, sort, status, description, extra)
VALUES (
  '7487852155148308496',
  'RESOURCE',
  '7487852155148308495',
  'RESOURCE_PERMISSION',
  'PERMISSION',
  '',
  'biz:problem:languagelimit:download',
  'CASCADE',
  'ALLOW',
  'ALL',
  '[]',
  false,
  80,
  'ENABLED',
  '下载题目语言限制',
  '{}'
)
ON CONFLICT (id)
DO UPDATE SET description = EXCLUDED.description, updated_at = now();

COMMIT;
