-- Generated by HEI code generator.
-- Author: Charlie
-- Generated at: 2026-07-28 20:51:09
-- Adjust module_id/parent_id before executing when needed.
BEGIN;

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, path, component, icon, sort, is_visible, is_cache, is_affix, status, description, extra)
VALUES (
  '7487852149339197440',
  NULLIF(NULL, ''),
  'biz_problem_type',
  '题目类型',
  'MENU',
  NULLIF(NULL, ''),
  '/biz/problem/type',
  '/biz/problem/type/index.vue',
  'icon-park-outline:code',
  10,
  true,
  false,
  false,
  'ENABLED',
  NULL,
  '{}'
)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name, path = EXCLUDED.path, component = EXCLUDED.component, updated_at = now();

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, sort, is_visible, is_cache, is_affix, status, extra)
VALUES (
  '7487852149339197441',
  '7487852149339197440',
  'biz_problem_type_page',
  '分页题目类型',
  'BUTTON',
  NULLIF(NULL, ''),
  10,
  false,
  false,
  false,
  'ENABLED',
  '{}'
)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, updated_at = now();

INSERT INTO sys_iam_relation (id, subject_type, subject_id, relation_type, target_type, target_id, target_key, grant_mode, effect, data_scope, custom_scope_dept_ids, is_primary, sort, status, description, extra)
VALUES (
  '7487852149339197442',
  'RESOURCE',
  '7487852149339197441',
  'RESOURCE_PERMISSION',
  'PERMISSION',
  '',
  'biz:problem:type:page',
  'CASCADE',
  'ALLOW',
  'ALL',
  '[]',
  false,
  10,
  'ENABLED',
  '分页题目类型',
  '{}'
)
ON CONFLICT (id)
DO UPDATE SET description = EXCLUDED.description, updated_at = now();

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, sort, is_visible, is_cache, is_affix, status, extra)
VALUES (
  '7487852149339197443',
  '7487852149339197440',
  'biz_problem_type_create',
  '新增题目类型',
  'BUTTON',
  NULLIF(NULL, ''),
  20,
  false,
  false,
  false,
  'ENABLED',
  '{}'
)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, updated_at = now();

INSERT INTO sys_iam_relation (id, subject_type, subject_id, relation_type, target_type, target_id, target_key, grant_mode, effect, data_scope, custom_scope_dept_ids, is_primary, sort, status, description, extra)
VALUES (
  '7487852149339197444',
  'RESOURCE',
  '7487852149339197443',
  'RESOURCE_PERMISSION',
  'PERMISSION',
  '',
  'biz:problem:type:create',
  'CASCADE',
  'ALLOW',
  'ALL',
  '[]',
  false,
  20,
  'ENABLED',
  '新增题目类型',
  '{}'
)
ON CONFLICT (id)
DO UPDATE SET description = EXCLUDED.description, updated_at = now();

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, sort, is_visible, is_cache, is_affix, status, extra)
VALUES (
  '7487852149339197445',
  '7487852149339197440',
  'biz_problem_type_detail',
  '详情题目类型',
  'BUTTON',
  NULLIF(NULL, ''),
  30,
  false,
  false,
  false,
  'ENABLED',
  '{}'
)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, updated_at = now();

INSERT INTO sys_iam_relation (id, subject_type, subject_id, relation_type, target_type, target_id, target_key, grant_mode, effect, data_scope, custom_scope_dept_ids, is_primary, sort, status, description, extra)
VALUES (
  '7487852149339197446',
  'RESOURCE',
  '7487852149339197445',
  'RESOURCE_PERMISSION',
  'PERMISSION',
  '',
  'biz:problem:type:detail',
  'CASCADE',
  'ALLOW',
  'ALL',
  '[]',
  false,
  30,
  'ENABLED',
  '详情题目类型',
  '{}'
)
ON CONFLICT (id)
DO UPDATE SET description = EXCLUDED.description, updated_at = now();

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, sort, is_visible, is_cache, is_affix, status, extra)
VALUES (
  '7487852149339197447',
  '7487852149339197440',
  'biz_problem_type_update',
  '编辑题目类型',
  'BUTTON',
  NULLIF(NULL, ''),
  40,
  false,
  false,
  false,
  'ENABLED',
  '{}'
)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, updated_at = now();

INSERT INTO sys_iam_relation (id, subject_type, subject_id, relation_type, target_type, target_id, target_key, grant_mode, effect, data_scope, custom_scope_dept_ids, is_primary, sort, status, description, extra)
VALUES (
  '7487852149339197448',
  'RESOURCE',
  '7487852149339197447',
  'RESOURCE_PERMISSION',
  'PERMISSION',
  '',
  'biz:problem:type:update',
  'CASCADE',
  'ALLOW',
  'ALL',
  '[]',
  false,
  40,
  'ENABLED',
  '编辑题目类型',
  '{}'
)
ON CONFLICT (id)
DO UPDATE SET description = EXCLUDED.description, updated_at = now();

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, sort, is_visible, is_cache, is_affix, status, extra)
VALUES (
  '7487852149339197449',
  '7487852149339197440',
  'biz_problem_type_delete',
  '删除题目类型',
  'BUTTON',
  NULLIF(NULL, ''),
  50,
  false,
  false,
  false,
  'ENABLED',
  '{}'
)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, updated_at = now();

INSERT INTO sys_iam_relation (id, subject_type, subject_id, relation_type, target_type, target_id, target_key, grant_mode, effect, data_scope, custom_scope_dept_ids, is_primary, sort, status, description, extra)
VALUES (
  '7487852149339197450',
  'RESOURCE',
  '7487852149339197449',
  'RESOURCE_PERMISSION',
  'PERMISSION',
  '',
  'biz:problem:type:delete',
  'CASCADE',
  'ALLOW',
  'ALL',
  '[]',
  false,
  50,
  'ENABLED',
  '删除题目类型',
  '{}'
)
ON CONFLICT (id)
DO UPDATE SET description = EXCLUDED.description, updated_at = now();

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, sort, is_visible, is_cache, is_affix, status, extra)
VALUES (
  '7487852149339197451',
  '7487852149339197440',
  'biz_problem_type_tables',
  '读取数据表题目类型',
  'BUTTON',
  NULLIF(NULL, ''),
  60,
  false,
  false,
  false,
  'ENABLED',
  '{}'
)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, updated_at = now();

INSERT INTO sys_iam_relation (id, subject_type, subject_id, relation_type, target_type, target_id, target_key, grant_mode, effect, data_scope, custom_scope_dept_ids, is_primary, sort, status, description, extra)
VALUES (
  '7487852149339197452',
  'RESOURCE',
  '7487852149339197451',
  'RESOURCE_PERMISSION',
  'PERMISSION',
  '',
  'biz:problem:type:tables',
  'CASCADE',
  'ALLOW',
  'ALL',
  '[]',
  false,
  60,
  'ENABLED',
  '读取数据表题目类型',
  '{}'
)
ON CONFLICT (id)
DO UPDATE SET description = EXCLUDED.description, updated_at = now();

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, sort, is_visible, is_cache, is_affix, status, extra)
VALUES (
  '7487852149339197453',
  '7487852149339197440',
  'biz_problem_type_preview',
  '预览题目类型',
  'BUTTON',
  NULLIF(NULL, ''),
  70,
  false,
  false,
  false,
  'ENABLED',
  '{}'
)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, updated_at = now();

INSERT INTO sys_iam_relation (id, subject_type, subject_id, relation_type, target_type, target_id, target_key, grant_mode, effect, data_scope, custom_scope_dept_ids, is_primary, sort, status, description, extra)
VALUES (
  '7487852149339197454',
  'RESOURCE',
  '7487852149339197453',
  'RESOURCE_PERMISSION',
  'PERMISSION',
  '',
  'biz:problem:type:preview',
  'CASCADE',
  'ALLOW',
  'ALL',
  '[]',
  false,
  70,
  'ENABLED',
  '预览题目类型',
  '{}'
)
ON CONFLICT (id)
DO UPDATE SET description = EXCLUDED.description, updated_at = now();

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, sort, is_visible, is_cache, is_affix, status, extra)
VALUES (
  '7487852149339197455',
  '7487852149339197440',
  'biz_problem_type_download',
  '下载题目类型',
  'BUTTON',
  NULLIF(NULL, ''),
  80,
  false,
  false,
  false,
  'ENABLED',
  '{}'
)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, updated_at = now();

INSERT INTO sys_iam_relation (id, subject_type, subject_id, relation_type, target_type, target_id, target_key, grant_mode, effect, data_scope, custom_scope_dept_ids, is_primary, sort, status, description, extra)
VALUES (
  '7487852149339197456',
  'RESOURCE',
  '7487852149339197455',
  'RESOURCE_PERMISSION',
  'PERMISSION',
  '',
  'biz:problem:type:download',
  'CASCADE',
  'ALLOW',
  'ALL',
  '[]',
  false,
  80,
  'ENABLED',
  '下载题目类型',
  '{}'
)
ON CONFLICT (id)
DO UPDATE SET description = EXCLUDED.description, updated_at = now();

COMMIT;
