-- Generated by HEI code generator.
-- Author: Charlie
-- Generated at: 2026-07-28 20:51:10
-- Adjust module_id/parent_id before executing when needed.
BEGIN;

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, path, component, icon, sort, is_visible, is_cache, is_affix, status, description, extra)
VALUES (
  '7487852152870801408',
  NULLIF(NULL, ''),
  'biz_problem_staff',
  '题目人员',
  'MENU',
  NULLIF(NULL, ''),
  '/biz/problem/staff',
  '/biz/problem/staff/index.vue',
  'icon-park-outline:code',
  50,
  true,
  false,
  false,
  'ENABLED',
  NULL,
  '{}'
)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name, path = EXCLUDED.path, component = EXCLUDED.component, updated_at = now();

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, sort, is_visible, is_cache, is_affix, status, extra)
VALUES (
  '7487852152870801409',
  '7487852152870801408',
  'biz_problem_staff_page',
  '分页题目人员',
  'BUTTON',
  NULLIF(NULL, ''),
  10,
  false,
  false,
  false,
  'ENABLED',
  '{}'
)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, updated_at = now();

INSERT INTO sys_iam_relation (id, subject_type, subject_id, relation_type, target_type, target_id, target_key, grant_mode, effect, data_scope, custom_scope_dept_ids, is_primary, sort, status, description, extra)
VALUES (
  '7487852152870801410',
  'RESOURCE',
  '7487852152870801409',
  'RESOURCE_PERMISSION',
  'PERMISSION',
  '',
  'biz:problem:staff:page',
  'CASCADE',
  'ALLOW',
  'ALL',
  '[]',
  false,
  10,
  'ENABLED',
  '分页题目人员',
  '{}'
)
ON CONFLICT (id)
DO UPDATE SET description = EXCLUDED.description, updated_at = now();

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, sort, is_visible, is_cache, is_affix, status, extra)
VALUES (
  '7487852152870801411',
  '7487852152870801408',
  'biz_problem_staff_create',
  '新增题目人员',
  'BUTTON',
  NULLIF(NULL, ''),
  20,
  false,
  false,
  false,
  'ENABLED',
  '{}'
)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, updated_at = now();

INSERT INTO sys_iam_relation (id, subject_type, subject_id, relation_type, target_type, target_id, target_key, grant_mode, effect, data_scope, custom_scope_dept_ids, is_primary, sort, status, description, extra)
VALUES (
  '7487852152870801412',
  'RESOURCE',
  '7487852152870801411',
  'RESOURCE_PERMISSION',
  'PERMISSION',
  '',
  'biz:problem:staff:create',
  'CASCADE',
  'ALLOW',
  'ALL',
  '[]',
  false,
  20,
  'ENABLED',
  '新增题目人员',
  '{}'
)
ON CONFLICT (id)
DO UPDATE SET description = EXCLUDED.description, updated_at = now();

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, sort, is_visible, is_cache, is_affix, status, extra)
VALUES (
  '7487852152870801413',
  '7487852152870801408',
  'biz_problem_staff_detail',
  '详情题目人员',
  'BUTTON',
  NULLIF(NULL, ''),
  30,
  false,
  false,
  false,
  'ENABLED',
  '{}'
)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, updated_at = now();

INSERT INTO sys_iam_relation (id, subject_type, subject_id, relation_type, target_type, target_id, target_key, grant_mode, effect, data_scope, custom_scope_dept_ids, is_primary, sort, status, description, extra)
VALUES (
  '7487852152870801414',
  'RESOURCE',
  '7487852152870801413',
  'RESOURCE_PERMISSION',
  'PERMISSION',
  '',
  'biz:problem:staff:detail',
  'CASCADE',
  'ALLOW',
  'ALL',
  '[]',
  false,
  30,
  'ENABLED',
  '详情题目人员',
  '{}'
)
ON CONFLICT (id)
DO UPDATE SET description = EXCLUDED.description, updated_at = now();

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, sort, is_visible, is_cache, is_affix, status, extra)
VALUES (
  '7487852152870801415',
  '7487852152870801408',
  'biz_problem_staff_update',
  '编辑题目人员',
  'BUTTON',
  NULLIF(NULL, ''),
  40,
  false,
  false,
  false,
  'ENABLED',
  '{}'
)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, updated_at = now();

INSERT INTO sys_iam_relation (id, subject_type, subject_id, relation_type, target_type, target_id, target_key, grant_mode, effect, data_scope, custom_scope_dept_ids, is_primary, sort, status, description, extra)
VALUES (
  '7487852152870801416',
  'RESOURCE',
  '7487852152870801415',
  'RESOURCE_PERMISSION',
  'PERMISSION',
  '',
  'biz:problem:staff:update',
  'CASCADE',
  'ALLOW',
  'ALL',
  '[]',
  false,
  40,
  'ENABLED',
  '编辑题目人员',
  '{}'
)
ON CONFLICT (id)
DO UPDATE SET description = EXCLUDED.description, updated_at = now();

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, sort, is_visible, is_cache, is_affix, status, extra)
VALUES (
  '7487852152870801417',
  '7487852152870801408',
  'biz_problem_staff_delete',
  '删除题目人员',
  'BUTTON',
  NULLIF(NULL, ''),
  50,
  false,
  false,
  false,
  'ENABLED',
  '{}'
)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, updated_at = now();

INSERT INTO sys_iam_relation (id, subject_type, subject_id, relation_type, target_type, target_id, target_key, grant_mode, effect, data_scope, custom_scope_dept_ids, is_primary, sort, status, description, extra)
VALUES (
  '7487852152870801418',
  'RESOURCE',
  '7487852152870801417',
  'RESOURCE_PERMISSION',
  'PERMISSION',
  '',
  'biz:problem:staff:delete',
  'CASCADE',
  'ALLOW',
  'ALL',
  '[]',
  false,
  50,
  'ENABLED',
  '删除题目人员',
  '{}'
)
ON CONFLICT (id)
DO UPDATE SET description = EXCLUDED.description, updated_at = now();

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, sort, is_visible, is_cache, is_affix, status, extra)
VALUES (
  '7487852152870801419',
  '7487852152870801408',
  'biz_problem_staff_tables',
  '读取数据表题目人员',
  'BUTTON',
  NULLIF(NULL, ''),
  60,
  false,
  false,
  false,
  'ENABLED',
  '{}'
)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, updated_at = now();

INSERT INTO sys_iam_relation (id, subject_type, subject_id, relation_type, target_type, target_id, target_key, grant_mode, effect, data_scope, custom_scope_dept_ids, is_primary, sort, status, description, extra)
VALUES (
  '7487852152870801420',
  'RESOURCE',
  '7487852152870801419',
  'RESOURCE_PERMISSION',
  'PERMISSION',
  '',
  'biz:problem:staff:tables',
  'CASCADE',
  'ALLOW',
  'ALL',
  '[]',
  false,
  60,
  'ENABLED',
  '读取数据表题目人员',
  '{}'
)
ON CONFLICT (id)
DO UPDATE SET description = EXCLUDED.description, updated_at = now();

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, sort, is_visible, is_cache, is_affix, status, extra)
VALUES (
  '7487852152870801421',
  '7487852152870801408',
  'biz_problem_staff_preview',
  '预览题目人员',
  'BUTTON',
  NULLIF(NULL, ''),
  70,
  false,
  false,
  false,
  'ENABLED',
  '{}'
)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, updated_at = now();

INSERT INTO sys_iam_relation (id, subject_type, subject_id, relation_type, target_type, target_id, target_key, grant_mode, effect, data_scope, custom_scope_dept_ids, is_primary, sort, status, description, extra)
VALUES (
  '7487852152870801422',
  'RESOURCE',
  '7487852152870801421',
  'RESOURCE_PERMISSION',
  'PERMISSION',
  '',
  'biz:problem:staff:preview',
  'CASCADE',
  'ALLOW',
  'ALL',
  '[]',
  false,
  70,
  'ENABLED',
  '预览题目人员',
  '{}'
)
ON CONFLICT (id)
DO UPDATE SET description = EXCLUDED.description, updated_at = now();

INSERT INTO sys_resource (id, parent_id, code, name, resource_type, module_id, sort, is_visible, is_cache, is_affix, status, extra)
VALUES (
  '7487852152870801423',
  '7487852152870801408',
  'biz_problem_staff_download',
  '下载题目人员',
  'BUTTON',
  NULLIF(NULL, ''),
  80,
  false,
  false,
  false,
  'ENABLED',
  '{}'
)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, updated_at = now();

INSERT INTO sys_iam_relation (id, subject_type, subject_id, relation_type, target_type, target_id, target_key, grant_mode, effect, data_scope, custom_scope_dept_ids, is_primary, sort, status, description, extra)
VALUES (
  '7487852152870801424',
  'RESOURCE',
  '7487852152870801423',
  'RESOURCE_PERMISSION',
  'PERMISSION',
  '',
  'biz:problem:staff:download',
  'CASCADE',
  'ALLOW',
  'ALL',
  '[]',
  false,
  80,
  'ENABLED',
  '下载题目人员',
  '{}'
)
ON CONFLICT (id)
DO UPDATE SET description = EXCLUDED.description, updated_at = now();

COMMIT;
