SUPER_ADMIN_CODE = "SUPER_ADMIN"

STATUS_YES = "YES"
STATUS_NO = "NO"
STATUS_ENABLED = "ENABLED"
STATUS_DISABLED = "DISABLED"

USER_STATUS_ACTIVE = "ACTIVE"
USER_STATUS_INACTIVE = "INACTIVE"
USER_STATUS_LOCKED = "LOCKED"

RESOURCE_CATEGORY_BACKEND_MENU = "BACKEND_MENU"
RESOURCE_CATEGORY_FRONTEND_MENU = "FRONTEND_MENU"
RESOURCE_CATEGORY_BACKEND_BUTTON = "BACKEND_BUTTON"
RESOURCE_CATEGORY_FRONTEND_BUTTON = "FRONTEND_BUTTON"

RESOURCE_TYPE_DIRECTORY = "DIRECTORY"
RESOURCE_TYPE_MENU = "MENU"
RESOURCE_TYPE_BUTTON = "BUTTON"
RESOURCE_TYPE_INTERNAL_LINK = "INTERNAL_LINK"
RESOURCE_TYPE_EXTERNAL_LINK = "EXTERNAL_LINK"
