"""
Generated by HEI code generator.
Author: Charlie
Generated at: 2026-07-28 20:51:10
"""

from sqlalchemy.ext.asyncio import AsyncSession

from app.core.exceptions.business import NotFoundError
from app.modules.biz.oj_scope import delete_owned_by_parent, ensure_belongs_to_parent
from app.core.response.pagination import PageData, build_page
from app.core.schema.base import IdQuery, IdsRequest, to_schema, to_schema_list
from app.platform.db.transaction import transactional
from app.modules.biz.problem.staff.model import OjProblemStaff
from app.modules.biz.problem.staff.repository import (
    OjProblemStaffRepository,
)
from app.modules.biz.problem.staff.schema import (
    OjProblemStaffAdminPageQuery,
    OjProblemStaffCreateRequest,
    OjProblemStaffSchema,
    OjProblemStaffUpdateRequest,
)


class OjProblemStaffService:
    def __init__(self, db: AsyncSession):
        self.db = db
        self.repo = OjProblemStaffRepository(db)

    async def create(self, problem_id: str, payload: OjProblemStaffCreateRequest) -> None:
        async with transactional(self.db):
            await self.repo.create(payload.model_copy(update={"problem_id": problem_id}))

    async def update(self, problem_id: str, payload: OjProblemStaffUpdateRequest) -> None:
        async with transactional(self.db):
            entity = await self.repo.get_required(payload.id)
            ensure_belongs_to_parent(entity, parent_attr="problem_id", parent_id=problem_id, not_found_message="OjProblemStaff not found")
            await self.repo.update(payload.model_copy(update={"problem_id": problem_id}))

    async def delete(self, problem_id: str, payload: IdsRequest) -> None:
        async with transactional(self.db):
            await delete_owned_by_parent(
                self.db,
                model=OjProblemStaff,
                parent_attr="problem_id",
                parent_id=problem_id,
                entity_ids=payload.ids,
                not_found_message="OjProblemStaff not found",
            )

    async def detail(self, problem_id: str, query: IdQuery) -> OjProblemStaffSchema:
        entity = await self.repo.get_required(query.id)
        ensure_belongs_to_parent(entity, parent_attr="problem_id", parent_id=problem_id, not_found_message="OjProblemStaff not found")
        return to_schema(OjProblemStaffSchema, entity)

    async def page_admin(
        self, problem_id: str, query: OjProblemStaffAdminPageQuery
    ) -> PageData[OjProblemStaffSchema]:
        scoped_query = query.model_copy(update={"problem_id": problem_id})
        items, total = await self.repo.page_admin(scoped_query)
        return build_page(scoped_query.pagination, total, to_schema_list(OjProblemStaffSchema, items))
