/**
 * Generated by HEI code generator.
 * Author: Charlie
 * Generated at: 2026-07-28 20:51:12
 */
import { http } from '@/utils'

const prefix = '/api/v1/admin/biz/contest/contest'

export function page(params: any) {
  return http.get<any>(`${prefix}/page`, { params })
}

export function detail(params: any) {
  return http.get<any>(`${prefix}/detail`, { params })
}

export function create(data: any) {
  return http.post<any>(`${prefix}/create`, data)
}

export function update(data: any) {
  return http.post<any>(`${prefix}/update`, data)
}

export function remove(data: any) {
  return http.post<any>(`${prefix}/delete`, data)
}

export function lock(data: { contest_id: string }) {
  return http.post<any>(`${prefix}/lock`, data)
}

export function unlock(data: { contest_id: string }) {
  return http.post<any>(`${prefix}/unlock`, data)
}

export function clone(data: { contest_id: string, new_key?: string, copy_staff?: boolean }) {
  return http.post<any>(`${prefix}/clone`, data)
}

export function rescore(data: { contest_id: string }) {
  return http.post<any>(`${prefix}/rescore`, data)
}

export function rate(data: { contest_id: string }) {
  return http.post<any>(`${prefix}/rate`, data)
}

export function scoreboard(params: { contest_id: string, virtual?: number }) {
  return http.get<any>(`${prefix}/scoreboard`, { params })
}

export function submit(data: any) {
  return http.post<any>(`${prefix}/submit`, data)
}

export function formats() {
  return http.get<any>(`${prefix}/formats`)
}
