// Code generated by ent, DO NOT EDIT.

package relorgrole

import (
	"hei-gin/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldContainsFold(FieldID, id))
}

// OrgID applies equality check predicate on the "org_id" field. It's identical to OrgIDEQ.
func OrgID(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldEQ(FieldOrgID, v))
}

// RoleID applies equality check predicate on the "role_id" field. It's identical to RoleIDEQ.
func RoleID(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldEQ(FieldRoleID, v))
}

// Scope applies equality check predicate on the "scope" field. It's identical to ScopeEQ.
func Scope(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldEQ(FieldScope, v))
}

// CustomScopeGroupIds applies equality check predicate on the "custom_scope_group_ids" field. It's identical to CustomScopeGroupIdsEQ.
func CustomScopeGroupIds(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldEQ(FieldCustomScopeGroupIds, v))
}

// OrgIDEQ applies the EQ predicate on the "org_id" field.
func OrgIDEQ(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldEQ(FieldOrgID, v))
}

// OrgIDNEQ applies the NEQ predicate on the "org_id" field.
func OrgIDNEQ(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldNEQ(FieldOrgID, v))
}

// OrgIDIn applies the In predicate on the "org_id" field.
func OrgIDIn(vs ...string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldIn(FieldOrgID, vs...))
}

// OrgIDNotIn applies the NotIn predicate on the "org_id" field.
func OrgIDNotIn(vs ...string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldNotIn(FieldOrgID, vs...))
}

// OrgIDGT applies the GT predicate on the "org_id" field.
func OrgIDGT(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldGT(FieldOrgID, v))
}

// OrgIDGTE applies the GTE predicate on the "org_id" field.
func OrgIDGTE(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldGTE(FieldOrgID, v))
}

// OrgIDLT applies the LT predicate on the "org_id" field.
func OrgIDLT(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldLT(FieldOrgID, v))
}

// OrgIDLTE applies the LTE predicate on the "org_id" field.
func OrgIDLTE(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldLTE(FieldOrgID, v))
}

// OrgIDContains applies the Contains predicate on the "org_id" field.
func OrgIDContains(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldContains(FieldOrgID, v))
}

// OrgIDHasPrefix applies the HasPrefix predicate on the "org_id" field.
func OrgIDHasPrefix(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldHasPrefix(FieldOrgID, v))
}

// OrgIDHasSuffix applies the HasSuffix predicate on the "org_id" field.
func OrgIDHasSuffix(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldHasSuffix(FieldOrgID, v))
}

// OrgIDEqualFold applies the EqualFold predicate on the "org_id" field.
func OrgIDEqualFold(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldEqualFold(FieldOrgID, v))
}

// OrgIDContainsFold applies the ContainsFold predicate on the "org_id" field.
func OrgIDContainsFold(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldContainsFold(FieldOrgID, v))
}

// RoleIDEQ applies the EQ predicate on the "role_id" field.
func RoleIDEQ(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldEQ(FieldRoleID, v))
}

// RoleIDNEQ applies the NEQ predicate on the "role_id" field.
func RoleIDNEQ(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldNEQ(FieldRoleID, v))
}

// RoleIDIn applies the In predicate on the "role_id" field.
func RoleIDIn(vs ...string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldIn(FieldRoleID, vs...))
}

// RoleIDNotIn applies the NotIn predicate on the "role_id" field.
func RoleIDNotIn(vs ...string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldNotIn(FieldRoleID, vs...))
}

// RoleIDGT applies the GT predicate on the "role_id" field.
func RoleIDGT(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldGT(FieldRoleID, v))
}

// RoleIDGTE applies the GTE predicate on the "role_id" field.
func RoleIDGTE(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldGTE(FieldRoleID, v))
}

// RoleIDLT applies the LT predicate on the "role_id" field.
func RoleIDLT(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldLT(FieldRoleID, v))
}

// RoleIDLTE applies the LTE predicate on the "role_id" field.
func RoleIDLTE(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldLTE(FieldRoleID, v))
}

// RoleIDContains applies the Contains predicate on the "role_id" field.
func RoleIDContains(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldContains(FieldRoleID, v))
}

// RoleIDHasPrefix applies the HasPrefix predicate on the "role_id" field.
func RoleIDHasPrefix(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldHasPrefix(FieldRoleID, v))
}

// RoleIDHasSuffix applies the HasSuffix predicate on the "role_id" field.
func RoleIDHasSuffix(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldHasSuffix(FieldRoleID, v))
}

// RoleIDEqualFold applies the EqualFold predicate on the "role_id" field.
func RoleIDEqualFold(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldEqualFold(FieldRoleID, v))
}

// RoleIDContainsFold applies the ContainsFold predicate on the "role_id" field.
func RoleIDContainsFold(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldContainsFold(FieldRoleID, v))
}

// ScopeEQ applies the EQ predicate on the "scope" field.
func ScopeEQ(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldEQ(FieldScope, v))
}

// ScopeNEQ applies the NEQ predicate on the "scope" field.
func ScopeNEQ(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldNEQ(FieldScope, v))
}

// ScopeIn applies the In predicate on the "scope" field.
func ScopeIn(vs ...string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldIn(FieldScope, vs...))
}

// ScopeNotIn applies the NotIn predicate on the "scope" field.
func ScopeNotIn(vs ...string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldNotIn(FieldScope, vs...))
}

// ScopeGT applies the GT predicate on the "scope" field.
func ScopeGT(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldGT(FieldScope, v))
}

// ScopeGTE applies the GTE predicate on the "scope" field.
func ScopeGTE(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldGTE(FieldScope, v))
}

// ScopeLT applies the LT predicate on the "scope" field.
func ScopeLT(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldLT(FieldScope, v))
}

// ScopeLTE applies the LTE predicate on the "scope" field.
func ScopeLTE(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldLTE(FieldScope, v))
}

// ScopeContains applies the Contains predicate on the "scope" field.
func ScopeContains(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldContains(FieldScope, v))
}

// ScopeHasPrefix applies the HasPrefix predicate on the "scope" field.
func ScopeHasPrefix(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldHasPrefix(FieldScope, v))
}

// ScopeHasSuffix applies the HasSuffix predicate on the "scope" field.
func ScopeHasSuffix(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldHasSuffix(FieldScope, v))
}

// ScopeIsNil applies the IsNil predicate on the "scope" field.
func ScopeIsNil() predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldIsNull(FieldScope))
}

// ScopeNotNil applies the NotNil predicate on the "scope" field.
func ScopeNotNil() predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldNotNull(FieldScope))
}

// ScopeEqualFold applies the EqualFold predicate on the "scope" field.
func ScopeEqualFold(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldEqualFold(FieldScope, v))
}

// ScopeContainsFold applies the ContainsFold predicate on the "scope" field.
func ScopeContainsFold(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldContainsFold(FieldScope, v))
}

// CustomScopeGroupIdsEQ applies the EQ predicate on the "custom_scope_group_ids" field.
func CustomScopeGroupIdsEQ(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldEQ(FieldCustomScopeGroupIds, v))
}

// CustomScopeGroupIdsNEQ applies the NEQ predicate on the "custom_scope_group_ids" field.
func CustomScopeGroupIdsNEQ(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldNEQ(FieldCustomScopeGroupIds, v))
}

// CustomScopeGroupIdsIn applies the In predicate on the "custom_scope_group_ids" field.
func CustomScopeGroupIdsIn(vs ...string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldIn(FieldCustomScopeGroupIds, vs...))
}

// CustomScopeGroupIdsNotIn applies the NotIn predicate on the "custom_scope_group_ids" field.
func CustomScopeGroupIdsNotIn(vs ...string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldNotIn(FieldCustomScopeGroupIds, vs...))
}

// CustomScopeGroupIdsGT applies the GT predicate on the "custom_scope_group_ids" field.
func CustomScopeGroupIdsGT(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldGT(FieldCustomScopeGroupIds, v))
}

// CustomScopeGroupIdsGTE applies the GTE predicate on the "custom_scope_group_ids" field.
func CustomScopeGroupIdsGTE(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldGTE(FieldCustomScopeGroupIds, v))
}

// CustomScopeGroupIdsLT applies the LT predicate on the "custom_scope_group_ids" field.
func CustomScopeGroupIdsLT(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldLT(FieldCustomScopeGroupIds, v))
}

// CustomScopeGroupIdsLTE applies the LTE predicate on the "custom_scope_group_ids" field.
func CustomScopeGroupIdsLTE(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldLTE(FieldCustomScopeGroupIds, v))
}

// CustomScopeGroupIdsContains applies the Contains predicate on the "custom_scope_group_ids" field.
func CustomScopeGroupIdsContains(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldContains(FieldCustomScopeGroupIds, v))
}

// CustomScopeGroupIdsHasPrefix applies the HasPrefix predicate on the "custom_scope_group_ids" field.
func CustomScopeGroupIdsHasPrefix(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldHasPrefix(FieldCustomScopeGroupIds, v))
}

// CustomScopeGroupIdsHasSuffix applies the HasSuffix predicate on the "custom_scope_group_ids" field.
func CustomScopeGroupIdsHasSuffix(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldHasSuffix(FieldCustomScopeGroupIds, v))
}

// CustomScopeGroupIdsIsNil applies the IsNil predicate on the "custom_scope_group_ids" field.
func CustomScopeGroupIdsIsNil() predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldIsNull(FieldCustomScopeGroupIds))
}

// CustomScopeGroupIdsNotNil applies the NotNil predicate on the "custom_scope_group_ids" field.
func CustomScopeGroupIdsNotNil() predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldNotNull(FieldCustomScopeGroupIds))
}

// CustomScopeGroupIdsEqualFold applies the EqualFold predicate on the "custom_scope_group_ids" field.
func CustomScopeGroupIdsEqualFold(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldEqualFold(FieldCustomScopeGroupIds, v))
}

// CustomScopeGroupIdsContainsFold applies the ContainsFold predicate on the "custom_scope_group_ids" field.
func CustomScopeGroupIdsContainsFold(v string) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.FieldContainsFold(FieldCustomScopeGroupIds, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RelOrgRole) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RelOrgRole) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RelOrgRole) predicate.RelOrgRole {
	return predicate.RelOrgRole(sql.NotPredicates(p))
}
