<!--
  Generated by HEI code generator.
  Author: Charlie
  Generated at: 2026-07-28 20:51:12
-->

<script setup lang="ts">
import type { FormInst, FormRules, SelectOption } from 'naive-ui'
import { ojContestApi, ojContestTagApi } from '@/api'
import { createRequiredRule, formatDateTime } from '@/utils'
import { computed, onMounted, reactive, ref } from 'vue'

const emit = defineEmits<{
  saved: []
}>()

const formRef = ref<FormInst | null>(null)
const tagOptions = ref<SelectOption[]>([])
const defaultFormData: Record<string, any> = {
  key: '',
  name: '',
  description: '',
  summary: '',
  start_time: null,
  end_time: null,
  time_limit_seconds: 0,
  is_visible: false,
  is_private: false,
  access_code: '',
  is_rated: false,
  rating_floor: 0,
  rating_ceiling: 0,
  rate_all: false,
  scoreboard_visibility: '',
  format_name: '',
  format_config: '{}',
  points_precision: 0,
  hide_problem_tags: false,
  hide_problem_authors: false,
  run_pretests_only: false,
  use_clarifications: false,
  tester_see_scoreboard: false,
  tester_see_submissions: false,
  show_short_display: false,
  problem_label_script: '',
  locked_after: null,
  og_image: '',
  logo_override_image: '',
  tag_ids: [],
  extra: '{}',
}
const state = reactive({
  showModal: false,
  loading: false,
  submitLoading: false,
  dataId: null as string | null,
  formModel: normalizeFormData(),
})

const modalTitle = computed(() => state.dataId ? '编辑竞赛' : '新增竞赛')
const rules = computed<FormRules>(() => ({
  key: [
    createRequiredRule('竞赛标识', 'input'),
  ],
  name: [
    createRequiredRule('竞赛名称', 'input'),
  ],
  description: [
    createRequiredRule('竞赛说明', 'input'),
  ],
  start_time: [
    createRequiredRule('开始时间', 'change'),
  ],
  end_time: [
    createRequiredRule('结束时间', 'change'),
  ],
  is_visible: [
    {
      validator: () => typeof state.formModel.is_visible === 'boolean',
      message: '请选择是否公开可见',
      trigger: 'change',
    },
  ],
  is_private: [
    {
      validator: () => typeof state.formModel.is_private === 'boolean',
      message: '请选择是否仅限指定选手',
      trigger: 'change',
    },
  ],
  is_rated: [
    {
      validator: () => typeof state.formModel.is_rated === 'boolean',
      message: '请选择是否计入 Rating',
      trigger: 'change',
    },
  ],
  rate_all: [
    {
      validator: () => typeof state.formModel.rate_all === 'boolean',
      message: '请选择无提交也计 Rating',
      trigger: 'change',
    },
  ],
  scoreboard_visibility: [
    createRequiredRule('榜单可见性', 'input'),
  ],
  format_name: [
    createRequiredRule('赛制', 'input'),
  ],
  format_config: [
    {
      validator: () => isValidJsonValue(state.formModel.format_config),
      message: '请输入合法 JSON 对象',
      trigger: ['input', 'blur'],
    },
  ],
  points_precision: [
    {
      validator: () => typeof state.formModel.points_precision === 'number' && Number.isFinite(state.formModel.points_precision),
      message: '请输入分数小数精度',
      trigger: ['input', 'blur'],
    },
  ],
  hide_problem_tags: [
    {
      validator: () => typeof state.formModel.hide_problem_tags === 'boolean',
      message: '请选择赛中隐藏题目标签',
      trigger: 'change',
    },
  ],
  hide_problem_authors: [
    {
      validator: () => typeof state.formModel.hide_problem_authors === 'boolean',
      message: '请选择赛中隐藏命题人',
      trigger: 'change',
    },
  ],
  run_pretests_only: [
    {
      validator: () => typeof state.formModel.run_pretests_only === 'boolean',
      message: '请选择赛中仅跑 pretest',
      trigger: 'change',
    },
  ],
  use_clarifications: [
    {
      validator: () => typeof state.formModel.use_clarifications === 'boolean',
      message: '请选择使用答疑',
      trigger: 'change',
    },
  ],
  tester_see_scoreboard: [
    {
      validator: () => typeof state.formModel.tester_see_scoreboard === 'boolean',
      message: '请选择测试员可见榜单',
      trigger: 'change',
    },
  ],
  tester_see_submissions: [
    {
      validator: () => typeof state.formModel.tester_see_submissions === 'boolean',
      message: '请选择测试员可见提交',
      trigger: 'change',
    },
  ],
  show_short_display: [
    {
      validator: () => typeof state.formModel.show_short_display === 'boolean',
      message: '请选择展示简短设置摘要',
      trigger: 'change',
    },
  ],
  extra: [
    createRequiredRule('扩展信息', 'input'),
    {
      validator: () => isValidJsonValue(state.formModel.extra),
      message: '请输入合法 JSON 对象',
      trigger: ['input', 'blur'],
    },
  ],
}))

async function openModal(id?: string, defaults: Partial<typeof defaultFormData> = {}) {
  state.dataId = id ?? null
  state.formModel = normalizeFormData(defaults)
  state.showModal = true
  if (id) {
    await fetchDetail(id)
  }
}

async function fetchDetail(id: string) {
  state.loading = true
  try {
    const response = await ojContestApi.detail({ id })
    state.formModel = normalizeFormData(response.data ?? {})
  } finally {
    state.loading = false
  }
}

function normalizeFormData(data: Record<string, any> = {}) {
  return {
    ...defaultFormData,
    ...data,
    tag_ids: Array.isArray(data.tag_ids) ? [...data.tag_ids] : [],
    start_time: normalizeDateTimeValue(data.start_time),
    end_time: normalizeDateTimeValue(data.end_time),
    locked_after: normalizeDateTimeValue(data.locked_after),
    format_config: stringifyJsonValue(data.format_config),
    extra: stringifyJsonValue(data.extra),
  }
}

async function loadTagOptions() {
  const response = await ojContestTagApi.list()
  const records = response.data ?? []
  tagOptions.value = records.map((item: any) => ({
    label: item.name,
    value: item.id,
  }))
}

onMounted(() => {
  void loadTagOptions()
})

function normalizeDateTimeValue(value: unknown) {
  return formatDateTime(value, '') || null
}

function normalizeSubmitDateTimeValue(value: unknown) {
  const text = formatDateTime(value, '')
  if (!text) {
    return null
  }
  const date = new Date(`${text.replace(' ', 'T')}+08:00`)
  return Number.isNaN(date.getTime()) ? null : date.toISOString().replace(/\.\d{3}Z$/, 'Z')
}

function normalizeSubmitData(data: Record<string, any>) {
  return {
    ...data,
    start_time: normalizeSubmitDateTimeValue(data.start_time),
    end_time: normalizeSubmitDateTimeValue(data.end_time),
    locked_after: normalizeSubmitDateTimeValue(data.locked_after),
    format_config: parseJsonValue(data.format_config),
    extra: parseJsonValue(data.extra),
  }
}

function parseJsonValue(value: unknown) {
  const text = String(value ?? '').trim()
  if (!text) {
    return {}
  }
  const parsed = JSON.parse(text)
  if (Array.isArray(parsed) || typeof parsed !== 'object' || parsed === null) {
    throw new Error('JSON value must be an object')
  }
  return parsed
}

function isValidJsonValue(value: unknown) {
  try {
    parseJsonValue(value)
    return true
  } catch {
    return false
  }
}

function stringifyJsonValue(value: unknown) {
  if (value === undefined || value === null || value === '') {
    return '{}'
  }
  if (typeof value === 'string') {
    try {
      return JSON.stringify(JSON.parse(value), null, 2)
    } catch {
      return value
    }
  }
  return JSON.stringify(value, null, 2)
}

function closeModal() {
  state.showModal = false
  state.submitLoading = false
}

async function submitForm() {
  await formRef.value?.validate()
  state.submitLoading = true
  try {
    const payload = normalizeSubmitData(state.formModel)
    if (state.dataId) {
      await ojContestApi.update({ ...payload, id: state.dataId })
      window.$message.success('更新成功')
    } else {
      await ojContestApi.create(payload)
      window.$message.success('创建成功')
    }
    emit('saved')
    closeModal()
  } finally {
    state.submitLoading = false
  }
}

defineExpose({
  openModal,
})
</script>

<template>
  <NModal
    v-model:show="state.showModal"
    preset="card"
    draggable
    :mask-closable="false"
    :title="modalTitle"
    style="width: 720px"
    :segmented="{ content: true, action: true }"
  >
    <NSpin :show="state.loading">
      <NScrollbar class="max-h-[min(620px,calc(100vh-300px))] pr-16px">
        <NForm ref="formRef" :model="state.formModel" :rules="rules" label-placement="left" label-width="110" :disabled="state.loading || state.submitLoading">
          <NFormItem label="竞赛标识" path="key">
            <NInput v-model:value="state.formModel.key" />
          </NFormItem>
          <NFormItem label="竞赛名称" path="name">
            <NInput v-model:value="state.formModel.name" />
          </NFormItem>
          <NFormItem label="竞赛标签" path="tag_ids">
            <NSelect
              v-model:value="state.formModel.tag_ids"
              multiple
              filterable
              clearable
              :options="tagOptions"
              placeholder="选择竞赛标签"
            />
          </NFormItem>
          <NFormItem label="竞赛说明" path="description">
            <NInput v-model:value="state.formModel.description" type="textarea" :autosize="{ minRows: 3, maxRows: 8 }" />
          </NFormItem>
          <NFormItem label="摘要" path="summary">
            <NInput v-model:value="state.formModel.summary" type="textarea" :autosize="{ minRows: 3, maxRows: 8 }" />
          </NFormItem>
          <NFormItem label="开始时间" path="start_time">
            <NDatePicker v-model:formatted-value="state.formModel.start_time" type="datetime" value-format="yyyy-MM-dd HH:mm:ss" class="w-full" clearable />
          </NFormItem>
          <NFormItem label="结束时间" path="end_time">
            <NDatePicker v-model:formatted-value="state.formModel.end_time" type="datetime" value-format="yyyy-MM-dd HH:mm:ss" class="w-full" clearable />
          </NFormItem>
          <NFormItem label="个人参赛时长（秒）" path="time_limit_seconds">
            <NInputNumber v-model:value="state.formModel.time_limit_seconds" class="w-full" />
          </NFormItem>
          <NFormItem label="是否公开可见" path="is_visible">
            <NSwitch v-model:value="state.formModel.is_visible" />
          </NFormItem>
          <NFormItem label="是否仅限指定选手" path="is_private">
            <NSwitch v-model:value="state.formModel.is_private" />
          </NFormItem>
          <NFormItem label="参赛准入码" path="access_code">
            <NInput v-model:value="state.formModel.access_code" />
          </NFormItem>
          <NFormItem label="是否计入 Rating" path="is_rated">
            <NSwitch v-model:value="state.formModel.is_rated" />
          </NFormItem>
          <NFormItem label="Rating 下限" path="rating_floor">
            <NInputNumber v-model:value="state.formModel.rating_floor" class="w-full" />
          </NFormItem>
          <NFormItem label="Rating 上限" path="rating_ceiling">
            <NInputNumber v-model:value="state.formModel.rating_ceiling" class="w-full" />
          </NFormItem>
          <NFormItem label="无提交也计 Rating" path="rate_all">
            <NSwitch v-model:value="state.formModel.rate_all" />
          </NFormItem>
          <NFormItem label="榜单可见性" path="scoreboard_visibility">
            <NInput v-model:value="state.formModel.scoreboard_visibility" />
          </NFormItem>
          <NFormItem label="赛制" path="format_name">
            <NInput v-model:value="state.formModel.format_name" />
          </NFormItem>
          <NFormItem label="赛制配置" path="format_config">
            <NInput v-model:value="state.formModel.format_config" type="textarea" :autosize="{ minRows: 3, maxRows: 8 }" />
          </NFormItem>
          <NFormItem label="分数小数精度" path="points_precision">
            <NInputNumber v-model:value="state.formModel.points_precision" class="w-full" />
          </NFormItem>
          <NFormItem label="赛中隐藏题目标签" path="hide_problem_tags">
            <NSwitch v-model:value="state.formModel.hide_problem_tags" />
          </NFormItem>
          <NFormItem label="赛中隐藏命题人" path="hide_problem_authors">
            <NSwitch v-model:value="state.formModel.hide_problem_authors" />
          </NFormItem>
          <NFormItem label="赛中仅跑 pretest" path="run_pretests_only">
            <NSwitch v-model:value="state.formModel.run_pretests_only" />
          </NFormItem>
          <NFormItem label="使用答疑" path="use_clarifications">
            <NSwitch v-model:value="state.formModel.use_clarifications" />
          </NFormItem>
          <NFormItem label="测试员可见榜单" path="tester_see_scoreboard">
            <NSwitch v-model:value="state.formModel.tester_see_scoreboard" />
          </NFormItem>
          <NFormItem label="测试员可见提交" path="tester_see_submissions">
            <NSwitch v-model:value="state.formModel.tester_see_submissions" />
          </NFormItem>
          <NFormItem label="展示简短设置摘要" path="show_short_display">
            <NSwitch v-model:value="state.formModel.show_short_display" />
          </NFormItem>
          <NFormItem label="题目标签脚本" path="problem_label_script">
            <NInput v-model:value="state.formModel.problem_label_script" type="textarea" :autosize="{ minRows: 3, maxRows: 8 }" />
          </NFormItem>
          <NFormItem label="重判锁定时间" path="locked_after">
            <NDatePicker v-model:formatted-value="state.formModel.locked_after" type="datetime" value-format="yyyy-MM-dd HH:mm:ss" class="w-full" clearable />
          </NFormItem>
          <NFormItem label="OpenGraph 图片" path="og_image">
            <NInput v-model:value="state.formModel.og_image" />
          </NFormItem>
          <NFormItem label="Logo 覆盖图" path="logo_override_image">
            <NInput v-model:value="state.formModel.logo_override_image" />
          </NFormItem>
          <NFormItem label="扩展信息" path="extra">
            <NInput v-model:value="state.formModel.extra" type="textarea" :autosize="{ minRows: 3, maxRows: 8 }" />
          </NFormItem>
        </NForm>
      </NScrollbar>
    </NSpin>

    <template #action>
      <NSpace justify="end">
        <NButton @click="closeModal">取消</NButton>
        <NButton type="primary" :loading="state.submitLoading" @click="submitForm">确认</NButton>
      </NSpace>
    </template>
  </NModal>
</template>
