"""
Generated by HEI code generator.
Author: Charlie
Generated at: 2026-07-28 20:51:12
"""

from typing import Annotated, Any

from fastapi import APIRouter, Depends, Query
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config.enums import AccountType
from app.core.response.pagination import Current, PageData, PageQuery, Size
from app.core.response.schema import ApiResponse, success
from app.core.schema.base import Id, IdQuery, IdsRequest
from app.deps.auth import require_account_type, require_permission
from app.deps.db import get_db_session
from app.modules.biz.contest.contest.schema import (
    OjContestAdminPageQuery,
    OjContestAdminSubmitRequest,
    OjContestCloneRequest,
    OjContestCreateRequest,
    OjContestLockRequest,
    OjContestRateRequest,
    OjContestRescoreRequest,
    OjContestSchema,
    OjContestScoreboardQuery,
    OjContestUnlockRequest,
    OjContestUpdateRequest,
)
from app.modules.biz.contest.contest.service import (
    OjContestService,
)
from app.modules.biz.contest.enums import ContestParticipationVirtual

router = APIRouter()


@router.post(
    "/biz/contest/contest/create",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("biz:contest:contest:create")),
    ],
    response_model=ApiResponse[str],
)
async def create(
    payload: OjContestCreateRequest,
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[str]:
    return success(await OjContestService(db).create(payload))


@router.post(
    "/biz/contest/contest/update",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("biz:contest:contest:update")),
    ],
    response_model=ApiResponse[None],
)
async def update(
    payload: OjContestUpdateRequest,
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[None]:
    await OjContestService(db).update(payload)
    return success()


@router.post(
    "/biz/contest/contest/delete",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("biz:contest:contest:delete")),
    ],
    response_model=ApiResponse[None],
)
async def delete(
    payload: IdsRequest,
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[None]:
    await OjContestService(db).delete(payload)
    return success()


@router.get(
    "/biz/contest/contest/detail",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("biz:contest:contest:detail")),
    ],
    response_model=ApiResponse[OjContestSchema],
)
async def detail(
    db: Annotated[AsyncSession, Depends(get_db_session)],
    id: Annotated[Id, Query()],
) -> ApiResponse[OjContestSchema]:
    return success(await OjContestService(db).detail(IdQuery(id=id)))


@router.get(
    "/biz/contest/contest/page",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("biz:contest:contest:page")),
    ],
    response_model=ApiResponse[PageData[OjContestSchema]],
)
async def page(
    db: Annotated[AsyncSession, Depends(get_db_session)],
    current: Current = 1,
    size: Size = 20,
    key: str | None = Query(default=None),
    name: str | None = Query(default=None),
    tag_id: str | None = Query(default=None),
) -> ApiResponse[PageData[OjContestSchema]]:
    query = OjContestAdminPageQuery(
        pagination=PageQuery(current=current, size=size),
        key=key,
        name=name,
        tag_id=tag_id,
    )
    return success(await OjContestService(db).page_admin(query))


@router.post(
    "/biz/contest/contest/lock",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("biz:contest:contest:update")),
    ],
    response_model=ApiResponse[OjContestSchema],
)
async def lock(
    payload: OjContestLockRequest,
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[OjContestSchema]:
    return success(await OjContestService(db).lock(payload))


@router.post(
    "/biz/contest/contest/unlock",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("biz:contest:contest:update")),
    ],
    response_model=ApiResponse[OjContestSchema],
)
async def unlock(
    payload: OjContestUnlockRequest,
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[OjContestSchema]:
    return success(await OjContestService(db).unlock(payload))


@router.post(
    "/biz/contest/contest/clone",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("biz:contest:contest:create")),
    ],
    response_model=ApiResponse[str],
)
async def clone(
    payload: OjContestCloneRequest,
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[str]:
    return success(await OjContestService(db).clone(payload))


@router.post(
    "/biz/contest/contest/rescore",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("biz:contest:contest:update")),
    ],
    response_model=ApiResponse[dict[str, Any]],
)
async def rescore(
    payload: OjContestRescoreRequest,
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[dict[str, Any]]:
    return success(await OjContestService(db).rescore(payload))


@router.post(
    "/biz/contest/contest/rate",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("biz:contest:contest:update")),
    ],
    response_model=ApiResponse[dict[str, Any]],
)
async def rate(
    payload: OjContestRateRequest,
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[dict[str, Any]]:
    return success(await OjContestService(db).rate(payload))


@router.get(
    "/biz/contest/contest/scoreboard",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("biz:contest:contest:detail")),
    ],
    response_model=ApiResponse[dict[str, Any]],
)
async def scoreboard(
    db: Annotated[AsyncSession, Depends(get_db_session)],
    contest_id: Annotated[Id, Query()],
    virtual: int = Query(default=int(ContestParticipationVirtual.LIVE)),
) -> ApiResponse[dict[str, Any]]:
    query = OjContestScoreboardQuery(contest_id=contest_id, virtual=virtual)
    return success(await OjContestService(db).scoreboard(query))


@router.post(
    "/biz/contest/contest/submit",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("biz:contest:contest:update")),
    ],
    response_model=ApiResponse[dict[str, Any]],
)
async def admin_submit(
    payload: OjContestAdminSubmitRequest,
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[dict[str, Any]]:
    return success(await OjContestService(db).admin_submit(payload))


@router.get(
    "/biz/contest/contest/formats",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("biz:contest:contest:page")),
    ],
    response_model=ApiResponse[list[dict[str, Any]]],
)
async def formats() -> ApiResponse[list[dict[str, Any]]]:
    return success(OjContestService.formats())
