"""
Generated by HEI code generator.
Author: Charlie
Generated at: 2026-07-28 20:51:09
"""

from datetime import datetime
from typing import Any

from pydantic import Field

from app.core.response.pagination import PageQuery
from app.core.schema.base import ApiSchema


class OjProblemGroupCreateRequest(ApiSchema):
    code: str
    name: str
    sort: int


class OjProblemGroupUpdateRequest(OjProblemGroupCreateRequest):
    id: str = Field(min_length=1, max_length=64)


class OjProblemGroupAdminPageQuery(PageQuery):
    code: str | None = None
    name: str | None = None


class OjProblemGroupSchema(ApiSchema):
    id: str
    code: str
    name: str
    sort: int
    created_at: datetime
    created_by: str | None = None
    updated_at: datetime
    updated_by: str | None = None
