"""
Generated by HEI code generator.
Author: Charlie
Generated at: 2026-07-28 20:51:10
"""

from typing import Annotated

from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config.enums import AccountType
from app.core.response.pagination import PageData
from app.core.response.schema import ApiResponse, success
from app.core.schema.base import ProblemIdsRequest, ProblemScopedIdQuery
from app.deps.auth import require_account_type, require_permission
from app.deps.db import get_db_session
from app.modules.biz.problem.language.schema import (
    OjProblemLanguageAdminPageQuery,
    OjProblemLanguageCreateRequest,
    OjProblemLanguageSchema,
    OjProblemLanguageUpdateRequest,
    WorkerLanguageOption,
)
from app.modules.biz.problem.language.service import (
    OjProblemLanguageService,
)
from app.modules.biz.problem.worker_languages import list_worker_languages

router = APIRouter()


@router.get(
    "/biz/problem/language/options",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("biz:problem:language:page")),
    ],
    response_model=ApiResponse[list[WorkerLanguageOption]],
)
async def options() -> ApiResponse[list[WorkerLanguageOption]]:
    """唯一语言选项 API：worker 镜像显式启用语言（题目语言 / 试测 / 交互器共用）。"""
    return success([WorkerLanguageOption.model_validate(item) for item in list_worker_languages()])


@router.post(
    "/biz/problem/language/create",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("biz:problem:language:create")),
    ],
    response_model=ApiResponse[None],
)
async def create(
    payload: OjProblemLanguageCreateRequest,
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[None]:
    await OjProblemLanguageService(db).create(payload)
    return success()


@router.post(
    "/biz/problem/language/update",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("biz:problem:language:update")),
    ],
    response_model=ApiResponse[None],
)
async def update(
    payload: OjProblemLanguageUpdateRequest,
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[None]:
    await OjProblemLanguageService(db).update(payload)
    return success()


@router.post(
    "/biz/problem/language/delete",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("biz:problem:language:delete")),
    ],
    response_model=ApiResponse[None],
)
async def delete(
    payload: ProblemIdsRequest,
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[None]:
    await OjProblemLanguageService(db).delete(payload)
    return success()


@router.get(
    "/biz/problem/language/detail",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("biz:problem:language:detail")),
    ],
    response_model=ApiResponse[OjProblemLanguageSchema],
)
async def detail(
    query: Annotated[ProblemScopedIdQuery, Depends()],
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[OjProblemLanguageSchema]:
    return success(await OjProblemLanguageService(db).detail(query))


@router.get(
    "/biz/problem/language/page",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("biz:problem:language:page")),
    ],
    response_model=ApiResponse[PageData[OjProblemLanguageSchema]],
)
async def page(
    query: Annotated[OjProblemLanguageAdminPageQuery, Depends()],
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[PageData[OjProblemLanguageSchema]]:
    return success(await OjProblemLanguageService(db).page_admin(query))
