"""
Generated by HEI code generator.
Author: Charlie
Generated at: 2026-07-28 20:51:10
"""

from typing import Annotated

from fastapi import APIRouter, Depends, Query
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config.enums import AccountType
from app.core.response.pagination import Current, PageData, PageQuery, Size
from app.core.response.schema import ApiResponse, success
from app.core.schema.base import Id, IdQuery, IdsRequest
from app.deps.auth import require_account_type, require_permission
from app.deps.db import get_db_session
from app.modules.biz.problem.language.schema import (
    OjProblemLanguageAdminPageQuery,
    OjProblemLanguageCreateRequest,
    OjProblemLanguageSchema,
    OjProblemLanguageUpdateRequest,
    SandboxLanguageOption,
)
from app.modules.biz.problem.language.service import (
    OjProblemLanguageService,
)
from app.modules.biz.problem.sandbox_languages import list_sandbox_languages

router = APIRouter()


@router.get(
    "/biz/problem/language/options",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("biz:problem:language:page")),
    ],
    response_model=ApiResponse[list[SandboxLanguageOption]],
)
async def options() -> ApiResponse[list[SandboxLanguageOption]]:
    """Language keys from acoj-sandbox LanguageId (aligned with worker)."""
    return success([SandboxLanguageOption.model_validate(item) for item in list_sandbox_languages()])


@router.post(
    "/biz/problem/language/create",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("biz:problem:language:create")),
    ],
    response_model=ApiResponse[None],
)
async def create(
    problem_id: Annotated[Id, Query()],
    payload: OjProblemLanguageCreateRequest,
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[None]:
    await OjProblemLanguageService(db).create(problem_id, payload)
    return success()


@router.post(
    "/biz/problem/language/update",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("biz:problem:language:update")),
    ],
    response_model=ApiResponse[None],
)
async def update(
    problem_id: Annotated[Id, Query()],
    payload: OjProblemLanguageUpdateRequest,
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[None]:
    await OjProblemLanguageService(db).update(problem_id, payload)
    return success()


@router.post(
    "/biz/problem/language/delete",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("biz:problem:language:delete")),
    ],
    response_model=ApiResponse[None],
)
async def delete(
    problem_id: Annotated[Id, Query()],
    payload: IdsRequest,
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[None]:
    await OjProblemLanguageService(db).delete(problem_id, payload)
    return success()


@router.get(
    "/biz/problem/language/detail",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("biz:problem:language:detail")),
    ],
    response_model=ApiResponse[OjProblemLanguageSchema],
)
async def detail(
    problem_id: Annotated[Id, Query()],
    db: Annotated[AsyncSession, Depends(get_db_session)],
    id: Annotated[Id, Query()],
) -> ApiResponse[OjProblemLanguageSchema]:
    return success(await OjProblemLanguageService(db).detail(problem_id, IdQuery(id=id)))


@router.get(
    "/biz/problem/language/page",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("biz:problem:language:page")),
    ],
    response_model=ApiResponse[PageData[OjProblemLanguageSchema]],
)
async def page(
    problem_id: Annotated[Id, Query()],
    db: Annotated[AsyncSession, Depends(get_db_session)],
    current: Current = 1,
    size: Size = 20,
) -> ApiResponse[PageData[OjProblemLanguageSchema]]:
    query = OjProblemLanguageAdminPageQuery(
        pagination=PageQuery(current=current, size=size),
    )
    return success(await OjProblemLanguageService(db).page_admin(problem_id, query))
