"""
Generated by HEI code generator.
Author: Charlie
Generated at: 2026-07-28 20:51:11
"""

from datetime import datetime
from typing import Any, Self

from pydantic import Field, model_validator

from app.core.response.pagination import PageQuery
from app.core.schema.base import ApiSchema
from app.modules.biz.problem.enums import TestCaseDataMode, TestCaseType


class OjProblemTestCaseCreateRequest(ApiSchema):
    problem_id: str
    case_no: int
    sort: int
    case_type: TestCaseType = TestCaseType.NORMAL
    data_mode: TestCaseDataMode = TestCaseDataMode.FILE
    input_file: str | None = None
    output_file: str | None = None
    input_inline: str | None = None
    output_inline: str | None = None
    input_sha256: str | None = None
    output_sha256: str | None = None
    points: float | None = None
    is_pretest: bool = False
    time_limit_ms: int | None = None
    memory_limit_kb: int | None = None
    batch_no: int | None = None
    batch_depends: list = Field(default_factory=list)
    checker: str | None = None
    checker_args: dict[str, Any] | None = Field(default_factory=dict)
    generator_args: str | None = None
    output_prefix: int | None = None
    output_limit: int | None = None
    extra: dict[str, Any] = Field(default_factory=dict)

    @model_validator(mode="after")
    def validate_data_mode(self) -> Self:
        if self.data_mode == TestCaseDataMode.FILE:
            if not self.input_file or not self.output_file:
                raise ValueError("file 模式需要 input_file 与 output_file（storage key）")
        elif self.data_mode == TestCaseDataMode.INLINE:
            if self.input_inline is None or self.output_inline is None:
                raise ValueError("inline 模式需要 input_inline 与 output_inline")
        return self


class OjProblemTestCaseUpdateRequest(OjProblemTestCaseCreateRequest):
    id: str = Field(min_length=1, max_length=64)


class OjProblemTestCaseAdminPageQuery(ApiSchema):
    pagination: PageQuery
    problem_id: str | None = None
    data_mode: TestCaseDataMode | None = None


class OjProblemTestCaseSchema(ApiSchema):
    id: str
    problem_id: str
    case_no: int
    sort: int
    case_type: str
    data_mode: str
    input_file: str | None = None
    output_file: str | None = None
    input_inline: str | None = None
    output_inline: str | None = None
    input_sha256: str | None = None
    output_sha256: str | None = None
    points: float | None = None
    is_pretest: bool
    time_limit_ms: int | None = None
    memory_limit_kb: int | None = None
    batch_no: int | None = None
    batch_depends: list
    checker: str | None = None
    checker_args: dict[str, Any] | None = Field(default_factory=dict)
    generator_args: str | None = None
    output_prefix: int | None = None
    output_limit: int | None = None
    extra: dict[str, Any]
    created_at: datetime
    created_by: str | None = None
    updated_at: datetime
    updated_by: str | None = None
