"""
Generated by HEI code generator.
Author: Charlie
Generated at: 2026-07-28 20:51:11
"""

from sqlalchemy.ext.asyncio import AsyncSession

from app.core.exceptions.business import NotFoundError
from app.modules.biz.oj_scope import delete_owned_by_parent, ensure_belongs_to_parent
from app.core.response.pagination import PageData, build_page
from app.core.schema.base import ProblemIdsRequest, ProblemScopedIdQuery, to_schema, to_schema_list
from app.platform.db.transaction import transactional
from app.modules.biz.problem.test_case.model import OjProblemTestCase
from app.modules.biz.problem.test_case.repository import (
    OjProblemTestCaseRepository,
)
from app.modules.biz.problem.test_case.schema import (
    OjProblemTestCaseAdminPageQuery,
    OjProblemTestCaseCreateRequest,
    OjProblemTestCaseSchema,
    OjProblemTestCaseUpdateRequest,
)


class OjProblemTestCaseService:
    def __init__(self, db: AsyncSession):
        self.db = db
        self.repo = OjProblemTestCaseRepository(db)

    async def create(self, payload: OjProblemTestCaseCreateRequest) -> None:
        async with transactional(self.db):
            await self.repo.create(payload)

    async def update(self, payload: OjProblemTestCaseUpdateRequest) -> None:
        async with transactional(self.db):
            entity = await self.repo.get_required(payload.id)
            ensure_belongs_to_parent(entity, parent_attr="problem_id", parent_id=payload.problem_id, not_found_message="OjProblemTestCase not found")
            await self.repo.update(payload)

    async def delete(self, payload: ProblemIdsRequest) -> None:
        async with transactional(self.db):
            await delete_owned_by_parent(
                self.db,
                model=OjProblemTestCase,
                parent_attr="problem_id",
                parent_id=payload.problem_id,
                entity_ids=payload.ids,
                not_found_message="OjProblemTestCase not found",
            )

    async def detail(self, query: ProblemScopedIdQuery) -> OjProblemTestCaseSchema:
        entity = await self.repo.get_required(query.id)
        ensure_belongs_to_parent(entity, parent_attr="problem_id", parent_id=query.problem_id, not_found_message="OjProblemTestCase not found")
        return to_schema(OjProblemTestCaseSchema, entity)

    async def page_admin(
        self, query: OjProblemTestCaseAdminPageQuery
    ) -> PageData[OjProblemTestCaseSchema]:
        items, total = await self.repo.page_admin(query)
        return build_page(query.pagination, total, to_schema_list(OjProblemTestCaseSchema, items))
