// Code generated by ent, DO NOT EDIT.

package sysdictdata

import (
	"hei-gin/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldContainsFold(FieldID, id))
}

// DictID applies equality check predicate on the "dict_id" field. It's identical to DictIDEQ.
func DictID(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldEQ(FieldDictID, v))
}

// Value applies equality check predicate on the "value" field. It's identical to ValueEQ.
func Value(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldEQ(FieldValue, v))
}

// Color applies equality check predicate on the "color" field. It's identical to ColorEQ.
func Color(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldEQ(FieldColor, v))
}

// SortCode applies equality check predicate on the "sort_code" field. It's identical to SortCodeEQ.
func SortCode(v int) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldEQ(FieldSortCode, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldEQ(FieldUpdatedBy, v))
}

// DictIDEQ applies the EQ predicate on the "dict_id" field.
func DictIDEQ(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldEQ(FieldDictID, v))
}

// DictIDNEQ applies the NEQ predicate on the "dict_id" field.
func DictIDNEQ(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldNEQ(FieldDictID, v))
}

// DictIDIn applies the In predicate on the "dict_id" field.
func DictIDIn(vs ...string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldIn(FieldDictID, vs...))
}

// DictIDNotIn applies the NotIn predicate on the "dict_id" field.
func DictIDNotIn(vs ...string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldNotIn(FieldDictID, vs...))
}

// DictIDGT applies the GT predicate on the "dict_id" field.
func DictIDGT(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldGT(FieldDictID, v))
}

// DictIDGTE applies the GTE predicate on the "dict_id" field.
func DictIDGTE(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldGTE(FieldDictID, v))
}

// DictIDLT applies the LT predicate on the "dict_id" field.
func DictIDLT(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldLT(FieldDictID, v))
}

// DictIDLTE applies the LTE predicate on the "dict_id" field.
func DictIDLTE(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldLTE(FieldDictID, v))
}

// DictIDContains applies the Contains predicate on the "dict_id" field.
func DictIDContains(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldContains(FieldDictID, v))
}

// DictIDHasPrefix applies the HasPrefix predicate on the "dict_id" field.
func DictIDHasPrefix(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldHasPrefix(FieldDictID, v))
}

// DictIDHasSuffix applies the HasSuffix predicate on the "dict_id" field.
func DictIDHasSuffix(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldHasSuffix(FieldDictID, v))
}

// DictIDEqualFold applies the EqualFold predicate on the "dict_id" field.
func DictIDEqualFold(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldEqualFold(FieldDictID, v))
}

// DictIDContainsFold applies the ContainsFold predicate on the "dict_id" field.
func DictIDContainsFold(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldContainsFold(FieldDictID, v))
}

// LabelEQ applies the EQ predicate on the "label" field.
func LabelEQ(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldEQ(FieldLabel, v))
}

// LabelNEQ applies the NEQ predicate on the "label" field.
func LabelNEQ(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldNEQ(FieldLabel, v))
}

// LabelIn applies the In predicate on the "label" field.
func LabelIn(vs ...string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldIn(FieldLabel, vs...))
}

// LabelNotIn applies the NotIn predicate on the "label" field.
func LabelNotIn(vs ...string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldNotIn(FieldLabel, vs...))
}

// LabelGT applies the GT predicate on the "label" field.
func LabelGT(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldGT(FieldLabel, v))
}

// LabelGTE applies the GTE predicate on the "label" field.
func LabelGTE(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldGTE(FieldLabel, v))
}

// LabelLT applies the LT predicate on the "label" field.
func LabelLT(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldLT(FieldLabel, v))
}

// LabelLTE applies the LTE predicate on the "label" field.
func LabelLTE(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldLTE(FieldLabel, v))
}

// LabelContains applies the Contains predicate on the "label" field.
func LabelContains(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldContains(FieldLabel, v))
}

// LabelHasPrefix applies the HasPrefix predicate on the "label" field.
func LabelHasPrefix(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldHasPrefix(FieldLabel, v))
}

// LabelHasSuffix applies the HasSuffix predicate on the "label" field.
func LabelHasSuffix(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldHasSuffix(FieldLabel, v))
}

// LabelEqualFold applies the EqualFold predicate on the "label" field.
func LabelEqualFold(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldEqualFold(FieldLabel, v))
}

// LabelContainsFold applies the ContainsFold predicate on the "label" field.
func LabelContainsFold(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldContainsFold(FieldLabel, v))
}

// ValueEQ applies the EQ predicate on the "value" field.
func ValueEQ(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldEQ(FieldValue, v))
}

// ValueNEQ applies the NEQ predicate on the "value" field.
func ValueNEQ(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldNEQ(FieldValue, v))
}

// ValueIn applies the In predicate on the "value" field.
func ValueIn(vs ...string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldIn(FieldValue, vs...))
}

// ValueNotIn applies the NotIn predicate on the "value" field.
func ValueNotIn(vs ...string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldNotIn(FieldValue, vs...))
}

// ValueGT applies the GT predicate on the "value" field.
func ValueGT(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldGT(FieldValue, v))
}

// ValueGTE applies the GTE predicate on the "value" field.
func ValueGTE(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldGTE(FieldValue, v))
}

// ValueLT applies the LT predicate on the "value" field.
func ValueLT(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldLT(FieldValue, v))
}

// ValueLTE applies the LTE predicate on the "value" field.
func ValueLTE(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldLTE(FieldValue, v))
}

// ValueContains applies the Contains predicate on the "value" field.
func ValueContains(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldContains(FieldValue, v))
}

// ValueHasPrefix applies the HasPrefix predicate on the "value" field.
func ValueHasPrefix(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldHasPrefix(FieldValue, v))
}

// ValueHasSuffix applies the HasSuffix predicate on the "value" field.
func ValueHasSuffix(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldHasSuffix(FieldValue, v))
}

// ValueEqualFold applies the EqualFold predicate on the "value" field.
func ValueEqualFold(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldEqualFold(FieldValue, v))
}

// ValueContainsFold applies the ContainsFold predicate on the "value" field.
func ValueContainsFold(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldContainsFold(FieldValue, v))
}

// ColorEQ applies the EQ predicate on the "color" field.
func ColorEQ(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldEQ(FieldColor, v))
}

// ColorNEQ applies the NEQ predicate on the "color" field.
func ColorNEQ(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldNEQ(FieldColor, v))
}

// ColorIn applies the In predicate on the "color" field.
func ColorIn(vs ...string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldIn(FieldColor, vs...))
}

// ColorNotIn applies the NotIn predicate on the "color" field.
func ColorNotIn(vs ...string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldNotIn(FieldColor, vs...))
}

// ColorGT applies the GT predicate on the "color" field.
func ColorGT(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldGT(FieldColor, v))
}

// ColorGTE applies the GTE predicate on the "color" field.
func ColorGTE(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldGTE(FieldColor, v))
}

// ColorLT applies the LT predicate on the "color" field.
func ColorLT(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldLT(FieldColor, v))
}

// ColorLTE applies the LTE predicate on the "color" field.
func ColorLTE(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldLTE(FieldColor, v))
}

// ColorContains applies the Contains predicate on the "color" field.
func ColorContains(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldContains(FieldColor, v))
}

// ColorHasPrefix applies the HasPrefix predicate on the "color" field.
func ColorHasPrefix(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldHasPrefix(FieldColor, v))
}

// ColorHasSuffix applies the HasSuffix predicate on the "color" field.
func ColorHasSuffix(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldHasSuffix(FieldColor, v))
}

// ColorIsNil applies the IsNil predicate on the "color" field.
func ColorIsNil() predicate.SysDictData {
	return predicate.SysDictData(sql.FieldIsNull(FieldColor))
}

// ColorNotNil applies the NotNil predicate on the "color" field.
func ColorNotNil() predicate.SysDictData {
	return predicate.SysDictData(sql.FieldNotNull(FieldColor))
}

// ColorEqualFold applies the EqualFold predicate on the "color" field.
func ColorEqualFold(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldEqualFold(FieldColor, v))
}

// ColorContainsFold applies the ContainsFold predicate on the "color" field.
func ColorContainsFold(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldContainsFold(FieldColor, v))
}

// SortCodeEQ applies the EQ predicate on the "sort_code" field.
func SortCodeEQ(v int) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldEQ(FieldSortCode, v))
}

// SortCodeNEQ applies the NEQ predicate on the "sort_code" field.
func SortCodeNEQ(v int) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldNEQ(FieldSortCode, v))
}

// SortCodeIn applies the In predicate on the "sort_code" field.
func SortCodeIn(vs ...int) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldIn(FieldSortCode, vs...))
}

// SortCodeNotIn applies the NotIn predicate on the "sort_code" field.
func SortCodeNotIn(vs ...int) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldNotIn(FieldSortCode, vs...))
}

// SortCodeGT applies the GT predicate on the "sort_code" field.
func SortCodeGT(v int) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldGT(FieldSortCode, v))
}

// SortCodeGTE applies the GTE predicate on the "sort_code" field.
func SortCodeGTE(v int) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldGTE(FieldSortCode, v))
}

// SortCodeLT applies the LT predicate on the "sort_code" field.
func SortCodeLT(v int) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldLT(FieldSortCode, v))
}

// SortCodeLTE applies the LTE predicate on the "sort_code" field.
func SortCodeLTE(v int) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldLTE(FieldSortCode, v))
}

// SortCodeIsNil applies the IsNil predicate on the "sort_code" field.
func SortCodeIsNil() predicate.SysDictData {
	return predicate.SysDictData(sql.FieldIsNull(FieldSortCode))
}

// SortCodeNotNil applies the NotNil predicate on the "sort_code" field.
func SortCodeNotNil() predicate.SysDictData {
	return predicate.SysDictData(sql.FieldNotNull(FieldSortCode))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusIsNil applies the IsNil predicate on the "status" field.
func StatusIsNil() predicate.SysDictData {
	return predicate.SysDictData(sql.FieldIsNull(FieldStatus))
}

// StatusNotNil applies the NotNil predicate on the "status" field.
func StatusNotNil() predicate.SysDictData {
	return predicate.SysDictData(sql.FieldNotNull(FieldStatus))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldContainsFold(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.SysDictData {
	return predicate.SysDictData(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.SysDictData {
	return predicate.SysDictData(sql.FieldNotNull(FieldCreatedAt))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.SysDictData {
	return predicate.SysDictData(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.SysDictData {
	return predicate.SysDictData(sql.FieldNotNull(FieldCreatedBy))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldContainsFold(FieldCreatedBy, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.SysDictData {
	return predicate.SysDictData(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.SysDictData {
	return predicate.SysDictData(sql.FieldNotNull(FieldUpdatedAt))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "updated_by" field.
func UpdatedByContains(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "updated_by" field.
func UpdatedByHasPrefix(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "updated_by" field.
func UpdatedByHasSuffix(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.SysDictData {
	return predicate.SysDictData(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.SysDictData {
	return predicate.SysDictData(sql.FieldNotNull(FieldUpdatedBy))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "updated_by" field.
func UpdatedByEqualFold(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "updated_by" field.
func UpdatedByContainsFold(v string) predicate.SysDictData {
	return predicate.SysDictData(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SysDictData) predicate.SysDictData {
	return predicate.SysDictData(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SysDictData) predicate.SysDictData {
	return predicate.SysDictData(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SysDictData) predicate.SysDictData {
	return predicate.SysDictData(sql.NotPredicates(p))
}
