"""
Generated by HEI code generator.
Author: Charlie
Generated at: 2026-07-28 20:51:09
"""

from sqlalchemy import Select, delete, func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.exceptions.business import NotFoundError
from app.modules.biz.problem.type.model import (
    OjProblemType,
    OjProblemTypeRel,
)
from app.modules.biz.problem.type.schema import (
    OjProblemTypeAdminPageQuery,
    OjProblemTypeCreateRequest,
    OjProblemTypeUpdateRequest,
)


class OjProblemTypeRepository:
    def __init__(self, db: AsyncSession):
        self.db = db

    async def create(self, payload: OjProblemTypeCreateRequest) -> OjProblemType:
        entity = OjProblemType(**payload.model_dump())
        self.db.add(entity)
        await self.db.flush()
        return entity

    async def get_by_id(self, entity_id: str) -> OjProblemType | None:
        return await self.db.get(OjProblemType, entity_id)

    async def get_required(self, entity_id: str) -> OjProblemType:
        entity = await self.get_by_id(entity_id)
        if entity is None:
            raise NotFoundError("OjProblemType not found")
        return entity

    async def update(self, payload: OjProblemTypeUpdateRequest) -> None:
        entity = await self.get_required(payload.id)
        for key, value in payload.model_dump(exclude={"id"}).items():
            setattr(entity, key, value)
        await self.db.flush()

    async def delete_many(self, entity_ids: list[str]) -> None:
        unique_ids = list(dict.fromkeys(entity_ids))
        stmt = select(OjProblemType.id).where(OjProblemType.id.in_(unique_ids))
        existing_ids = set((await self.db.execute(stmt)).scalars().all())
        if len(existing_ids) != len(unique_ids):
            raise NotFoundError("OjProblemType not found")
        await self.db.execute(delete(OjProblemTypeRel).where(OjProblemTypeRel.type_id.in_(unique_ids)))
        await self.db.execute(delete(OjProblemType).where(OjProblemType.id.in_(unique_ids)))

    async def page_admin(self, query: OjProblemTypeAdminPageQuery) -> tuple[list[OjProblemType], int]:
        stmt: Select[tuple[OjProblemType]] = select(OjProblemType)
        count_stmt = select(func.count(OjProblemType.id))
        filters = []
        if query.code:
            filters.append(OjProblemType.code.ilike(f"%{query.code}%"))
        if query.name:
            filters.append(OjProblemType.name.ilike(f"%{query.name}%"))
        if filters:
            stmt = stmt.where(*filters)
            count_stmt = count_stmt.where(*filters)
        stmt = stmt.order_by(OjProblemType.id.desc()).offset(query.pagination.offset).limit(query.pagination.size)
        items = list((await self.db.execute(stmt)).scalars().all())
        total = (await self.db.execute(count_stmt)).scalar_one()
        return items, total

    async def list_all(self) -> list[OjProblemType]:
        stmt = select(OjProblemType).order_by(OjProblemType.sort.asc(), OjProblemType.code.asc())
        return list((await self.db.execute(stmt)).scalars().all())
