"""
Generated by HEI code generator.
Author: Charlie
Generated at: 2026-07-28 20:51:09
"""

from sqlalchemy.ext.asyncio import AsyncSession

from app.core.response.pagination import PageData, build_page
from app.core.schema.base import IdQuery, IdsRequest, to_schema, to_schema_list
from app.modules.biz.oj_options import OjNamedOption
from app.platform.db.transaction import transactional
from app.modules.biz.problem.type.repository import (
    OjProblemTypeRepository,
)
from app.modules.biz.problem.type.schema import (
    OjProblemTypeAdminPageQuery,
    OjProblemTypeCreateRequest,
    OjProblemTypeSchema,
    OjProblemTypeUpdateRequest,
)


class OjProblemTypeService:
    def __init__(self, db: AsyncSession):
        self.db = db
        self.repo = OjProblemTypeRepository(db)

    async def create(self, payload: OjProblemTypeCreateRequest) -> None:
        async with transactional(self.db):
            await self.repo.create(payload)

    async def update(self, payload: OjProblemTypeUpdateRequest) -> None:
        async with transactional(self.db):
            await self.repo.update(payload)

    async def delete(self, payload: IdsRequest) -> None:
        async with transactional(self.db):
            await self.repo.delete_many(payload.ids)

    async def detail(self, query: IdQuery) -> OjProblemTypeSchema:
        return to_schema(OjProblemTypeSchema, await self.repo.get_required(query.id))

    async def page_admin(self, query: OjProblemTypeAdminPageQuery) -> PageData[OjProblemTypeSchema]:
        items, total = await self.repo.page_admin(query)
        return build_page(query.pagination, total, to_schema_list(OjProblemTypeSchema, items))

    async def list_options(self) -> list[OjNamedOption]:
        items = await self.repo.list_all()
        return [OjNamedOption(id=item.id, code=item.code, name=item.name) for item in items]
