"""add resource layout"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '20338b04a088'
down_revision: str | Sequence[str] | None = '80bbc87821be'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_resource', sa.Column('layout', sa.String(length=255), nullable=True, comment='布局类型'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sys_resource', 'layout')
    # ### end Alembic commands ###
