"""oj test case data_mode inline and storage key columns"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '571ebd1d248f'
down_revision: str | Sequence[str] | None = 'd57972b97c68'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oj_problem_data', 'zip_file_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=512),
               comment='测试数据 zip storage key',
               existing_comment='测试数据 zip 文件ID',
               existing_nullable=True)
    op.alter_column('oj_problem_data', 'generator_file_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=512),
               comment='数据生成器 storage key',
               existing_comment='数据生成器文件ID',
               existing_nullable=True)
    op.alter_column('oj_problem_data', 'spj_file_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=512),
               comment='自定义 SPJ storage key',
               existing_comment='自定义 SPJ 文件ID',
               existing_nullable=True)
    op.alter_column('oj_problem_data', 'interactor_file_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=512),
               comment='交互器 storage key',
               existing_comment='交互器文件ID',
               existing_nullable=True)
    op.add_column(
        'oj_problem_test_case',
        sa.Column('data_mode', sa.String(length=16), nullable=False, server_default='file', comment='数据模式 file|inline'),
    )
    op.add_column('oj_problem_test_case', sa.Column('input_inline', sa.Text(), nullable=True, comment='内联输入'))
    op.add_column('oj_problem_test_case', sa.Column('output_inline', sa.Text(), nullable=True, comment='内联输出'))
    op.alter_column('oj_problem_test_case', 'data_mode', server_default=None)
    op.alter_column('oj_problem_test_case', 'input_file',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               comment='输入文件 storage key',
               existing_comment='输入文件名',
               existing_nullable=True)
    op.alter_column('oj_problem_test_case', 'output_file',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               comment='输出文件 storage key',
               existing_comment='输出文件名',
               existing_nullable=True)
    op.alter_column('oj_problem_test_case', 'input_file_id',
               existing_type=sa.VARCHAR(length=64),
               comment='输入文件元数据ID',
               existing_comment='输入文件ID',
               existing_nullable=True)
    op.alter_column('oj_problem_test_case', 'output_file_id',
               existing_type=sa.VARCHAR(length=64),
               comment='输出文件元数据ID',
               existing_comment='输出文件ID',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oj_problem_test_case', 'output_file_id',
               existing_type=sa.VARCHAR(length=64),
               comment='输出文件ID',
               existing_comment='输出文件元数据ID',
               existing_nullable=True)
    op.alter_column('oj_problem_test_case', 'input_file_id',
               existing_type=sa.VARCHAR(length=64),
               comment='输入文件ID',
               existing_comment='输入文件元数据ID',
               existing_nullable=True)
    op.alter_column('oj_problem_test_case', 'output_file',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               comment='输出文件名',
               existing_comment='输出文件 storage key',
               existing_nullable=True)
    op.alter_column('oj_problem_test_case', 'input_file',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               comment='输入文件名',
               existing_comment='输入文件 storage key',
               existing_nullable=True)
    op.drop_column('oj_problem_test_case', 'output_inline')
    op.drop_column('oj_problem_test_case', 'input_inline')
    op.drop_column('oj_problem_test_case', 'data_mode')
    op.alter_column('oj_problem_data', 'interactor_file_id',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=64),
               comment='交互器文件ID',
               existing_comment='交互器 storage key',
               existing_nullable=True)
    op.alter_column('oj_problem_data', 'spj_file_id',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=64),
               comment='自定义 SPJ 文件ID',
               existing_comment='自定义 SPJ storage key',
               existing_nullable=True)
    op.alter_column('oj_problem_data', 'generator_file_id',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=64),
               comment='数据生成器文件ID',
               existing_comment='数据生成器 storage key',
               existing_nullable=True)
    op.alter_column('oj_problem_data', 'zip_file_id',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=64),
               comment='测试数据 zip 文件ID',
               existing_comment='测试数据 zip storage key',
               existing_nullable=True)
    # ### end Alembic commands ###
