"""add sys_storage_config table"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '6f2e5eb8dcf7'
down_revision: str | Sequence[str] | None = '422745a0ef20'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_storage_config',
    sa.Column('id', sa.String(length=64), nullable=False, comment='主键'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='配置名称'),
    sa.Column('provider', sa.String(length=32), nullable=False, comment='存储服务商：local/minio/s3/oss'),
    sa.Column('bucket', sa.String(length=255), nullable=True, comment='存储桶'),
    sa.Column('endpoint', sa.String(length=500), nullable=True, comment='服务端点'),
    sa.Column('access_key', sa.String(length=255), nullable=True, comment='访问密钥 ID'),
    sa.Column('secret_key', sa.String(length=255), nullable=True, comment='访问密钥 Secret'),
    sa.Column('region', sa.String(length=100), nullable=True, comment='区域'),
    sa.Column('use_ssl', sa.Boolean(), nullable=False, comment='是否使用 SSL 连接'),
    sa.Column('base_url', sa.String(length=500), nullable=True, comment='自定义基础 URL'),
    sa.Column('public_path', sa.String(length=255), nullable=False, comment='公开访问路径'),
    sa.Column('local_root', sa.String(length=500), nullable=False, comment='本地存储根目录'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='是否为当前启用的默认配置（互斥）'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('sort_code', sa.Integer(), nullable=False, comment='排序码'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('created_by', sa.String(length=64), nullable=True, comment='创建人'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('updated_by', sa.String(length=64), nullable=True, comment='更新人'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_storage_config'))
    )
    op.create_index(
        'uq_sys_storage_config_default',
        'sys_storage_config',
        ['is_default'],
        unique=True,
        postgresql_where=sa.text('is_default = true'),
    )

    # 从 sys_config 迁移已有的 storage.* 配置
    conn = op.get_bind()
    if conn.dialect.name.startswith('postgresql'):
        rows = conn.execute(
            sa.text("SELECT config_key, config_value FROM sys_config WHERE category = 'STORAGE' AND config_key NOT LIKE 'storage.upload_%'")
        ).fetchall()
        if rows:
            config_map = {row[0]: row[1] for row in rows}
            use_ssl_val = config_map.get('storage.use_ssl', 'false') == 'true'
            conn.execute(
                sa.text("""
                    INSERT INTO sys_storage_config (
                        id, name, provider, bucket, endpoint, access_key, secret_key,
                        region, use_ssl, base_url, public_path, local_root, is_default,
                        remark, sort_code
                    ) VALUES (
                        '200101', '默认配置',
                        :provider, :bucket, :endpoint, :access_key, :secret_key,
                        :region, :use_ssl, :base_url, :public_path, :local_root,
                        true, '', 0
                    )
                """),
                {
                    'provider': config_map.get('storage.provider', 'local'),
                    'bucket': config_map.get('storage.bucket', ''),
                    'endpoint': config_map.get('storage.endpoint', ''),
                    'access_key': config_map.get('storage.access_key', ''),
                    'secret_key': config_map.get('storage.secret_key', ''),
                    'region': config_map.get('storage.region', ''),
                    'use_ssl': use_ssl_val,
                    'base_url': config_map.get('storage.base_url', ''),
                    'public_path': config_map.get('storage.public_path', '/api/v1/files'),
                    'local_root': config_map.get('storage.local_root', 'storage'),
                }
            )
            # 删除已迁移的 storage.* 配置（保留 upload 相关）
            conn.execute(
                sa.text("DELETE FROM sys_config WHERE category = 'STORAGE' AND config_key NOT LIKE 'storage.upload_%'")
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sys_storage_config')
    # ### end Alembic commands ###
