"""add_password_history"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '7d921f48c092'
down_revision: str | Sequence[str] | None = '73ab89db9f27'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_account_password_history',
    sa.Column('id', sa.String(length=64), nullable=False, comment='主键'),
    sa.Column('account_id', sa.String(length=64), nullable=False, comment='账户ID'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('changed_by', sa.String(length=64), nullable=True, comment='变更人（账户ID或系统）'),
    sa.Column('change_reason', sa.String(length=64), nullable=True, comment='变更原因: register / admin_reset / self_reset / password_expired'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='变更时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_account_password_history'))
    )
    op.create_index('idx_pwd_history_account_created', 'sys_account_password_history', ['account_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_pwd_history_account_created', table_name='sys_account_password_history')
    op.drop_table('sys_account_password_history')
    # ### end Alembic commands ###
