"""add friend and group join request tables"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '82bb86a662b7'
down_revision: str | Sequence[str] | None = '20e3c1a790ce'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('msg_group_join_request',
    sa.Column('id', sa.String(length=64), nullable=False, comment='主键'),
    sa.Column('group_id', sa.String(length=64), nullable=False, comment='群组ID'),
    sa.Column('applicant_type', sa.String(length=32), nullable=False, comment='申请人账户类型'),
    sa.Column('applicant_id', sa.String(length=64), nullable=False, comment='申请人账户ID'),
    sa.Column('message', sa.Text(), nullable=True, comment='申请附言'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='状态'),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=True, comment='处理时间'),
    sa.Column('handled_by_type', sa.String(length=32), nullable=True, comment='处理人账户类型'),
    sa.Column('handled_by_id', sa.String(length=64), nullable=True, comment='处理人账户ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('created_by', sa.String(length=64), nullable=True, comment='创建人'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('updated_by', sa.String(length=64), nullable=True, comment='更新人'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_msg_group_join_request')),
    sa.UniqueConstraint('group_id', 'applicant_type', 'applicant_id', name='uq_msg_group_join_request')
    )
    op.create_index('ix_msg_group_join_request_applicant', 'msg_group_join_request', ['applicant_type', 'applicant_id'], unique=False)
    op.create_index('ix_msg_group_join_request_group', 'msg_group_join_request', ['group_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_msg_group_join_request_group', table_name='msg_group_join_request')
    op.drop_index('ix_msg_group_join_request_applicant', table_name='msg_group_join_request')
    op.drop_table('msg_group_join_request')
    # ### end Alembic commands ###
