"""add_alert_log"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'cfbf047505b2'
down_revision: str | Sequence[str] | None = '7d921f48c092'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_alert_log',
    sa.Column('id', sa.String(length=64), nullable=False, comment='主键'),
    sa.Column('rule_name', sa.String(length=64), nullable=False, comment='规则名称'),
    sa.Column('severity', sa.String(length=16), nullable=False, comment='严重级别: INFO/WARNING/CRITICAL'),
    sa.Column('summary', sa.String(length=255), nullable=False, comment='告警摘要'),
    sa.Column('details', sa.JSON(), nullable=True, comment='告警详情（JSON）'),
    sa.Column('notified_via', sa.String(length=64), nullable=True, comment='通知方式: email/webhook'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='通知时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_alert_log'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sys_alert_log')
    # ### end Alembic commands ###
