"""
Generated by HEI code generator.
Author: Charlie
Generated at: 2026-07-28 20:51:11
"""

from datetime import datetime
from typing import Any

from pydantic import Field

from app.core.response.pagination import PageQuery
from app.core.schema.base import ApiSchema


class OjProblemSolutionCreateRequest(ApiSchema):
    problem_id: str
    content: str
    is_public: bool
    publish_at: datetime | None = None
    author_account_ids: list


class OjProblemSolutionUpdateRequest(OjProblemSolutionCreateRequest):
    id: str = Field(min_length=1, max_length=64)


class OjProblemSolutionAdminPageQuery(PageQuery):
    problem_id: str = Field(min_length=1, max_length=64)


class OjProblemSolutionSchema(ApiSchema):
    id: str
    problem_id: str
    content: str
    is_public: bool
    publish_at: datetime | None = None
    author_account_ids: list
    created_at: datetime
    created_by: str | None = None
    updated_at: datetime
    updated_by: str | None = None
