"""
Generated by HEI code generator.
Author: Charlie
Generated at: 2026-07-28 20:51:11
"""

from sqlalchemy.ext.asyncio import AsyncSession

from app.core.exceptions.business import NotFoundError
from app.modules.biz.oj_scope import delete_owned_by_parent, ensure_belongs_to_parent
from app.core.response.pagination import PageData, build_page
from app.core.schema.base import ProblemIdsRequest, ProblemScopedIdQuery, to_schema, to_schema_list
from app.platform.db.transaction import transactional
from app.modules.biz.problem.solution.model import OjProblemSolution
from app.modules.biz.problem.solution.repository import (
    OjProblemSolutionRepository,
)
from app.modules.biz.problem.solution.schema import (
    OjProblemSolutionAdminPageQuery,
    OjProblemSolutionCreateRequest,
    OjProblemSolutionSchema,
    OjProblemSolutionUpdateRequest,
)


class OjProblemSolutionService:
    def __init__(self, db: AsyncSession):
        self.db = db
        self.repo = OjProblemSolutionRepository(db)

    async def create(self, payload: OjProblemSolutionCreateRequest) -> None:
        async with transactional(self.db):
            await self.repo.create(payload)

    async def update(self, payload: OjProblemSolutionUpdateRequest) -> None:
        async with transactional(self.db):
            entity = await self.repo.get_required(payload.id)
            ensure_belongs_to_parent(entity, parent_attr="problem_id", parent_id=payload.problem_id, not_found_message="OjProblemSolution not found")
            await self.repo.update(payload)

    async def delete(self, payload: ProblemIdsRequest) -> None:
        async with transactional(self.db):
            await delete_owned_by_parent(
                self.db,
                model=OjProblemSolution,
                parent_attr="problem_id",
                parent_id=payload.problem_id,
                entity_ids=payload.ids,
                not_found_message="OjProblemSolution not found",
            )

    async def detail(self, query: ProblemScopedIdQuery) -> OjProblemSolutionSchema:
        entity = await self.repo.get_required(query.id)
        ensure_belongs_to_parent(entity, parent_attr="problem_id", parent_id=query.problem_id, not_found_message="OjProblemSolution not found")
        return to_schema(OjProblemSolutionSchema, entity)

    async def page_admin(
        self, query: OjProblemSolutionAdminPageQuery
    ) -> PageData[OjProblemSolutionSchema]:
        items, total = await self.repo.page_admin(query)
        return build_page(query.pagination, total, to_schema_list(OjProblemSolutionSchema, items))
