server:
  port: 89

spring:
  application:
    name: galaxy-oj
  profiles:
    active: @profiles.active@
  cloud:
    nacos:
      server-addr: @nacos.server-addr@
      username: @nacos.username@
      password: @nacos.password@
      discovery:
        group: @nacos.discovery.group@
        namespace: @nacos.discovery.namespace@
#        ephemeral: false # false 永久实例，true 临时实例
      config:
        group: @nacos.config.group@
        namespace: @nacos.config.namespace@
  config:
    import:
      - optional:nacos:astro-code-common.yaml
      - optional:nacos:${spring.application.name}.yaml

logging:
  level:
    org.dromara.trans.service.impl.SimpleTransService: ERROR

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus  # 暴露 prometheus 端点
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: my-springboot-app  # 可选：给所有指标加标签