"""
Generated by HEI code generator.
Author: codegen_script
Generated at: 2026-07-24 10:52:12
"""

from datetime import datetime
from typing import Any

from sqlalchemy import JSON, Boolean, DateTime, Float, Integer, Numeric, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.platform.db.base import Base
from app.platform.db.mixins import TimestampMixin
from app.platform.id_generator.snowflake import generate_snowflake_id


class MsgFriend(Base, TimestampMixin):
    __tablename__ = "msg_friend"

    id: Mapped[str] = mapped_column(String(64), primary_key=True, nullable=False, default=generate_snowflake_id, comment="主键")
    account_type: Mapped[str] = mapped_column(String(32), nullable=False, comment="账户类型")
    account_id: Mapped[str] = mapped_column(String(64), nullable=False, comment="账户ID")
    friend_account_type: Mapped[str] = mapped_column(String(32), nullable=False, comment="好友账户类型")
    friend_account_id: Mapped[str] = mapped_column(String(64), nullable=False, comment="好友账户ID")
    remark: Mapped[str | None] = mapped_column(String(64), comment="备注名")
    status: Mapped[str] = mapped_column(String(32), nullable=False, comment="状态")
    friend_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, comment="成为好友时间")
