"""
Generated by HEI code generator.
Author: codegen_script
Generated at: 2026-07-24 10:52:12
"""

from sqlalchemy.ext.asyncio import AsyncSession

from app.core.response.pagination import PageData, build_page
from app.core.schema.base import IdQuery, IdsRequest, to_schema, to_schema_list
from app.platform.db.transaction import transactional
from app.modules.message.friend.repository import (
    MsgFriendRepository,
)
from app.modules.message.friend.schema import (
    MsgFriendAdminPageQuery,
    MsgFriendCreateRequest,
    MsgFriendSchema,
    MsgFriendUpdateRequest,
)


class MsgFriendService:
    def __init__(self, db: AsyncSession):
        self.db = db
        self.repo = MsgFriendRepository(db)

    async def create(self, payload: MsgFriendCreateRequest) -> None:
        async with transactional(self.db):
            await self.repo.create(payload)

    async def update(self, payload: MsgFriendUpdateRequest) -> None:
        async with transactional(self.db):
            await self.repo.update(payload)

    async def delete(self, payload: IdsRequest) -> None:
        async with transactional(self.db):
            await self.repo.delete_many(payload.ids)

    async def detail(self, query: IdQuery) -> MsgFriendSchema:
        return to_schema(MsgFriendSchema, await self.repo.get_required(query.id))

    async def page_admin(self, query: MsgFriendAdminPageQuery) -> PageData[MsgFriendSchema]:
        items, total = await self.repo.page_admin(query)
        return build_page(query.pagination, total, to_schema_list(MsgFriendSchema, items))
