// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"hei-gin/ent/clientuser"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ClientUserCreate is the builder for creating a ClientUser entity.
type ClientUserCreate struct {
	config
	mutation *ClientUserMutation
	hooks    []Hook
}

// SetUsername sets the "username" field.
func (_c *ClientUserCreate) SetUsername(v string) *ClientUserCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetPassword sets the "password" field.
func (_c *ClientUserCreate) SetPassword(v string) *ClientUserCreate {
	_c.mutation.SetPassword(v)
	return _c
}

// SetNickname sets the "nickname" field.
func (_c *ClientUserCreate) SetNickname(v string) *ClientUserCreate {
	_c.mutation.SetNickname(v)
	return _c
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (_c *ClientUserCreate) SetNillableNickname(v *string) *ClientUserCreate {
	if v != nil {
		_c.SetNickname(*v)
	}
	return _c
}

// SetAvatar sets the "avatar" field.
func (_c *ClientUserCreate) SetAvatar(v string) *ClientUserCreate {
	_c.mutation.SetAvatar(v)
	return _c
}

// SetNillableAvatar sets the "avatar" field if the given value is not nil.
func (_c *ClientUserCreate) SetNillableAvatar(v *string) *ClientUserCreate {
	if v != nil {
		_c.SetAvatar(*v)
	}
	return _c
}

// SetEmail sets the "email" field.
func (_c *ClientUserCreate) SetEmail(v string) *ClientUserCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_c *ClientUserCreate) SetNillableEmail(v *string) *ClientUserCreate {
	if v != nil {
		_c.SetEmail(*v)
	}
	return _c
}

// SetPhone sets the "phone" field.
func (_c *ClientUserCreate) SetPhone(v string) *ClientUserCreate {
	_c.mutation.SetPhone(v)
	return _c
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_c *ClientUserCreate) SetNillablePhone(v *string) *ClientUserCreate {
	if v != nil {
		_c.SetPhone(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ClientUserCreate) SetStatus(v string) *ClientUserCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ClientUserCreate) SetNillableStatus(v *string) *ClientUserCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetGender sets the "gender" field.
func (_c *ClientUserCreate) SetGender(v string) *ClientUserCreate {
	_c.mutation.SetGender(v)
	return _c
}

// SetNillableGender sets the "gender" field if the given value is not nil.
func (_c *ClientUserCreate) SetNillableGender(v *string) *ClientUserCreate {
	if v != nil {
		_c.SetGender(*v)
	}
	return _c
}

// SetBirthday sets the "birthday" field.
func (_c *ClientUserCreate) SetBirthday(v time.Time) *ClientUserCreate {
	_c.mutation.SetBirthday(v)
	return _c
}

// SetNillableBirthday sets the "birthday" field if the given value is not nil.
func (_c *ClientUserCreate) SetNillableBirthday(v *time.Time) *ClientUserCreate {
	if v != nil {
		_c.SetBirthday(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *ClientUserCreate) SetDescription(v string) *ClientUserCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ClientUserCreate) SetNillableDescription(v *string) *ClientUserCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ClientUserCreate) SetCreatedAt(v time.Time) *ClientUserCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ClientUserCreate) SetNillableCreatedAt(v *time.Time) *ClientUserCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *ClientUserCreate) SetCreatedBy(v string) *ClientUserCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *ClientUserCreate) SetNillableCreatedBy(v *string) *ClientUserCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ClientUserCreate) SetUpdatedAt(v time.Time) *ClientUserCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ClientUserCreate) SetNillableUpdatedAt(v *time.Time) *ClientUserCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *ClientUserCreate) SetUpdatedBy(v string) *ClientUserCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *ClientUserCreate) SetNillableUpdatedBy(v *string) *ClientUserCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ClientUserCreate) SetID(v string) *ClientUserCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ClientUserMutation object of the builder.
func (_c *ClientUserCreate) Mutation() *ClientUserMutation {
	return _c.mutation
}

// Save creates the ClientUser in the database.
func (_c *ClientUserCreate) Save(ctx context.Context) (*ClientUser, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ClientUserCreate) SaveX(ctx context.Context) *ClientUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ClientUserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ClientUserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ClientUserCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := clientuser.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Gender(); !ok {
		v := clientuser.DefaultGender
		_c.mutation.SetGender(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ClientUserCreate) check() error {
	if _, ok := _c.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "ClientUser.username"`)}
	}
	if v, ok := _c.mutation.Username(); ok {
		if err := clientuser.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "ClientUser.username": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Password(); !ok {
		return &ValidationError{Name: "password", err: errors.New(`ent: missing required field "ClientUser.password"`)}
	}
	if v, ok := _c.mutation.Password(); ok {
		if err := clientuser.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "ClientUser.password": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Nickname(); ok {
		if err := clientuser.NicknameValidator(v); err != nil {
			return &ValidationError{Name: "nickname", err: fmt.Errorf(`ent: validator failed for field "ClientUser.nickname": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Avatar(); ok {
		if err := clientuser.AvatarValidator(v); err != nil {
			return &ValidationError{Name: "avatar", err: fmt.Errorf(`ent: validator failed for field "ClientUser.avatar": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := clientuser.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "ClientUser.email": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Phone(); ok {
		if err := clientuser.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "ClientUser.phone": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := clientuser.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ClientUser.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Gender(); ok {
		if err := clientuser.GenderValidator(v); err != nil {
			return &ValidationError{Name: "gender", err: fmt.Errorf(`ent: validator failed for field "ClientUser.gender": %w`, err)}
		}
	}
	if v, ok := _c.mutation.CreatedBy(); ok {
		if err := clientuser.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "ClientUser.created_by": %w`, err)}
		}
	}
	if v, ok := _c.mutation.UpdatedBy(); ok {
		if err := clientuser.UpdatedByValidator(v); err != nil {
			return &ValidationError{Name: "updated_by", err: fmt.Errorf(`ent: validator failed for field "ClientUser.updated_by": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := clientuser.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "ClientUser.id": %w`, err)}
		}
	}
	return nil
}

func (_c *ClientUserCreate) sqlSave(ctx context.Context) (*ClientUser, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ClientUser.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ClientUserCreate) createSpec() (*ClientUser, *sqlgraph.CreateSpec) {
	var (
		_node = &ClientUser{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(clientuser.Table, sqlgraph.NewFieldSpec(clientuser.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(clientuser.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.Password(); ok {
		_spec.SetField(clientuser.FieldPassword, field.TypeString, value)
		_node.Password = value
	}
	if value, ok := _c.mutation.Nickname(); ok {
		_spec.SetField(clientuser.FieldNickname, field.TypeString, value)
		_node.Nickname = value
	}
	if value, ok := _c.mutation.Avatar(); ok {
		_spec.SetField(clientuser.FieldAvatar, field.TypeString, value)
		_node.Avatar = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(clientuser.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.Phone(); ok {
		_spec.SetField(clientuser.FieldPhone, field.TypeString, value)
		_node.Phone = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(clientuser.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Gender(); ok {
		_spec.SetField(clientuser.FieldGender, field.TypeString, value)
		_node.Gender = value
	}
	if value, ok := _c.mutation.Birthday(); ok {
		_spec.SetField(clientuser.FieldBirthday, field.TypeTime, value)
		_node.Birthday = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(clientuser.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(clientuser.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(clientuser.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(clientuser.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(clientuser.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	return _node, _spec
}

// ClientUserCreateBulk is the builder for creating many ClientUser entities in bulk.
type ClientUserCreateBulk struct {
	config
	err      error
	builders []*ClientUserCreate
}

// Save creates the ClientUser entities in the database.
func (_c *ClientUserCreateBulk) Save(ctx context.Context) ([]*ClientUser, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ClientUser, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ClientUserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ClientUserCreateBulk) SaveX(ctx context.Context) []*ClientUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ClientUserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ClientUserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
