// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"hei-gin/ent/relorgrole"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// RelOrgRole is the model entity for the RelOrgRole schema.
type RelOrgRole struct {
	config `json:"-"`
	// ID of the ent.
	// 主键
	ID string `json:"id,omitempty"`
	// 组织ID
	OrgID string `json:"org_id,omitempty"`
	// 角色ID
	RoleID string `json:"role_id,omitempty"`
	// 数据范围
	Scope string `json:"scope,omitempty"`
	// 自定义分组IDs
	CustomScopeGroupIds string `json:"custom_scope_group_ids,omitempty"`
	selectValues        sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RelOrgRole) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case relorgrole.FieldID, relorgrole.FieldOrgID, relorgrole.FieldRoleID, relorgrole.FieldScope, relorgrole.FieldCustomScopeGroupIds:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RelOrgRole fields.
func (_m *RelOrgRole) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case relorgrole.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case relorgrole.FieldOrgID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field org_id", values[i])
			} else if value.Valid {
				_m.OrgID = value.String
			}
		case relorgrole.FieldRoleID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role_id", values[i])
			} else if value.Valid {
				_m.RoleID = value.String
			}
		case relorgrole.FieldScope:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scope", values[i])
			} else if value.Valid {
				_m.Scope = value.String
			}
		case relorgrole.FieldCustomScopeGroupIds:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field custom_scope_group_ids", values[i])
			} else if value.Valid {
				_m.CustomScopeGroupIds = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RelOrgRole.
// This includes values selected through modifiers, order, etc.
func (_m *RelOrgRole) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this RelOrgRole.
// Note that you need to call RelOrgRole.Unwrap() before calling this method if this RelOrgRole
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RelOrgRole) Update() *RelOrgRoleUpdateOne {
	return NewRelOrgRoleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RelOrgRole entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RelOrgRole) Unwrap() *RelOrgRole {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RelOrgRole is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RelOrgRole) String() string {
	var builder strings.Builder
	builder.WriteString("RelOrgRole(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("org_id=")
	builder.WriteString(_m.OrgID)
	builder.WriteString(", ")
	builder.WriteString("role_id=")
	builder.WriteString(_m.RoleID)
	builder.WriteString(", ")
	builder.WriteString("scope=")
	builder.WriteString(_m.Scope)
	builder.WriteString(", ")
	builder.WriteString("custom_scope_group_ids=")
	builder.WriteString(_m.CustomScopeGroupIds)
	builder.WriteByte(')')
	return builder.String()
}

// RelOrgRoles is a parsable slice of RelOrgRole.
type RelOrgRoles []*RelOrgRole
