// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"hei-gin/ent/sysdictdata"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// SysDictData is the model entity for the SysDictData schema.
type SysDictData struct {
	config `json:"-"`
	// ID of the ent.
	// 主键
	ID string `json:"id,omitempty"`
	// 字典ID
	DictID string `json:"dict_id,omitempty"`
	// 数据标签
	Label string `json:"label,omitempty"`
	// 数据值
	Value string `json:"value,omitempty"`
	// 颜色
	Color string `json:"color,omitempty"`
	// 排序
	SortCode int `json:"sort_code,omitempty"`
	// 状态
	Status string `json:"status,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 创建用户
	CreatedBy string `json:"created_by,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 更新用户
	UpdatedBy    string `json:"updated_by,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SysDictData) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sysdictdata.FieldSortCode:
			values[i] = new(sql.NullInt64)
		case sysdictdata.FieldID, sysdictdata.FieldDictID, sysdictdata.FieldLabel, sysdictdata.FieldValue, sysdictdata.FieldColor, sysdictdata.FieldStatus, sysdictdata.FieldCreatedBy, sysdictdata.FieldUpdatedBy:
			values[i] = new(sql.NullString)
		case sysdictdata.FieldCreatedAt, sysdictdata.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SysDictData fields.
func (_m *SysDictData) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sysdictdata.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case sysdictdata.FieldDictID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field dict_id", values[i])
			} else if value.Valid {
				_m.DictID = value.String
			}
		case sysdictdata.FieldLabel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field label", values[i])
			} else if value.Valid {
				_m.Label = value.String
			}
		case sysdictdata.FieldValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value.Valid {
				_m.Value = value.String
			}
		case sysdictdata.FieldColor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field color", values[i])
			} else if value.Valid {
				_m.Color = value.String
			}
		case sysdictdata.FieldSortCode:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_code", values[i])
			} else if value.Valid {
				_m.SortCode = int(value.Int64)
			}
		case sysdictdata.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case sysdictdata.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case sysdictdata.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.String
			}
		case sysdictdata.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case sysdictdata.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// GetValue returns the ent.Value that was dynamically selected and assigned to the SysDictData.
// This includes values selected through modifiers, order, etc.
func (_m *SysDictData) GetValue(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SysDictData.
// Note that you need to call SysDictData.Unwrap() before calling this method if this SysDictData
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SysDictData) Update() *SysDictDataUpdateOne {
	return NewSysDictDataClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SysDictData entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SysDictData) Unwrap() *SysDictData {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SysDictData is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SysDictData) String() string {
	var builder strings.Builder
	builder.WriteString("SysDictData(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("dict_id=")
	builder.WriteString(_m.DictID)
	builder.WriteString(", ")
	builder.WriteString("label=")
	builder.WriteString(_m.Label)
	builder.WriteString(", ")
	builder.WriteString("value=")
	builder.WriteString(_m.Value)
	builder.WriteString(", ")
	builder.WriteString("color=")
	builder.WriteString(_m.Color)
	builder.WriteString(", ")
	builder.WriteString("sort_code=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortCode))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(_m.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(_m.UpdatedBy)
	builder.WriteByte(')')
	return builder.String()
}

// SysDictDataSlice is a parsable slice of SysDictData.
type SysDictDataSlice []*SysDictData
