// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"hei-gin/ent/sysgroup"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SysGroupCreate is the builder for creating a SysGroup entity.
type SysGroupCreate struct {
	config
	mutation *SysGroupMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *SysGroupCreate) SetName(v string) *SysGroupCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetCode sets the "code" field.
func (_c *SysGroupCreate) SetCode(v string) *SysGroupCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetParentID sets the "parent_id" field.
func (_c *SysGroupCreate) SetParentID(v string) *SysGroupCreate {
	_c.mutation.SetParentID(v)
	return _c
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_c *SysGroupCreate) SetNillableParentID(v *string) *SysGroupCreate {
	if v != nil {
		_c.SetParentID(*v)
	}
	return _c
}

// SetHierarchy sets the "hierarchy" field.
func (_c *SysGroupCreate) SetHierarchy(v string) *SysGroupCreate {
	_c.mutation.SetHierarchy(v)
	return _c
}

// SetNillableHierarchy sets the "hierarchy" field if the given value is not nil.
func (_c *SysGroupCreate) SetNillableHierarchy(v *string) *SysGroupCreate {
	if v != nil {
		_c.SetHierarchy(*v)
	}
	return _c
}

// SetSortCode sets the "sort_code" field.
func (_c *SysGroupCreate) SetSortCode(v int) *SysGroupCreate {
	_c.mutation.SetSortCode(v)
	return _c
}

// SetNillableSortCode sets the "sort_code" field if the given value is not nil.
func (_c *SysGroupCreate) SetNillableSortCode(v *int) *SysGroupCreate {
	if v != nil {
		_c.SetSortCode(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *SysGroupCreate) SetStatus(v string) *SysGroupCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SysGroupCreate) SetNillableStatus(v *string) *SysGroupCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *SysGroupCreate) SetDescription(v string) *SysGroupCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *SysGroupCreate) SetNillableDescription(v *string) *SysGroupCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SysGroupCreate) SetCreatedAt(v time.Time) *SysGroupCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SysGroupCreate) SetNillableCreatedAt(v *time.Time) *SysGroupCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *SysGroupCreate) SetCreatedBy(v string) *SysGroupCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *SysGroupCreate) SetNillableCreatedBy(v *string) *SysGroupCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SysGroupCreate) SetUpdatedAt(v time.Time) *SysGroupCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SysGroupCreate) SetNillableUpdatedAt(v *time.Time) *SysGroupCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *SysGroupCreate) SetUpdatedBy(v string) *SysGroupCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *SysGroupCreate) SetNillableUpdatedBy(v *string) *SysGroupCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SysGroupCreate) SetID(v string) *SysGroupCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the SysGroupMutation object of the builder.
func (_c *SysGroupCreate) Mutation() *SysGroupMutation {
	return _c.mutation
}

// Save creates the SysGroup in the database.
func (_c *SysGroupCreate) Save(ctx context.Context) (*SysGroup, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SysGroupCreate) SaveX(ctx context.Context) *SysGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SysGroupCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SysGroupCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SysGroupCreate) defaults() {
	if _, ok := _c.mutation.SortCode(); !ok {
		v := sysgroup.DefaultSortCode
		_c.mutation.SetSortCode(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := sysgroup.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SysGroupCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "SysGroup.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := sysgroup.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SysGroup.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "SysGroup.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := sysgroup.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "SysGroup.code": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ParentID(); ok {
		if err := sysgroup.ParentIDValidator(v); err != nil {
			return &ValidationError{Name: "parent_id", err: fmt.Errorf(`ent: validator failed for field "SysGroup.parent_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Hierarchy(); ok {
		if err := sysgroup.HierarchyValidator(v); err != nil {
			return &ValidationError{Name: "hierarchy", err: fmt.Errorf(`ent: validator failed for field "SysGroup.hierarchy": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := sysgroup.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SysGroup.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.CreatedBy(); ok {
		if err := sysgroup.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "SysGroup.created_by": %w`, err)}
		}
	}
	if v, ok := _c.mutation.UpdatedBy(); ok {
		if err := sysgroup.UpdatedByValidator(v); err != nil {
			return &ValidationError{Name: "updated_by", err: fmt.Errorf(`ent: validator failed for field "SysGroup.updated_by": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := sysgroup.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "SysGroup.id": %w`, err)}
		}
	}
	return nil
}

func (_c *SysGroupCreate) sqlSave(ctx context.Context) (*SysGroup, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected SysGroup.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SysGroupCreate) createSpec() (*SysGroup, *sqlgraph.CreateSpec) {
	var (
		_node = &SysGroup{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sysgroup.Table, sqlgraph.NewFieldSpec(sysgroup.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(sysgroup.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(sysgroup.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.ParentID(); ok {
		_spec.SetField(sysgroup.FieldParentID, field.TypeString, value)
		_node.ParentID = value
	}
	if value, ok := _c.mutation.Hierarchy(); ok {
		_spec.SetField(sysgroup.FieldHierarchy, field.TypeString, value)
		_node.Hierarchy = value
	}
	if value, ok := _c.mutation.SortCode(); ok {
		_spec.SetField(sysgroup.FieldSortCode, field.TypeInt, value)
		_node.SortCode = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(sysgroup.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(sysgroup.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(sysgroup.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(sysgroup.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(sysgroup.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(sysgroup.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	return _node, _spec
}

// SysGroupCreateBulk is the builder for creating many SysGroup entities in bulk.
type SysGroupCreateBulk struct {
	config
	err      error
	builders []*SysGroupCreate
}

// Save creates the SysGroup entities in the database.
func (_c *SysGroupCreateBulk) Save(ctx context.Context) ([]*SysGroup, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SysGroup, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SysGroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SysGroupCreateBulk) SaveX(ctx context.Context) []*SysGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SysGroupCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SysGroupCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
