// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"hei-gin/ent/predicate"
	"hei-gin/ent/syslog"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SysLogDelete is the builder for deleting a SysLog entity.
type SysLogDelete struct {
	config
	hooks    []Hook
	mutation *SysLogMutation
}

// Where appends a list predicates to the SysLogDelete builder.
func (_d *SysLogDelete) Where(ps ...predicate.SysLog) *SysLogDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SysLogDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SysLogDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SysLogDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(syslog.Table, sqlgraph.NewFieldSpec(syslog.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SysLogDeleteOne is the builder for deleting a single SysLog entity.
type SysLogDeleteOne struct {
	_d *SysLogDelete
}

// Where appends a list predicates to the SysLogDelete builder.
func (_d *SysLogDeleteOne) Where(ps ...predicate.SysLog) *SysLogDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SysLogDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{syslog.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SysLogDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
