// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"hei-gin/ent/predicate"
	"hei-gin/ent/syspermission"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SysPermissionDelete is the builder for deleting a SysPermission entity.
type SysPermissionDelete struct {
	config
	hooks    []Hook
	mutation *SysPermissionMutation
}

// Where appends a list predicates to the SysPermissionDelete builder.
func (_d *SysPermissionDelete) Where(ps ...predicate.SysPermission) *SysPermissionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SysPermissionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SysPermissionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SysPermissionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(syspermission.Table, sqlgraph.NewFieldSpec(syspermission.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SysPermissionDeleteOne is the builder for deleting a single SysPermission entity.
type SysPermissionDeleteOne struct {
	_d *SysPermissionDelete
}

// Where appends a list predicates to the SysPermissionDelete builder.
func (_d *SysPermissionDeleteOne) Where(ps ...predicate.SysPermission) *SysPermissionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SysPermissionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{syspermission.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SysPermissionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
