// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"hei-gin/ent/sysrole"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// SysRole is the model entity for the SysRole schema.
type SysRole struct {
	config `json:"-"`
	// ID of the ent.
	// 主键
	ID string `json:"id,omitempty"`
	// 角色名称
	Name string `json:"name,omitempty"`
	// 角色编码
	Code string `json:"code,omitempty"`
	// 数据权限范围
	DataScope string `json:"data_scope,omitempty"`
	// 自定义组织权限IDs
	CustomScopeOrgIds string `json:"custom_scope_org_ids,omitempty"`
	// 自定义分组权限IDs
	CustomScopeGroupIds string `json:"custom_scope_group_ids,omitempty"`
	// 排序
	SortCode int `json:"sort_code,omitempty"`
	// 状态
	Status string `json:"status,omitempty"`
	// 角色描述
	Description string `json:"description,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 创建用户
	CreatedBy string `json:"created_by,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 更新用户
	UpdatedBy    string `json:"updated_by,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SysRole) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sysrole.FieldSortCode:
			values[i] = new(sql.NullInt64)
		case sysrole.FieldID, sysrole.FieldName, sysrole.FieldCode, sysrole.FieldDataScope, sysrole.FieldCustomScopeOrgIds, sysrole.FieldCustomScopeGroupIds, sysrole.FieldStatus, sysrole.FieldDescription, sysrole.FieldCreatedBy, sysrole.FieldUpdatedBy:
			values[i] = new(sql.NullString)
		case sysrole.FieldCreatedAt, sysrole.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SysRole fields.
func (_m *SysRole) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sysrole.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case sysrole.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case sysrole.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case sysrole.FieldDataScope:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field data_scope", values[i])
			} else if value.Valid {
				_m.DataScope = value.String
			}
		case sysrole.FieldCustomScopeOrgIds:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field custom_scope_org_ids", values[i])
			} else if value.Valid {
				_m.CustomScopeOrgIds = value.String
			}
		case sysrole.FieldCustomScopeGroupIds:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field custom_scope_group_ids", values[i])
			} else if value.Valid {
				_m.CustomScopeGroupIds = value.String
			}
		case sysrole.FieldSortCode:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_code", values[i])
			} else if value.Valid {
				_m.SortCode = int(value.Int64)
			}
		case sysrole.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case sysrole.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case sysrole.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case sysrole.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.String
			}
		case sysrole.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case sysrole.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SysRole.
// This includes values selected through modifiers, order, etc.
func (_m *SysRole) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SysRole.
// Note that you need to call SysRole.Unwrap() before calling this method if this SysRole
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SysRole) Update() *SysRoleUpdateOne {
	return NewSysRoleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SysRole entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SysRole) Unwrap() *SysRole {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SysRole is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SysRole) String() string {
	var builder strings.Builder
	builder.WriteString("SysRole(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("data_scope=")
	builder.WriteString(_m.DataScope)
	builder.WriteString(", ")
	builder.WriteString("custom_scope_org_ids=")
	builder.WriteString(_m.CustomScopeOrgIds)
	builder.WriteString(", ")
	builder.WriteString("custom_scope_group_ids=")
	builder.WriteString(_m.CustomScopeGroupIds)
	builder.WriteString(", ")
	builder.WriteString("sort_code=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortCode))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(_m.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(_m.UpdatedBy)
	builder.WriteByte(')')
	return builder.String()
}

// SysRoles is a parsable slice of SysRole.
type SysRoles []*SysRole
