"""
Generated by HEI code generator.
Author: Charlie
Generated at: 2026-07-28 20:51:10
"""

from datetime import datetime
from typing import Any

from pydantic import Field

from app.core.response.pagination import PageQuery
from app.core.schema.base import ApiSchema
from app.modules.biz.problem.enums import ProblemDifficulty, ProblemStatus, SubmissionSourceVisibility


class OjProblemTrialJudgeRequest(ApiSchema):
    problem_id: str = Field(min_length=1, max_length=64)
    language_key: str = Field(min_length=1, max_length=32)
    source: str = Field(min_length=1)
    case_ids: list[str] | None = None
    wait_timeout_sec: int = Field(default=60, ge=5, le=300)
    # False: enqueue and return immediately (SSE/poll for result). True: poll DB until terminal.
    wait: bool = False


class OjProblemTrialJudgeResult(ApiSchema):
    submission_id: str
    status: str
    result: str | None = None
    score: float = 0
    time_ms: int = 0
    memory_kb: int = 0
    compile_output: str | None = None
    compile_error: bool = False
    cases: list[dict[str, Any]] = Field(default_factory=list)
    error: str | None = None
    wall_time_ms: int = 0


class OjProblemCreateRequest(ApiSchema):
    code: str
    name: str
    description: str
    summary: str | None = None
    group_id: str | None = None
    time_limit_ms: int
    memory_limit_kb: int
    points: float
    partial: bool
    status: ProblemStatus = ProblemStatus.DRAFT
    is_public: bool = False
    published_at: datetime | None = None
    submission_source_visibility: SubmissionSourceVisibility
    difficulty: ProblemDifficulty = ProblemDifficulty.MEDIUM
    type_ids: list[str] = Field(default_factory=list)
    extra: dict[str, Any] | None = Field(default_factory=dict)


class OjProblemUpdateRequest(OjProblemCreateRequest):
    id: str = Field(min_length=1, max_length=64)


class OjProblemStatusRequest(ApiSchema):
    id: str = Field(min_length=1, max_length=64)
    status: ProblemStatus


class OjProblemAdminPageQuery(PageQuery):
    code: str | None = None
    name: str | None = None
    group_id: str | None = None
    type_id: str | None = None
    status: ProblemStatus | None = None
    is_public: bool | None = None


class OjProblemSchema(ApiSchema):
    id: str
    code: str
    name: str
    description: str
    summary: str | None = None
    group_id: str | None = None
    group_name: str | None = None
    time_limit_ms: int
    memory_limit_kb: int
    points: float
    partial: bool
    status: ProblemStatus
    is_public: bool = False
    published_at: datetime | None = None
    submission_source_visibility: SubmissionSourceVisibility
    difficulty: ProblemDifficulty = ProblemDifficulty.MEDIUM
    user_count: int
    ac_rate: float
    type_ids: list[str] = Field(default_factory=list)
    type_names: list[str] = Field(default_factory=list)
    extra: dict[str, Any] | None = Field(default_factory=dict)
    created_at: datetime
    created_by: str | None = None
    updated_at: datetime
    updated_by: str | None = None
