const LANGUAGE_MAP: Record<string, string> = {
  c: 'c',
  c11: 'c',
  c17: 'c',
  cpp: 'cpp',
  cpp11: 'cpp',
  cpp14: 'cpp',
  cpp17: 'cpp',
  cpp20: 'cpp',
  cpp23: 'cpp',
  python: 'python',
  python2: 'python',
  python3: 'python',
  py: 'python',
  py3: 'python',
  pypy3: 'python',
  java: 'java',
  java8: 'java',
  java11: 'java',
  java17: 'java',
  go: 'go',
  golang: 'go',
  rust: 'rust',
  rs: 'rust',
  js: 'javascript',
  javascript: 'javascript',
  node: 'javascript',
  nodejs: 'javascript',
  ts: 'typescript',
  typescript: 'typescript',
  kotlin: 'kotlin',
  swift: 'swift',
  php: 'php',
  ruby: 'ruby',
  perl: 'perl',
  haskell: 'haskell',
  lua: 'lua',
  r: 'r',
  sql: 'sql',
  shell: 'shell',
  bash: 'shell',
  sh: 'shell',
  csharp: 'csharp',
  cs: 'csharp',
  objc: 'objective-c',
}

export function monacoLanguage(languageKey: string) {
  return LANGUAGE_MAP[(languageKey || '').toLowerCase()] ?? 'plaintext'
}

export function languageLabel(languageKey: string) {
  const map: Record<string, string> = {
    c: 'C',
    c11: 'C11',
    c17: 'C17',
    cpp: 'C++',
    cpp11: 'C++11',
    cpp14: 'C++14',
    cpp17: 'C++17',
    cpp20: 'C++20',
    cpp23: 'C++23',
    python: 'Python',
    python2: 'Python 2',
    python3: 'Python 3',
    py: 'Python',
    py3: 'Python 3',
    pypy3: 'PyPy 3',
    java: 'Java',
    java8: 'Java 8',
    java11: 'Java 11',
    java17: 'Java 17',
    go: 'Go',
    golang: 'Go',
    rust: 'Rust',
    js: 'JavaScript',
    javascript: 'JavaScript',
    node: 'Node.js',
    ts: 'TypeScript',
    typescript: 'TypeScript',
    kotlin: 'Kotlin',
    swift: 'Swift',
    php: 'PHP',
    ruby: 'Ruby',
    csharp: 'C#',
    cs: 'C#',
  }
  return map[(languageKey || '').toLowerCase()] ?? languageKey
}
