BEGIN;

INSERT INTO public.sys_resource (
    id, parent_id, code, name, resource_type, module_id, path, component, redirect, icon, color, href, sort,
    is_visible, is_cache, is_affix, status, description, extra, created_at, created_by, updated_at, updated_by
) VALUES
    ('5202000', NULL, 'oj', '在线判题', 'CATALOG', '210001', '/oj', NULL, NULL, 'icon-park-outline:code-computer', NULL, NULL, 20, true, false, false, 'ENABLED', '在线判题管理目录', '{}'::json, now(), NULL, now(), NULL),
    ('5202001', '5202000', 'oj-problem', '题目管理', 'MENU', '210001', '/oj/problem', '/oj/problem/index.vue', NULL, 'icon-park-outline:book-open', NULL, NULL, 1, true, true, false, 'ENABLED', '题目聚合维护', '{}'::json, now(), NULL, now(), NULL),
    ('5202002', '5202000', 'oj-contest', '竞赛管理', 'MENU', '210001', '/oj/contest', '/oj/contest/index.vue', NULL, 'icon-park-outline:trophy', NULL, NULL, 2, true, true, false, 'ENABLED', '竞赛聚合维护', '{}'::json, now(), NULL, now(), NULL),
    ('5202003', '5202000', 'oj-submission', '提交记录', 'MENU', '210001', '/oj/submission', '/oj/submission/index.vue', NULL, 'icon-park-outline:send-email', NULL, NULL, 3, true, true, false, 'ENABLED', '提交记录查询', '{}'::json, now(), NULL, now(), NULL),
    ('5202004', '5202000', 'oj-judge', '判题管理', 'CATALOG', '210001', '/oj/judge', NULL, NULL, 'icon-park-outline:terminal', NULL, NULL, 4, true, false, false, 'ENABLED', '判题机与任务管理目录', '{}'::json, now(), NULL, now(), NULL),
    ('5202005', '5202004', 'oj-judge-task', '判题任务', 'MENU', '210001', '/oj/judge/task', '/oj/judge/task/index.vue', NULL, 'icon-park-outline:list-checkbox', NULL, NULL, 1, true, false, false, 'ENABLED', '判题任务管理', '{}'::json, now(), NULL, now(), NULL),
    ('5202006', '5202004', 'oj-judge-node', '判题节点', 'MENU', '210001', '/oj/judge/node', '/oj/judge/node/index.vue', NULL, 'icon-park-outline:server', NULL, NULL, 2, true, false, false, 'ENABLED', '判题节点管理', '{}'::json, now(), NULL, now(), NULL),
    ('5202007', '5202004', 'oj-language', '语言配置', 'MENU', '210001', '/oj/judge/language', '/oj/judge/language/index.vue', NULL, 'icon-park-outline:code', NULL, NULL, 3, true, false, false, 'ENABLED', '判题语言配置', '{}'::json, now(), NULL, now(), NULL),
    ('5202008', '5202004', 'oj-runtime-version', '运行时版本', 'MENU', '210001', '/oj/judge/runtime-version', '/oj/judge/runtime_version/index.vue', NULL, 'icon-park-outline:info', NULL, NULL, 4, true, false, false, 'ENABLED', '运行时版本管理', '{}'::json, now(), NULL, now(), NULL),
    ('5202101', '5202001', 'oj-problem-create', '新增题目', 'BUTTON', '210001', NULL, NULL, NULL, NULL, NULL, NULL, 1, true, false, false, 'ENABLED', NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5202102', '5202001', 'oj-problem-detail', '查看题目', 'BUTTON', '210001', NULL, NULL, NULL, NULL, NULL, NULL, 2, true, false, false, 'ENABLED', NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5202103', '5202001', 'oj-problem-update', '编辑题目', 'BUTTON', '210001', NULL, NULL, NULL, NULL, NULL, NULL, 3, true, false, false, 'ENABLED', NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5202104', '5202001', 'oj-problem-delete', '删除题目', 'BUTTON', '210001', NULL, NULL, NULL, NULL, NULL, NULL, 4, true, false, false, 'ENABLED', NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5202201', '5202002', 'oj-contest-create', '新增竞赛', 'BUTTON', '210001', NULL, NULL, NULL, NULL, NULL, NULL, 1, true, false, false, 'ENABLED', NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5202202', '5202002', 'oj-contest-detail', '查看竞赛', 'BUTTON', '210001', NULL, NULL, NULL, NULL, NULL, NULL, 2, true, false, false, 'ENABLED', NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5202203', '5202002', 'oj-contest-update', '编辑竞赛', 'BUTTON', '210001', NULL, NULL, NULL, NULL, NULL, NULL, 3, true, false, false, 'ENABLED', NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5202204', '5202002', 'oj-contest-delete', '删除竞赛', 'BUTTON', '210001', NULL, NULL, NULL, NULL, NULL, NULL, 4, true, false, false, 'ENABLED', NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5202301', '5202003', 'oj-submission-detail', '查看提交', 'BUTTON', '210001', NULL, NULL, NULL, NULL, NULL, NULL, 1, true, false, false, 'ENABLED', NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5202302', '5202003', 'oj-submission-delete', '删除提交', 'BUTTON', '210001', NULL, NULL, NULL, NULL, NULL, NULL, 2, true, false, false, 'ENABLED', NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5202501', '5202005', 'oj-judge-task-detail', '查看判题任务', 'BUTTON', '210001', NULL, NULL, NULL, NULL, NULL, NULL, 1, true, false, false, 'ENABLED', NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5202502', '5202005', 'oj-judge-task-delete', '删除判题任务', 'BUTTON', '210001', NULL, NULL, NULL, NULL, NULL, NULL, 2, true, false, false, 'ENABLED', NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5202601', '5202006', 'oj-judge-node-create', '新增判题节点', 'BUTTON', '210001', NULL, NULL, NULL, NULL, NULL, NULL, 1, true, false, false, 'ENABLED', NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5202602', '5202006', 'oj-judge-node-detail', '查看判题节点', 'BUTTON', '210001', NULL, NULL, NULL, NULL, NULL, NULL, 2, true, false, false, 'ENABLED', NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5202603', '5202006', 'oj-judge-node-update', '编辑判题节点', 'BUTTON', '210001', NULL, NULL, NULL, NULL, NULL, NULL, 3, true, false, false, 'ENABLED', NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5202604', '5202006', 'oj-judge-node-delete', '删除判题节点', 'BUTTON', '210001', NULL, NULL, NULL, NULL, NULL, NULL, 4, true, false, false, 'ENABLED', NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5202701', '5202007', 'oj-language-create', '新增语言', 'BUTTON', '210001', NULL, NULL, NULL, NULL, NULL, NULL, 1, true, false, false, 'ENABLED', NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5202702', '5202007', 'oj-language-detail', '查看语言', 'BUTTON', '210001', NULL, NULL, NULL, NULL, NULL, NULL, 2, true, false, false, 'ENABLED', NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5202703', '5202007', 'oj-language-update', '编辑语言', 'BUTTON', '210001', NULL, NULL, NULL, NULL, NULL, NULL, 3, true, false, false, 'ENABLED', NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5202704', '5202007', 'oj-language-delete', '删除语言', 'BUTTON', '210001', NULL, NULL, NULL, NULL, NULL, NULL, 4, true, false, false, 'ENABLED', NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5202801', '5202008', 'oj-runtime-version-create', '新增运行时版本', 'BUTTON', '210001', NULL, NULL, NULL, NULL, NULL, NULL, 1, true, false, false, 'ENABLED', NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5202802', '5202008', 'oj-runtime-version-detail', '查看运行时版本', 'BUTTON', '210001', NULL, NULL, NULL, NULL, NULL, NULL, 2, true, false, false, 'ENABLED', NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5202803', '5202008', 'oj-runtime-version-update', '编辑运行时版本', 'BUTTON', '210001', NULL, NULL, NULL, NULL, NULL, NULL, 3, true, false, false, 'ENABLED', NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5202804', '5202008', 'oj-runtime-version-delete', '删除运行时版本', 'BUTTON', '210001', NULL, NULL, NULL, NULL, NULL, NULL, 4, true, false, false, 'ENABLED', NULL, '{}'::json, now(), NULL, now(), NULL)
ON CONFLICT (id) DO UPDATE SET
    parent_id = EXCLUDED.parent_id,
    code = EXCLUDED.code,
    name = EXCLUDED.name,
    resource_type = EXCLUDED.resource_type,
    module_id = EXCLUDED.module_id,
    path = EXCLUDED.path,
    component = EXCLUDED.component,
    redirect = EXCLUDED.redirect,
    icon = EXCLUDED.icon,
    color = EXCLUDED.color,
    href = EXCLUDED.href,
    sort = EXCLUDED.sort,
    is_visible = EXCLUDED.is_visible,
    is_cache = EXCLUDED.is_cache,
    is_affix = EXCLUDED.is_affix,
    status = EXCLUDED.status,
    description = EXCLUDED.description,
    extra = EXCLUDED.extra,
    updated_at = now(),
    updated_by = EXCLUDED.updated_by;

INSERT INTO public.sys_iam_relation (
    id, subject_type, subject_id, relation_type, target_type, target_id, target_key, grant_mode,
    effect, data_scope, custom_scope_dept_ids, is_primary, sort, status, description, reason,
    expired_at, extra, created_at, created_by, updated_at, updated_by
) VALUES
    ('5402001', 'RESOURCE', '5202001', 'RESOURCE_PERMISSION', 'PERMISSION', '', 'oj:problems:page', 'CASCADE', 'ALLOW', 'ALL', '[]'::json, false, 1, 'ENABLED', '题目分页', NULL, NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5402101', 'RESOURCE', '5202101', 'RESOURCE_PERMISSION', 'PERMISSION', '', 'oj:problems:create', 'CASCADE', 'ALLOW', 'ALL', '[]'::json, false, 2, 'ENABLED', '新增题目', NULL, NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5402102', 'RESOURCE', '5202102', 'RESOURCE_PERMISSION', 'PERMISSION', '', 'oj:problems:detail', 'CASCADE', 'ALLOW', 'ALL', '[]'::json, false, 3, 'ENABLED', '查看题目', NULL, NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5402103', 'RESOURCE', '5202103', 'RESOURCE_PERMISSION', 'PERMISSION', '', 'oj:problems:update', 'CASCADE', 'ALLOW', 'ALL', '[]'::json, false, 4, 'ENABLED', '编辑题目', NULL, NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5402104', 'RESOURCE', '5202104', 'RESOURCE_PERMISSION', 'PERMISSION', '', 'oj:problems:delete', 'CASCADE', 'ALLOW', 'ALL', '[]'::json, false, 5, 'ENABLED', '删除题目', NULL, NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5402002', 'RESOURCE', '5202002', 'RESOURCE_PERMISSION', 'PERMISSION', '', 'oj:contests:page', 'CASCADE', 'ALLOW', 'ALL', '[]'::json, false, 10, 'ENABLED', '竞赛分页', NULL, NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5402201', 'RESOURCE', '5202201', 'RESOURCE_PERMISSION', 'PERMISSION', '', 'oj:contests:create', 'CASCADE', 'ALLOW', 'ALL', '[]'::json, false, 11, 'ENABLED', '新增竞赛', NULL, NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5402202', 'RESOURCE', '5202202', 'RESOURCE_PERMISSION', 'PERMISSION', '', 'oj:contests:detail', 'CASCADE', 'ALLOW', 'ALL', '[]'::json, false, 12, 'ENABLED', '查看竞赛', NULL, NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5402203', 'RESOURCE', '5202203', 'RESOURCE_PERMISSION', 'PERMISSION', '', 'oj:contests:update', 'CASCADE', 'ALLOW', 'ALL', '[]'::json, false, 13, 'ENABLED', '编辑竞赛', NULL, NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5402204', 'RESOURCE', '5202204', 'RESOURCE_PERMISSION', 'PERMISSION', '', 'oj:contests:delete', 'CASCADE', 'ALLOW', 'ALL', '[]'::json, false, 14, 'ENABLED', '删除竞赛', NULL, NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5402003', 'RESOURCE', '5202003', 'RESOURCE_PERMISSION', 'PERMISSION', '', 'oj:submissions:page', 'CASCADE', 'ALLOW', 'ALL', '[]'::json, false, 20, 'ENABLED', '提交分页', NULL, NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5402301', 'RESOURCE', '5202301', 'RESOURCE_PERMISSION', 'PERMISSION', '', 'oj:submissions:detail', 'CASCADE', 'ALLOW', 'ALL', '[]'::json, false, 21, 'ENABLED', '查看提交', NULL, NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5402302', 'RESOURCE', '5202302', 'RESOURCE_PERMISSION', 'PERMISSION', '', 'oj:submissions:delete', 'CASCADE', 'ALLOW', 'ALL', '[]'::json, false, 22, 'ENABLED', '删除提交', NULL, NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5402005', 'RESOURCE', '5202005', 'RESOURCE_PERMISSION', 'PERMISSION', '', 'oj:judgetasks:page', 'CASCADE', 'ALLOW', 'ALL', '[]'::json, false, 30, 'ENABLED', '判题任务分页', NULL, NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5402501', 'RESOURCE', '5202501', 'RESOURCE_PERMISSION', 'PERMISSION', '', 'oj:judgetasks:detail', 'CASCADE', 'ALLOW', 'ALL', '[]'::json, false, 31, 'ENABLED', '查看判题任务', NULL, NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5402502', 'RESOURCE', '5202502', 'RESOURCE_PERMISSION', 'PERMISSION', '', 'oj:judgetasks:delete', 'CASCADE', 'ALLOW', 'ALL', '[]'::json, false, 32, 'ENABLED', '删除判题任务', NULL, NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5402006', 'RESOURCE', '5202006', 'RESOURCE_PERMISSION', 'PERMISSION', '', 'oj:judgenodes:page', 'CASCADE', 'ALLOW', 'ALL', '[]'::json, false, 40, 'ENABLED', '判题节点分页', NULL, NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5402601', 'RESOURCE', '5202601', 'RESOURCE_PERMISSION', 'PERMISSION', '', 'oj:judgenodes:create', 'CASCADE', 'ALLOW', 'ALL', '[]'::json, false, 41, 'ENABLED', '新增判题节点', NULL, NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5402602', 'RESOURCE', '5202602', 'RESOURCE_PERMISSION', 'PERMISSION', '', 'oj:judgenodes:detail', 'CASCADE', 'ALLOW', 'ALL', '[]'::json, false, 42, 'ENABLED', '查看判题节点', NULL, NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5402603', 'RESOURCE', '5202603', 'RESOURCE_PERMISSION', 'PERMISSION', '', 'oj:judgenodes:update', 'CASCADE', 'ALLOW', 'ALL', '[]'::json, false, 43, 'ENABLED', '编辑判题节点', NULL, NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5402604', 'RESOURCE', '5202604', 'RESOURCE_PERMISSION', 'PERMISSION', '', 'oj:judgenodes:delete', 'CASCADE', 'ALLOW', 'ALL', '[]'::json, false, 44, 'ENABLED', '删除判题节点', NULL, NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5402007', 'RESOURCE', '5202007', 'RESOURCE_PERMISSION', 'PERMISSION', '', 'oj:languages:page', 'CASCADE', 'ALLOW', 'ALL', '[]'::json, false, 50, 'ENABLED', '语言分页', NULL, NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5402701', 'RESOURCE', '5202701', 'RESOURCE_PERMISSION', 'PERMISSION', '', 'oj:languages:create', 'CASCADE', 'ALLOW', 'ALL', '[]'::json, false, 51, 'ENABLED', '新增语言', NULL, NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5402702', 'RESOURCE', '5202702', 'RESOURCE_PERMISSION', 'PERMISSION', '', 'oj:languages:detail', 'CASCADE', 'ALLOW', 'ALL', '[]'::json, false, 52, 'ENABLED', '查看语言', NULL, NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5402703', 'RESOURCE', '5202703', 'RESOURCE_PERMISSION', 'PERMISSION', '', 'oj:languages:update', 'CASCADE', 'ALLOW', 'ALL', '[]'::json, false, 53, 'ENABLED', '编辑语言', NULL, NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5402704', 'RESOURCE', '5202704', 'RESOURCE_PERMISSION', 'PERMISSION', '', 'oj:languages:delete', 'CASCADE', 'ALLOW', 'ALL', '[]'::json, false, 54, 'ENABLED', '删除语言', NULL, NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5402008', 'RESOURCE', '5202008', 'RESOURCE_PERMISSION', 'PERMISSION', '', 'oj:runtimeversions:page', 'CASCADE', 'ALLOW', 'ALL', '[]'::json, false, 60, 'ENABLED', '运行时版本分页', NULL, NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5402801', 'RESOURCE', '5202801', 'RESOURCE_PERMISSION', 'PERMISSION', '', 'oj:runtimeversions:create', 'CASCADE', 'ALLOW', 'ALL', '[]'::json, false, 61, 'ENABLED', '新增运行时版本', NULL, NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5402802', 'RESOURCE', '5202802', 'RESOURCE_PERMISSION', 'PERMISSION', '', 'oj:runtimeversions:detail', 'CASCADE', 'ALLOW', 'ALL', '[]'::json, false, 62, 'ENABLED', '查看运行时版本', NULL, NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5402803', 'RESOURCE', '5202803', 'RESOURCE_PERMISSION', 'PERMISSION', '', 'oj:runtimeversions:update', 'CASCADE', 'ALLOW', 'ALL', '[]'::json, false, 63, 'ENABLED', '编辑运行时版本', NULL, NULL, '{}'::json, now(), NULL, now(), NULL),
    ('5402804', 'RESOURCE', '5202804', 'RESOURCE_PERMISSION', 'PERMISSION', '', 'oj:runtimeversions:delete', 'CASCADE', 'ALLOW', 'ALL', '[]'::json, false, 64, 'ENABLED', '删除运行时版本', NULL, NULL, '{}'::json, now(), NULL, now(), NULL)
ON CONFLICT ON CONSTRAINT uq_sys_iam_relation_subject_relation_target DO UPDATE SET
    target_key = EXCLUDED.target_key,
    grant_mode = EXCLUDED.grant_mode,
    effect = EXCLUDED.effect,
    data_scope = EXCLUDED.data_scope,
    custom_scope_dept_ids = EXCLUDED.custom_scope_dept_ids,
    is_primary = EXCLUDED.is_primary,
    sort = EXCLUDED.sort,
    status = EXCLUDED.status,
    description = EXCLUDED.description,
    extra = EXCLUDED.extra,
    updated_at = now(),
    updated_by = EXCLUDED.updated_by;

INSERT INTO public.sys_iam_relation (
    id, subject_type, subject_id, relation_type, target_type, target_id, target_key, grant_mode,
    effect, data_scope, custom_scope_dept_ids, is_primary, sort, status, description, reason,
    expired_at, extra, created_at, created_by, updated_at, updated_by
)
SELECT
    '5302' || lpad(row_number() OVER (ORDER BY resource.id)::text, 3, '0') AS id,
    'ROLE',
    '1',
    'SUBJECT_RESOURCE_GRANT',
    'RESOURCE',
    resource.id,
    '',
    'CASCADE',
    'ALLOW',
    'SELF',
    '[]'::json,
    false,
    99,
    'ENABLED',
    '超管角色默认资源授权',
    NULL,
    NULL,
    '{}'::json,
    now(),
    NULL,
    now(),
    NULL
FROM public.sys_resource resource
WHERE resource.id IN (
    '5202000', '5202001', '5202002', '5202003', '5202004', '5202005', '5202006', '5202007', '5202008',
    '5202101', '5202102', '5202103', '5202104',
    '5202201', '5202202', '5202203', '5202204',
    '5202301', '5202302',
    '5202501', '5202502',
    '5202601', '5202602', '5202603', '5202604',
    '5202701', '5202702', '5202703', '5202704',
    '5202801', '5202802', '5202803', '5202804'
)
ON CONFLICT ON CONSTRAINT uq_sys_iam_relation_subject_relation_target DO UPDATE SET
    grant_mode = EXCLUDED.grant_mode,
    effect = EXCLUDED.effect,
    data_scope = EXCLUDED.data_scope,
    custom_scope_dept_ids = EXCLUDED.custom_scope_dept_ids,
    is_primary = EXCLUDED.is_primary,
    sort = EXCLUDED.sort,
    status = EXCLUDED.status,
    description = EXCLUDED.description,
    extra = EXCLUDED.extra,
    updated_at = now(),
    updated_by = EXCLUDED.updated_by;

COMMIT;
