Name: similarity-service
Host: 0.0.0.0
Port: 8882

# MySQL 配置
MySQL:
  Host: mysql:3306
  Username: root
  Password: "infra@123"
  Database: astro_code
  Charset: utf8mb4
  ParseTime: true
  Loc: Local
  MaxIdleConns: 10
  MaxOpenConns: 100
  ConnMaxLifetime: "1h"

Redis:
  Host: "redis:6379"
  Password: "infra@123"   # 与 redis.conf 的 requirepass 一致
  DB: 0
  PoolSize: 10

# RabbitMQ 配置
RabbitMQ:
  Host: "amqp://admin:infra%40123@rabbitmq:5672/"
  VirtualHost: "/"
  Common:
    SimilarityExchange: "common.sim.exchange"
    SimilarityQueue: "common.sim.queue"
    SimilarityRoutingKey: "common.sim.routing"
    ResultExchange: "common.sim.result.exchange"
    ResultQueue: "common.sim.result.queue"
    ResultRoutingKey: "common.sim.result.routing"
