"""
Generated by HEI code generator.
Author: Charlie
Generated at: 2026-07-28 20:51:11
"""

from app.platform.module import ModuleSpec, RouteSpec

module = ModuleSpec(
    name="biz.problem.data",
    routes=(
        RouteSpec(
            version="v1",
            prefix="/admin",
            tags=("admin",),
            router="app.modules.biz.problem.data.router:router",
        ),
    ),
    order=224,
    depends_on=("biz.problem.problem",),
    models=("app.modules.biz.problem.data.model",),
)
