"""
Generated by HEI code generator.
Author: Charlie
Generated at: 2026-07-28 20:51:11
"""

from sqlalchemy import Select, delete, func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.exceptions.business import NotFoundError
from app.modules.biz.problem.data.model import (
    OjProblemData,
)
from app.modules.biz.problem.data.schema import (
    OjProblemDataAdminPageQuery,
    OjProblemDataCreateRequest,
    OjProblemDataUpdateRequest,
)


class OjProblemDataRepository:
    def __init__(self, db: AsyncSession):
        self.db = db

    async def create(self, payload: OjProblemDataCreateRequest) -> OjProblemData:
        entity = OjProblemData(**payload.model_dump())
        self.db.add(entity)
        await self.db.flush()
        return entity

    async def get_by_id(self, entity_id: str) -> OjProblemData | None:
        return await self.db.get(OjProblemData, entity_id)

    async def get_required(self, entity_id: str) -> OjProblemData:
        entity = await self.get_by_id(entity_id)
        if entity is None:
            raise NotFoundError("OjProblemData not found")
        return entity

    async def update(self, payload: OjProblemDataUpdateRequest) -> None:
        entity = await self.get_required(payload.id)
        for key, value in payload.model_dump(exclude={"id"}).items():
            setattr(entity, key, value)
        await self.db.flush()

    async def delete_many(self, entity_ids: list[str]) -> None:
        unique_ids = list(dict.fromkeys(entity_ids))
        stmt = select(OjProblemData.id).where(OjProblemData.id.in_(unique_ids))
        existing_ids = set((await self.db.execute(stmt)).scalars().all())
        if len(existing_ids) != len(unique_ids):
            raise NotFoundError("OjProblemData not found")
        await self.db.execute(delete(OjProblemData).where(OjProblemData.id.in_(unique_ids)))

    async def page_admin(self, query: OjProblemDataAdminPageQuery) -> tuple[list[OjProblemData], int]:
        stmt: Select[tuple[OjProblemData]] = select(OjProblemData)
        count_stmt = select(func.count(OjProblemData.id))
        filters = []
        if query.problem_id is not None:
            filters.append(OjProblemData.problem_id == query.problem_id)
        if query.zip_object_name is not None:
            filters.append(OjProblemData.zip_object_name == query.zip_object_name)
        if query.generator_file_id is not None:
            filters.append(OjProblemData.generator_file_id == query.generator_file_id)
        if filters:
            stmt = stmt.where(*filters)
            count_stmt = count_stmt.where(*filters)
        stmt = stmt.order_by(OjProblemData.id.desc()).offset(query.pagination.offset).limit(query.pagination.size)
        items = list((await self.db.execute(stmt)).scalars().all())
        total = (await self.db.execute(count_stmt)).scalar_one()
        return items, total
