"""
Generated by HEI code generator.
Author: Charlie
Generated at: 2026-07-28 20:51:11
"""

from datetime import datetime
from typing import Any

from pydantic import Field

from app.core.response.pagination import PageQuery
from app.core.schema.base import ApiSchema
from app.modules.biz.problem.enums import JudgeMode


class OjProblemDataCreateRequest(ApiSchema):
    problem_id: str
    judge_mode: JudgeMode = JudgeMode.STANDARD
    zip_object_name: str | None = None
    spj_source: str | None = None
    interactor_source: str | None = None
    interactor_language_key: str | None = None
    extra: dict[str, Any] | None = None


class OjProblemDataUpdateRequest(OjProblemDataCreateRequest):
    id: str = Field(min_length=1, max_length=64)


class OjProblemDataAdminPageQuery(ApiSchema):
    pagination: PageQuery
    problem_id: str | None = None
    zip_object_name: str | None = None


class OjProblemDataSchema(ApiSchema):
    id: str
    problem_id: str
    judge_mode: JudgeMode = JudgeMode.STANDARD
    zip_object_name: str | None = None
    spj_source: str | None = None
    interactor_source: str | None = None
    interactor_language_key: str | None = None
    extra: dict[str, Any]
    created_at: datetime
    created_by: str | None = None
    updated_at: datetime
    updated_by: str | None = None
