"""
Generated by HEI code generator.
Author: Charlie
Generated at: 2026-07-28 20:51:11
"""

from __future__ import annotations

from sqlalchemy.ext.asyncio import AsyncSession

from app.core.exceptions.business import BusinessError, NotFoundError
from app.core.response.pagination import PageData, build_page
from app.core.schema.base import IdQuery, IdsRequest, to_schema
from app.modules.biz.oj_scope import delete_owned_by_parent
from app.modules.biz.problem.data.model import OjProblemData
from app.modules.biz.problem.data.repository import OjProblemDataRepository
from app.modules.biz.problem.data.schema import (
    OjProblemDataAdminPageQuery,
    OjProblemDataCreateRequest,
    OjProblemDataSchema,
    OjProblemDataUpdateRequest,
)
from app.modules.biz.problem.enums import JudgeMode
from app.platform.db.transaction import transactional


class OjProblemDataService:
    def __init__(self, db: AsyncSession):
        self.db = db
        self.repo = OjProblemDataRepository(db)

    @staticmethod
    def _ensure_belongs_to_problem(entity: object, problem_id: str) -> None:
        if getattr(entity, "problem_id") != problem_id:
            raise NotFoundError("OjProblemData not found")

    async def create(self, problem_id: str, payload: OjProblemDataCreateRequest) -> None:
        prepared = self._prepare_payload(payload)
        async with transactional(self.db):
            await self.repo.create(prepared.model_copy(update={"problem_id": problem_id}))

    async def update(self, problem_id: str, payload: OjProblemDataUpdateRequest) -> None:
        prepared = self._prepare_payload(payload)
        async with transactional(self.db):
            entity = await self.repo.get_required(payload.id)
            self._ensure_belongs_to_problem(entity, problem_id)
            await self.repo.update(prepared.model_copy(update={"problem_id": problem_id}))

    async def delete(self, problem_id: str, payload: IdsRequest) -> None:
        async with transactional(self.db):
            await delete_owned_by_parent(
                self.db,
                model=OjProblemData,
                parent_attr="problem_id",
                parent_id=problem_id,
                entity_ids=payload.ids,
                not_found_message="OjProblemData not found",
            )

    async def detail(self, problem_id: str, query: IdQuery) -> OjProblemDataSchema:
        entity = await self.repo.get_required(query.id)
        self._ensure_belongs_to_problem(entity, problem_id)
        return to_schema(OjProblemDataSchema, entity)

    async def page_admin(
        self, problem_id: str, query: OjProblemDataAdminPageQuery
    ) -> PageData[OjProblemDataSchema]:
        scoped_query = query.model_copy(update={"problem_id": problem_id})
        items, total = await self.repo.page_admin(scoped_query)
        schemas = [to_schema(OjProblemDataSchema, item) for item in items]
        return build_page(scoped_query.pagination, total, schemas)

    def _prepare_payload(
        self,
        payload: OjProblemDataCreateRequest | OjProblemDataUpdateRequest,
    ) -> OjProblemDataCreateRequest | OjProblemDataUpdateRequest:
        judge_mode = payload.judge_mode or JudgeMode.STANDARD
        is_spj = judge_mode == JudgeMode.SPECIAL_JUDGE
        is_interactive = judge_mode == JudgeMode.INTERACTIVE

        spj_source = (payload.spj_source or "").strip() or None
        interactor_source = (payload.interactor_source or "").strip() or None

        if is_spj and not spj_source:
            raise BusinessError("SPECIAL_JUDGE 需要 SPJ 源码")
        if is_interactive and not interactor_source:
            raise BusinessError("INTERACTIVE 需要交互器源码")
        if not is_spj:
            spj_source = None
        if not is_interactive:
            interactor_source = None

        checker = "custom" if is_spj else "standard"
        return payload.model_copy(
            update={
                "judge_mode": judge_mode,
                "checker": checker,
                "checker_args": payload.checker_args if payload.checker_args is not None else {},
                "spj_source": spj_source,
                "interactor_source": interactor_source,
                "generator_file_id": payload.generator_file_id,
                "output_prefix": payload.output_prefix,
                "output_limit": payload.output_limit,
                "enable_unicode": payload.enable_unicode,
                "disable_big_math": payload.disable_big_math,
                "feedback": payload.feedback,
                "extra": payload.extra if payload.extra is not None else {},
            }
        )
