-- OJ P0：仅「启用/禁用」以外还有其它取值时才新建字典
-- - 纯启用/禁用 → 复用 COMMON_STATUS
-- - 题目状态含 DRAFT/PUBLISHED → OJ_PROBLEM_STATUS
-- - 执行机管理状态含 DRAINING → OJ_JUDGE_ADMIN_STATUS（完整三项）
-- Author: Charlie

INSERT INTO `sys_dict` (`id`, `code`, `label`, `value`, `color`, `category`, `parent_id`, `status`, `sort`, `created_at`, `created_by`, `updated_at`, `updated_by`)
SELECT * FROM (
  SELECT '101600' AS id, 'OJ_PROBLEM_STATUS' AS code, 'OJ题目状态' AS label, 'OJ_PROBLEM_STATUS' AS value, '#2080f0' AS color, 'SYS' AS category, NULL AS parent_id, 'ENABLED' AS status, 0 AS sort, CURRENT_TIMESTAMP(6) AS created_at, NULL AS created_by, CURRENT_TIMESTAMP(6) AS updated_at, NULL AS updated_by
  UNION ALL SELECT '101601', 'OJ_PROBLEM_STATUS_DRAFT', '草稿', 'DRAFT', '#909399', 'SYS', '101600', 'ENABLED', 1, CURRENT_TIMESTAMP(6), NULL, CURRENT_TIMESTAMP(6), NULL
  UNION ALL SELECT '101602', 'OJ_PROBLEM_STATUS_PUBLISHED', '已发布', 'PUBLISHED', '#18a058', 'SYS', '101600', 'ENABLED', 2, CURRENT_TIMESTAMP(6), NULL, CURRENT_TIMESTAMP(6), NULL
  UNION ALL SELECT '101603', 'OJ_PROBLEM_STATUS_DISABLED', '已禁用', 'DISABLED', '#d03050', 'SYS', '101600', 'ENABLED', 3, CURRENT_TIMESTAMP(6), NULL, CURRENT_TIMESTAMP(6), NULL
  UNION ALL SELECT '101610', 'OJ_JUDGE_ADMIN_STATUS', 'OJ执行机管理状态', 'OJ_JUDGE_ADMIN_STATUS', '#2080f0', 'SYS', NULL, 'ENABLED', 0, CURRENT_TIMESTAMP(6), NULL, CURRENT_TIMESTAMP(6), NULL
  UNION ALL SELECT '101611', 'OJ_JUDGE_ADMIN_STATUS_ENABLED', '启用', 'ENABLED', '#18a058', 'SYS', '101610', 'ENABLED', 1, CURRENT_TIMESTAMP(6), NULL, CURRENT_TIMESTAMP(6), NULL
  UNION ALL SELECT '101612', 'OJ_JUDGE_ADMIN_STATUS_DISABLED', '禁用', 'DISABLED', '#d03050', 'SYS', '101610', 'ENABLED', 2, CURRENT_TIMESTAMP(6), NULL, CURRENT_TIMESTAMP(6), NULL
  UNION ALL SELECT '101613', 'OJ_JUDGE_ADMIN_STATUS_DRAINING', '排空', 'DRAINING', '#f0a020', 'SYS', '101610', 'ENABLED', 3, CURRENT_TIMESTAMP(6), NULL, CURRENT_TIMESTAMP(6), NULL
) AS t
WHERE NOT EXISTS (
  SELECT 1 FROM `sys_dict` d WHERE d.`id` = t.id
);
