<!--
  Generated by HEI code generator.
  Author: Charlie
  Generated at: 2026-07-28 20:51:13
-->

<script setup lang="ts">
import { ojContestBannedUserApi } from '@/api'
import { displayValue, formatDateTime } from '@/utils'
import { computed, reactive } from 'vue'
import { useRoute } from 'vue-router'

const route = useRoute()
const props = defineProps<{ contestId?: string, embedded?: boolean }>()
const contestId = computed(() => String(props.contestId ?? route.query.id ?? ''))

const state = reactive({
  showModal: false,
  loading: false,
  detail: {} as any,
})

async function openModal(id: string) {
  state.detail = {}
  state.showModal = true
  await fetchDetail(id)
}

async function fetchDetail(id: string) {
  state.loading = true
  try {
    const response = await ojContestBannedUserApi.detail(contestId.value, { id })
    state.detail = response.data ?? {}
  } finally {
    state.loading = false
  }
}

defineExpose({
  openModal,
})
</script>

<template>
  <NModal v-model:show="state.showModal" preset="card" draggable :mask-closable="false" title="竞赛禁赛用户详情" style="width: 680px">
    <NScrollbar class="max-h-[min(620px,calc(100vh-300px))] pr-16px">
      <NSpin :show="state.loading">
        <NDescriptions label-placement="left" bordered :column="1">
          <NDescriptionsItem label="主键">
            {{ displayValue(state.detail.id) }}
          </NDescriptionsItem>
          <NDescriptionsItem label="竞赛ID">
            {{ displayValue(state.detail.contest_id) }}
          </NDescriptionsItem>
          <NDescriptionsItem label="账户ID">
            {{ displayValue(state.detail.account_id) }}
          </NDescriptionsItem>
          <NDescriptionsItem label="禁赛原因">
            {{ displayValue(state.detail.reason) }}
          </NDescriptionsItem>
          <NDescriptionsItem label="创建时间">{{ formatDateTime(state.detail.created_at) }}</NDescriptionsItem>
          <NDescriptionsItem label="创建人">{{ displayValue(state.detail.created_by) }}</NDescriptionsItem>
          <NDescriptionsItem label="更新时间">{{ formatDateTime(state.detail.updated_at) }}</NDescriptionsItem>
          <NDescriptionsItem label="更新人">{{ displayValue(state.detail.updated_by) }}</NDescriptionsItem>
        </NDescriptions>
      </NSpin>
    </NScrollbar>
  </NModal>
</template>
