/**
 * 静态资源路由表。
 *
 * 这里模拟后端 sys_resource 表返回的数据结构，字段需要与 AppRoute.RowRoute / SysResource 保持一致。
 * 注意：这里的 path 是资源自身路径，不使用 VITE_HOME_PATH；VITE_HOME_PATH 只负责默认首页跳转。
 */
export const staticRoutes: AppRoute.RowRoute[] = [
  {
    // 工作台：普通菜单页面，同时作为固定标签页展示。
    id: '1',
    parent_id: null,
    code: 'dashboard',
    name: '工作台',
    locale_key: 'resource.dashboard.title',
    resource_type: 'MENU',
    module_id: '210001',
    module_id_name: '系统',
    path: '/dashboard',
    component: '/dashboard/index.vue',
    redirect: null,
    icon: 'icon-park-outline:analysis',
    href: null,
    sort: 1,
    is_visible: true,
    is_cache: false,
    is_affix: true,
    status: 'ENABLED',
    description: null,
  },
  {
    // 示例目录：CATALOG 只负责菜单分组，不直接加载页面组件。
    id: '2',
    parent_id: null,
    code: 'demo',
    name: '示例页面',
    locale_key: 'resource.demo.title',
    resource_type: 'CATALOG',
    module_id: '210001',
    module_id_name: '系统',
    path: '/demo',
    component: null,
    redirect: null,
    icon: 'icon-park-outline:application-one',
    href: null,
    sort: 20,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    // 系统管理：CATALOG 只负责菜单分组，不直接加载页面组件。
    id: '3',
    parent_id: null,
    code: 'sys',
    name: '系统管理',
    locale_key: 'resource.sys.title',
    resource_type: 'CATALOG',
    module_id: '210001',
    module_id_name: '系统',
    path: '/sys',
    component: null,
    redirect: null,
    icon: 'icon-park-outline:setting-two',
    href: null,
    sort: 10,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    // 字典管理：左树右表的本地模拟 CRUD 示例。
    id: '302',
    parent_id: '3',
    code: 'sys-dict',
    name: '字典管理',
    locale_key: 'resource.sys.dict.title',
    resource_type: 'MENU',
    module_id: '210001',
    module_id_name: '系统',
    path: '/sys/dict',
    component: '/sys/dict/index.vue',
    redirect: null,
    icon: 'icon-park-outline:file-search',
    href: null,
    sort: 2,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    // 展示图管理：使用后端展示图管理接口的 CRUD 示例。
    id: '303',
    parent_id: '3',
    code: 'sys-banner',
    name: '展示图管理',
    locale_key: 'resource.sys.banner.title',
    resource_type: 'MENU',
    module_id: '210001',
    module_id_name: '系统',
    path: '/sys/banner',
    component: '/sys/banner/index.vue',
    redirect: null,
    icon: 'icon-park-outline:ad-product',
    href: null,
    sort: 3,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    id: '4',
    parent_id: null,
    code: 'iam',
    name: '身份权限',
    locale_key: 'resource.iam.title',
    resource_type: 'CATALOG',
    module_id: '210001',
    module_id_name: '系统',
    path: '/iam',
    component: null,
    redirect: null,
    icon: 'icon-park-outline:permissions',
    href: null,
    sort: 15,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    id: '401',
    parent_id: '4',
    code: 'iam-account',
    name: '账号管理',
    locale_key: 'resource.iam.account.title',
    resource_type: 'MENU',
    module_id: '210001',
    module_id_name: '系统',
    path: '/iam/account',
    component: '/iam/account/index.vue',
    redirect: null,
    icon: 'icon-park-outline:people',
    href: null,
    sort: 1,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    id: '402',
    parent_id: '4',
    code: 'iam-dept',
    name: '部门管理',
    locale_key: 'resource.iam.dept.title',
    resource_type: 'MENU',
    module_id: '210001',
    module_id_name: '系统',
    path: '/iam/dept',
    component: '/iam/dept/index.vue',
    redirect: null,
    icon: 'icon-park-outline:tree-diagram',
    href: null,
    sort: 2,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    id: '403',
    parent_id: '4',
    code: 'iam-group',
    name: '用户组管理',
    locale_key: 'resource.iam.group.title',
    resource_type: 'MENU',
    module_id: '210001',
    module_id_name: '系统',
    path: '/iam/group',
    component: '/iam/group/index.vue',
    redirect: null,
    icon: 'icon-park-outline:group',
    href: null,
    sort: 3,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    id: '404',
    parent_id: '4',
    code: 'iam-position',
    name: '岗位管理',
    locale_key: 'resource.iam.position.title',
    resource_type: 'MENU',
    module_id: '210001',
    module_id_name: '系统',
    path: '/iam/position',
    component: '/iam/position/index.vue',
    redirect: null,
    icon: 'icon-park-outline:people-bottom',
    href: null,
    sort: 4,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    id: '405',
    parent_id: '4',
    code: 'iam-role',
    name: '角色管理',
    locale_key: 'resource.iam.role.title',
    resource_type: 'MENU',
    module_id: '210001',
    module_id_name: '系统',
    path: '/iam/role',
    component: '/iam/role/index.vue',
    redirect: null,
    icon: 'icon-park-outline:peoples',
    href: null,
    sort: 5,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    id: '406',
    parent_id: '4',
    code: 'iam-resource',
    name: '资源管理',
    locale_key: 'resource.iam.resource.title',
    resource_type: 'MENU',
    module_id: '210001',
    module_id_name: '系统',
    path: '/iam/resource',
    component: '/iam/resource/index.vue',
    redirect: null,
    icon: 'icon-park-outline:all-application',
    href: null,
    sort: 6,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    id: '407',
    parent_id: '4',
    code: 'iam-resourcemodule',
    name: '资源模块管理',
    locale_key: 'resource.iam.resource_module.title',
    resource_type: 'MENU',
    module_id: '210001',
    module_id_name: '系统',
    path: '/iam/resource_module',
    component: '/iam/resource_module/index.vue',
    redirect: null,
    icon: 'icon-park-outline:blocks-and-arrows',
    href: null,
    sort: 7,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    id: '5',
    parent_id: null,
    code: 'message',
    name: '消息中心',
    locale_key: 'resource.message.title',
    resource_type: 'CATALOG',
    module_id: '210001',
    module_id_name: '系统',
    path: '/message',
    component: null,
    redirect: null,
    icon: 'icon-park-outline:message',
    href: null,
    sort: 18,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    id: '501',
    parent_id: '5',
    code: 'message-notification',
    name: '通知管理',
    locale_key: 'resource.message.notification.title',
    resource_type: 'MENU',
    module_id: '210001',
    module_id_name: '系统',
    path: '/message/notification',
    component: '/message/notification/index.vue',
    redirect: null,
    icon: 'icon-park-outline:tips-one',
    href: null,
    sort: 1,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    id: '502',
    parent_id: '5',
    code: 'message-message',
    name: '站内信管理',
    locale_key: 'resource.message.message.title',
    resource_type: 'MENU',
    module_id: '210001',
    module_id_name: '系统',
    path: '/message/message',
    component: '/message/message/index.vue',
    redirect: null,
    icon: 'icon-park-outline:message',
    href: null,
    sort: 2,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    id: '503',
    parent_id: '5',
    code: 'message-todo',
    name: '待办管理',
    locale_key: 'resource.message.todo.title',
    resource_type: 'MENU',
    module_id: '210001',
    module_id_name: '系统',
    path: '/message/todo',
    component: '/message/todo/index.vue',
    redirect: null,
    icon: 'icon-park-outline:checklist',
    href: null,
    sort: 3,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    // 示例总览：普通菜单页面，并开启页面缓存。
    id: '201',
    parent_id: '2',
    code: 'demo-overview',
    name: '示例总览',
    locale_key: 'resource.demo.overview',
    resource_type: 'MENU',
    module_id: '210001',
    module_id_name: '系统',
    path: '/demo/overview',
    component: '/demo/overview/index.vue',
    redirect: null,
    icon: 'icon-park-outline:dashboard-one',
    href: null,
    sort: 1,
    is_visible: true,
    is_cache: true,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    // 列表示例：普通菜单页面，详情页会从这里跳转进入。
    id: '202',
    parent_id: '2',
    code: 'demo-list',
    name: '列表示例',
    locale_key: 'resource.demo.list',
    resource_type: 'MENU',
    module_id: '210001',
    module_id_name: '系统',
    path: '/demo/list',
    component: '/demo/list/index.vue',
    redirect: null,
    icon: 'icon-park-outline:list-view',
    href: null,
    sort: 2,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    // 表单示例：普通菜单页面。
    id: '203',
    parent_id: '2',
    code: 'demo-form',
    name: '表单示例',
    locale_key: 'resource.demo.form',
    resource_type: 'MENU',
    module_id: '210001',
    module_id_name: '系统',
    path: '/demo/form',
    component: '/demo/form/index.vue',
    redirect: null,
    icon: 'icon-park-outline:edit',
    href: null,
    sort: 3,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    // 图表示例：普通菜单页面。
    id: '204',
    parent_id: '2',
    code: 'demo-chart',
    name: '图表示例',
    locale_key: 'resource.demo.chart',
    resource_type: 'MENU',
    module_id: '210001',
    module_id_name: '系统',
    path: '/demo/chart',
    component: '/demo/chart/index.vue',
    redirect: null,
    icon: 'icon-park-outline:chart-line',
    href: null,
    sort: 4,
    is_visible: true,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
  {
    // 详情示例：PAGE 页面可通过路由访问，但 is_visible=false 表示不显示在侧边菜单和搜索中。
    id: '205',
    parent_id: '2',
    code: 'demo-detail',
    name: '详情示例',
    locale_key: 'resource.demo.detail',
    resource_type: 'PAGE',
    module_id: '210001',
    module_id_name: '系统',
    path: '/demo/detail',
    component: '/demo/detail/index.vue',
    redirect: null,
    icon: 'icon-park-outline:doc-detail',
    href: null,
    sort: 5,
    is_visible: false,
    is_cache: false,
    is_affix: false,
    status: 'ENABLED',
    description: null,
  },
]
