"""
Generated by HEI code generator.
Author: Charlie
Generated at: 2026-07-23 16:28:51
"""

from datetime import datetime
from typing import Any

from pydantic import Field

from app.core.response.pagination import PageQuery
from app.core.schema.base import ApiSchema, Id


class MsgAnnouncementCreateRequest(ApiSchema):
    title: str
    content: str
    content_type: str
    severity: str
    target_scope: str
    target_account_type: str | None = None
    publish_locations: dict[str, Any]
    is_pinned: bool
    pinned_until: datetime | None = None
    sender_account_type: str | None = None
    sender_account_id: str | None = None
    status: str
    publish_at: datetime | None = None
    revoked_at: datetime | None = None
    expire_at: datetime | None = None
    view_count: int
    extra: dict[str, Any]


class MsgAnnouncementUpdateRequest(MsgAnnouncementCreateRequest):
    id: str = Field(min_length=1, max_length=64)


class MsgAnnouncementAdminPageQuery(ApiSchema):
    pagination: PageQuery
    title: str | None = None
    status: str | None = None


class AnnouncementReadRequest(ApiSchema):
    ids: list[Id] = Field(min_length=1)


class MyAnnouncementPageQuery(ApiSchema):
    pagination: PageQuery


class PinAnnouncementRequest(ApiSchema):
    id: Id
    is_pinned: bool
    pinned_until: datetime | None = None


class MsgAnnouncementSchema(ApiSchema):
    id: str
    title: str
    content: str
    content_type: str
    severity: str
    target_scope: str
    target_account_type: str | None = None
    publish_locations: dict[str, Any]
    is_pinned: bool
    pinned_until: datetime | None = None
    sender_account_type: str | None = None
    sender_account_id: str | None = None
    status: str
    publish_at: datetime | None = None
    revoked_at: datetime | None = None
    expire_at: datetime | None = None
    view_count: int
    extra: dict[str, Any]
    is_read: bool = False
    created_at: datetime
    created_by: str | None = None
    updated_at: datetime
    updated_by: str | None = None
