<template>
  <Layout title="Banner管理" back>
    <view class="flex flex-col"><view class="bg-white mx-4 mt-3 rounded-lg overflow-hidden"><view class="flex items-center gap-2 p-2"><u-search v-model="keyword" placeholder="搜索标题" :show-action="false" @search="onSearch" class="flex-1" /><u-button text="新增" type="primary" icon="plus" @click="openCreate" /></view></view><view v-for="item in records" :key="item.id" class="mx-4 mt-3 bg-white rounded-lg overflow-hidden"><view class="flex items-center justify-between px-4 py-3 border-b"><view class="flex flex-col"><text class="text-base font-bold text-gray-900">{{ item.title }}</text><text class="text-xs text-gray-500">{{ item.summary || '-' }}</text></view><view class="flex gap-1"><u-button text="详情" size="mini" plain @click="openDetail(item)" /><u-button text="编辑" size="mini" plain @click="openEdit(item)" /><u-button text="删除" size="mini" plain type="error" @click="confirmDelete(item)" /></view></view><view class="px-4 py-2 flex flex-wrap gap-x-4 gap-y-1 text-xs text-gray-500"><text>分类: {{ dictLabel('BANNER_CATEGORY', item.category) }}</text><text>位置: {{ dictLabel('BANNER_POSITION', item.position) }}</text><text>类型: {{ dictLabel('BANNER_TYPE', item.type) }}</text><text>{{ formatDateTime(item.updated_at) }}</text></view></view><u-loadmore :status="loadStatus" /></view>
    <u-popup :show="formVisible" mode="bottom" :safe-area-inset-bottom="true" @close="formVisible = false"><view class="bg-white rounded-t-lg p-4" style="max-height: 70vh; overflow-y: auto;"><text class="block text-lg font-bold mb-4">{{ editingId ? '编辑Banner' : '新增Banner' }}</text><u-form :model="form"><u-form-item label="标题" required><u-input v-model="form.title" placeholder="请输入标题" border="none" /></u-form-item><u-form-item label="分类" required><view class="w-full" @click="openPicker('category', dictOptions('BANNER_CATEGORY'))"><u-input :value="dictLabel('BANNER_CATEGORY', form.category)" placeholder="请选择" disabled border="none" /></view></u-form-item><u-form-item label="类型" required><view class="w-full" @click="openPicker('type', dictOptions('BANNER_TYPE'))"><u-input :value="dictLabel('BANNER_TYPE', form.type)" placeholder="请选择" disabled border="none" /></view></u-form-item><u-form-item label="位置" required><view class="w-full" @click="openPicker('position', dictOptions('BANNER_POSITION'))"><u-input :value="dictLabel('BANNER_POSITION', form.position)" placeholder="请选择" disabled border="none" /></view></u-form-item><u-form-item label="展示范围" required><view class="w-full" @click="openPicker('display_scope', dictOptions('BANNER_DISPLAY_SCOPE'))"><u-input :value="dictLabel('BANNER_DISPLAY_SCOPE', form.display_scope)" placeholder="请选择" disabled border="none" /></view></u-form-item><u-form-item label="链接"><u-input v-model="form.url" placeholder="请输入URL" border="none" /></u-form-item><u-form-item label="排序"><u-number-box v-model="form.sort" :min="0" /></u-form-item><u-form-item label="状态"><view class="w-full" @click="openPicker('status', dictOptions('COMMON_STATUS'))"><u-input :value="dictLabel('COMMON_STATUS', form.status)" placeholder="请选择" disabled border="none" /></view></u-form-item><u-form-item label="开始时间"><u-input v-model="form.start_at" placeholder="YYYY-MM-DD HH:mm:ss" border="none" /></u-form-item><u-form-item label="结束时间"><u-input v-model="form.end_at" placeholder="YYYY-MM-DD HH:mm:ss" border="none" /></u-form-item><u-form-item label="摘要"><u-input v-model="form.summary" placeholder="请输入摘要" border="none" /></u-form-item><u-form-item label="描述"><u-textarea v-model="form.description" placeholder="请输入描述" border="none" /></u-form-item></u-form><u-button text="保存" type="primary" :loading="saving" @click="doSave" class="mt-4" /></view></u-popup>
    <u-popup :show="detailVisible" mode="bottom" :safe-area-inset-bottom="true" @close="detailVisible = false"><view class="bg-white rounded-t-lg p-4" style="max-height: 70vh; overflow-y: auto;"><text class="block text-lg font-bold mb-4">Banner详情</text><u-cell-group :border="false"><u-cell-item v-for="f in detailFields" :key="f" :title="detailLabel(f)" :value="displayVal(detail[f])" :arrow="false" /></u-cell-group></view></u-popup>
    <u-picker :show="pickerShow" :columns="pickerColumns" key-name="label" @confirm="onPickerConfirm" @close="pickerShow = false" />
  </Layout>
</template>
<script setup lang="ts">
import { computed, ref } from 'vue'; import { onLoad, onPullDownRefresh } from '@dcloudio/uni-app'; import Layout from '@/layouts/index.vue'; import { bannerApi } from '@/api'; import { dictList } from '@/utils/dict'; import { displayValue, formatDateTime } from '@/utils/format'; import { fallbackDicts } from '@/config/resource'
const records = ref<any[]>([]); const keyword = ref(''); const current = ref(1); const total = ref(0); const loading = ref(false); const formVisible = ref(false); const detailVisible = ref(false); const saving = ref(false); const editingId = ref(''); const detail = ref<any>({}); const form = ref<Record<string, any>>({}); const pickerShow = ref(false); const pickerField = ref(''); const pickerColumns = ref<any[]>([[]])
const detailFields = ['id', 'title', 'image', 'url', 'link_type', 'category', 'type', 'position', 'display_scope', 'sort', 'status', 'start_at', 'end_at', 'summary', 'description', 'created_at', 'updated_at']
const loadStatus = computed(() => loading.value ? 'loading' : records.value.length >= total.value ? 'nomore' : 'loadmore')
onLoad(() => { refresh() }); onPullDownRefresh(async () => { await refresh(); uni.stopPullDownRefresh() })
async function refresh() { current.value = 1; await loadPage(false) }
async function loadPage(a: boolean) { loading.value = true; try { const p: any = { current: current.value, size: 20 }; if (keyword.value) { const pg = await bannerApi.page(p); records.value = a ? [...records.value, ...(pg.records ?? [])] : (pg.records ?? []); total.value = pg.total ?? 0 } } finally { loading.value = false } }
function onSearch() { refresh() }; function dictOptions(c: string) { return dictList(c).length ? dictList(c) : fallbackDicts[c] ?? [] }; function dictLabel(c: string, v: any) { return dictOptions(c).find((o: any) => String(o.value) === String(v))?.label ?? v ?? '' }; function displayVal(v: any) { const dt = formatDateTime(v); return displayValue(dt !== v ? dt : v) }; function detailLabel(p: string) { const m: Record<string, string> = { id: 'ID', title: '标题', image: '图片', url: 'URL', link_type: '链接类型', category: '分类', type: '类型', position: '位置', display_scope: '展示范围', sort: '排序', status: '状态', start_at: '开始时间', end_at: '结束时间', summary: '摘要', description: '描述', created_at: '创建时间', updated_at: '更新时间' }; return m[p] ?? p }; function openPicker(f: string, o: any[]) { pickerField.value = f; pickerColumns.value = [o]; pickerShow.value = true }; function onPickerConfirm(e: any) { const v = e.value?.[0]; if (pickerField.value && v) form.value[pickerField.value] = v.value; pickerShow.value = false }; function openCreate() { editingId.value = ''; form.value = { sort: 0, status: 'ENABLED' }; formVisible.value = true }; function openEdit(item: any) { editingId.value = item.id; form.value = { ...item }; formVisible.value = true }; function openDetail(item: any) { detail.value = item; detailVisible.value = true }; async function doSave() { saving.value = true; try { const p: any = { ...form.value }; if (editingId.value) { await bannerApi.update({ ...p, id: editingId.value }) } else { await bannerApi.create(p) }; formVisible.value = false; await refresh() } finally { saving.value = false } }; function confirmDelete(item: any) { uni.showModal({ title: '确认删除', content: `删除 ${item.title}？`, success: async (r: any) => { if (r.confirm) { await bannerApi.remove({ ids: [item.id] }); await refresh() } } }) }
</script>
