"""
Generated by HEI code generator.
Author: Charlie
Generated at: 2026-07-28 20:51:13
"""

from app.platform.module import ModuleSpec, RouteSpec

module = ModuleSpec(
    name="biz.contest.private_contestant",
    routes=(
        RouteSpec(
            version="v1",
            prefix="/admin",
            tags=("admin",),
            router="app.modules.biz.contest.private_contestant.router:router",
        ),
    ),
    order=322,
    depends_on=("biz.contest.contest",),
    models=("app.modules.biz.contest.private_contestant.model",),
)
