"""
Generated by HEI code generator.
Author: Charlie
Generated at: 2026-07-28 20:51:13
"""

from sqlalchemy.ext.asyncio import AsyncSession

from app.core.exceptions.business import NotFoundError
from app.modules.biz.oj_scope import delete_owned_by_parent
from app.core.response.pagination import PageData, build_page
from app.core.schema.base import ContestIdsRequest, ContestScopedIdQuery, to_schema, to_schema_list
from app.platform.db.transaction import transactional
from app.modules.biz.contest.banned_user.model import OjContestBannedUser
from app.modules.biz.contest.banned_user.repository import (
    OjContestBannedUserRepository,
)
from app.modules.biz.contest.banned_user.schema import (
    OjContestBannedUserAdminPageQuery,
    OjContestBannedUserCreateRequest,
    OjContestBannedUserSchema,
    OjContestBannedUserUpdateRequest,
)


class OjContestBannedUserService:
    def __init__(self, db: AsyncSession):
        self.db = db
        self.repo = OjContestBannedUserRepository(db)

    @staticmethod
    def _ensure_belongs_to_contest(entity: object, contest_id: str) -> None:
        if getattr(entity, "contest_id") != contest_id:
            raise NotFoundError("OjContestBannedUser not found")

    async def create(self, payload: OjContestBannedUserCreateRequest) -> None:
        async with transactional(self.db):
            await self.repo.create(payload)

    async def update(self, payload: OjContestBannedUserUpdateRequest) -> None:
        async with transactional(self.db):
            entity = await self.repo.get_required(payload.id)
            self._ensure_belongs_to_contest(entity, payload.contest_id)
            await self.repo.update(payload)

    async def delete(self, payload: ContestIdsRequest) -> None:
        async with transactional(self.db):
            await delete_owned_by_parent(
                self.db,
                model=OjContestBannedUser,
                parent_attr="contest_id",
                parent_id=payload.contest_id,
                entity_ids=payload.ids,
                not_found_message="OjContestBannedUser not found",
            )

    async def detail(self, query: ContestScopedIdQuery) -> OjContestBannedUserSchema:
        entity = await self.repo.get_required(query.id)
        self._ensure_belongs_to_contest(entity, query.contest_id)
        return to_schema(OjContestBannedUserSchema, entity)

    async def page_admin(
        self, query: OjContestBannedUserAdminPageQuery
    ) -> PageData[OjContestBannedUserSchema]:
        items, total = await self.repo.page_admin(query)
        return build_page(query.pagination, total, to_schema_list(OjContestBannedUserSchema, items))
