Name: similarity-service
Host: 0.0.0.0
Port: 8882

Nacos:
  ServerAddr: "nacos:8848"
  Username: "nacos"
  Password: "nacos"
  Namespace: ""
  Group: "DEFAULT_GROUP"
  DataId: "similarity-service.yaml"
