/**
 * Generated by HEI code generator.
 * Author: Charlie
 * Generated at: 2026-07-28 20:51:11
 */
import { http } from '@/utils'

const prefix = '/api/v1/admin/biz/problem/language'

export function page(problemId: string, params: any) {
  return http.get<any>(`${prefix}/page`, { params: { ...params, problem_id: problemId } })
}

export function detail(problemId: string, params: any) {
  return http.get<any>(`${prefix}/detail`, { params: { ...params, problem_id: problemId } })
}

export function create(problemId: string, data: any) {
  return http.post<any>(`${prefix}/create`, data, { params: { problem_id: problemId } })
}

export function update(problemId: string, data: any) {
  return http.post<any>(`${prefix}/update`, data, { params: { problem_id: problemId } })
}

export function remove(problemId: string, data: any) {
  return http.post<any>(`${prefix}/delete`, data, { params: { problem_id: problemId } })
}

/**
 * 唯一语言选项接口：worker 镜像显式启用语言。
 * 题目语言 / 试测 / 交互器选择器均应只调用本 API，禁止前端硬编码或全量枚举。
 */
export function options() {
  return http.get<Array<{ key: string, label: string, extension: string, source_filename: string }>>(
    `${prefix}/options`,
  )
}
