"""
Generated by HEI code generator.
Author: Charlie
Generated at: 2026-07-19 10:50:36
"""

from app.platform.module import ModuleSpec, RouteSpec

module = ModuleSpec(
    name="biz.cg_test_knowledge_category",
    routes=(
        RouteSpec(
            version="v1",
            prefix="/admin",
            tags=("admin",),
            router="app.modules.biz.cg_test_knowledge_category.router:router",
        ),
    ),
    models=("app.modules.biz.cg_test_knowledge_category.model",),
)
