// Code generated by ent, DO NOT EDIT.

package relrolepermission

import (
	"hei-gin/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldContainsFold(FieldID, id))
}

// RoleID applies equality check predicate on the "role_id" field. It's identical to RoleIDEQ.
func RoleID(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldEQ(FieldRoleID, v))
}

// PermissionCode applies equality check predicate on the "permission_code" field. It's identical to PermissionCodeEQ.
func PermissionCode(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldEQ(FieldPermissionCode, v))
}

// Scope applies equality check predicate on the "scope" field. It's identical to ScopeEQ.
func Scope(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldEQ(FieldScope, v))
}

// CustomScopeGroupIds applies equality check predicate on the "custom_scope_group_ids" field. It's identical to CustomScopeGroupIdsEQ.
func CustomScopeGroupIds(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldEQ(FieldCustomScopeGroupIds, v))
}

// CustomScopeOrgIds applies equality check predicate on the "custom_scope_org_ids" field. It's identical to CustomScopeOrgIdsEQ.
func CustomScopeOrgIds(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldEQ(FieldCustomScopeOrgIds, v))
}

// RoleIDEQ applies the EQ predicate on the "role_id" field.
func RoleIDEQ(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldEQ(FieldRoleID, v))
}

// RoleIDNEQ applies the NEQ predicate on the "role_id" field.
func RoleIDNEQ(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldNEQ(FieldRoleID, v))
}

// RoleIDIn applies the In predicate on the "role_id" field.
func RoleIDIn(vs ...string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldIn(FieldRoleID, vs...))
}

// RoleIDNotIn applies the NotIn predicate on the "role_id" field.
func RoleIDNotIn(vs ...string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldNotIn(FieldRoleID, vs...))
}

// RoleIDGT applies the GT predicate on the "role_id" field.
func RoleIDGT(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldGT(FieldRoleID, v))
}

// RoleIDGTE applies the GTE predicate on the "role_id" field.
func RoleIDGTE(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldGTE(FieldRoleID, v))
}

// RoleIDLT applies the LT predicate on the "role_id" field.
func RoleIDLT(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldLT(FieldRoleID, v))
}

// RoleIDLTE applies the LTE predicate on the "role_id" field.
func RoleIDLTE(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldLTE(FieldRoleID, v))
}

// RoleIDContains applies the Contains predicate on the "role_id" field.
func RoleIDContains(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldContains(FieldRoleID, v))
}

// RoleIDHasPrefix applies the HasPrefix predicate on the "role_id" field.
func RoleIDHasPrefix(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldHasPrefix(FieldRoleID, v))
}

// RoleIDHasSuffix applies the HasSuffix predicate on the "role_id" field.
func RoleIDHasSuffix(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldHasSuffix(FieldRoleID, v))
}

// RoleIDEqualFold applies the EqualFold predicate on the "role_id" field.
func RoleIDEqualFold(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldEqualFold(FieldRoleID, v))
}

// RoleIDContainsFold applies the ContainsFold predicate on the "role_id" field.
func RoleIDContainsFold(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldContainsFold(FieldRoleID, v))
}

// PermissionCodeEQ applies the EQ predicate on the "permission_code" field.
func PermissionCodeEQ(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldEQ(FieldPermissionCode, v))
}

// PermissionCodeNEQ applies the NEQ predicate on the "permission_code" field.
func PermissionCodeNEQ(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldNEQ(FieldPermissionCode, v))
}

// PermissionCodeIn applies the In predicate on the "permission_code" field.
func PermissionCodeIn(vs ...string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldIn(FieldPermissionCode, vs...))
}

// PermissionCodeNotIn applies the NotIn predicate on the "permission_code" field.
func PermissionCodeNotIn(vs ...string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldNotIn(FieldPermissionCode, vs...))
}

// PermissionCodeGT applies the GT predicate on the "permission_code" field.
func PermissionCodeGT(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldGT(FieldPermissionCode, v))
}

// PermissionCodeGTE applies the GTE predicate on the "permission_code" field.
func PermissionCodeGTE(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldGTE(FieldPermissionCode, v))
}

// PermissionCodeLT applies the LT predicate on the "permission_code" field.
func PermissionCodeLT(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldLT(FieldPermissionCode, v))
}

// PermissionCodeLTE applies the LTE predicate on the "permission_code" field.
func PermissionCodeLTE(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldLTE(FieldPermissionCode, v))
}

// PermissionCodeContains applies the Contains predicate on the "permission_code" field.
func PermissionCodeContains(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldContains(FieldPermissionCode, v))
}

// PermissionCodeHasPrefix applies the HasPrefix predicate on the "permission_code" field.
func PermissionCodeHasPrefix(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldHasPrefix(FieldPermissionCode, v))
}

// PermissionCodeHasSuffix applies the HasSuffix predicate on the "permission_code" field.
func PermissionCodeHasSuffix(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldHasSuffix(FieldPermissionCode, v))
}

// PermissionCodeEqualFold applies the EqualFold predicate on the "permission_code" field.
func PermissionCodeEqualFold(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldEqualFold(FieldPermissionCode, v))
}

// PermissionCodeContainsFold applies the ContainsFold predicate on the "permission_code" field.
func PermissionCodeContainsFold(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldContainsFold(FieldPermissionCode, v))
}

// ScopeEQ applies the EQ predicate on the "scope" field.
func ScopeEQ(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldEQ(FieldScope, v))
}

// ScopeNEQ applies the NEQ predicate on the "scope" field.
func ScopeNEQ(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldNEQ(FieldScope, v))
}

// ScopeIn applies the In predicate on the "scope" field.
func ScopeIn(vs ...string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldIn(FieldScope, vs...))
}

// ScopeNotIn applies the NotIn predicate on the "scope" field.
func ScopeNotIn(vs ...string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldNotIn(FieldScope, vs...))
}

// ScopeGT applies the GT predicate on the "scope" field.
func ScopeGT(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldGT(FieldScope, v))
}

// ScopeGTE applies the GTE predicate on the "scope" field.
func ScopeGTE(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldGTE(FieldScope, v))
}

// ScopeLT applies the LT predicate on the "scope" field.
func ScopeLT(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldLT(FieldScope, v))
}

// ScopeLTE applies the LTE predicate on the "scope" field.
func ScopeLTE(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldLTE(FieldScope, v))
}

// ScopeContains applies the Contains predicate on the "scope" field.
func ScopeContains(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldContains(FieldScope, v))
}

// ScopeHasPrefix applies the HasPrefix predicate on the "scope" field.
func ScopeHasPrefix(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldHasPrefix(FieldScope, v))
}

// ScopeHasSuffix applies the HasSuffix predicate on the "scope" field.
func ScopeHasSuffix(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldHasSuffix(FieldScope, v))
}

// ScopeIsNil applies the IsNil predicate on the "scope" field.
func ScopeIsNil() predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldIsNull(FieldScope))
}

// ScopeNotNil applies the NotNil predicate on the "scope" field.
func ScopeNotNil() predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldNotNull(FieldScope))
}

// ScopeEqualFold applies the EqualFold predicate on the "scope" field.
func ScopeEqualFold(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldEqualFold(FieldScope, v))
}

// ScopeContainsFold applies the ContainsFold predicate on the "scope" field.
func ScopeContainsFold(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldContainsFold(FieldScope, v))
}

// CustomScopeGroupIdsEQ applies the EQ predicate on the "custom_scope_group_ids" field.
func CustomScopeGroupIdsEQ(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldEQ(FieldCustomScopeGroupIds, v))
}

// CustomScopeGroupIdsNEQ applies the NEQ predicate on the "custom_scope_group_ids" field.
func CustomScopeGroupIdsNEQ(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldNEQ(FieldCustomScopeGroupIds, v))
}

// CustomScopeGroupIdsIn applies the In predicate on the "custom_scope_group_ids" field.
func CustomScopeGroupIdsIn(vs ...string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldIn(FieldCustomScopeGroupIds, vs...))
}

// CustomScopeGroupIdsNotIn applies the NotIn predicate on the "custom_scope_group_ids" field.
func CustomScopeGroupIdsNotIn(vs ...string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldNotIn(FieldCustomScopeGroupIds, vs...))
}

// CustomScopeGroupIdsGT applies the GT predicate on the "custom_scope_group_ids" field.
func CustomScopeGroupIdsGT(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldGT(FieldCustomScopeGroupIds, v))
}

// CustomScopeGroupIdsGTE applies the GTE predicate on the "custom_scope_group_ids" field.
func CustomScopeGroupIdsGTE(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldGTE(FieldCustomScopeGroupIds, v))
}

// CustomScopeGroupIdsLT applies the LT predicate on the "custom_scope_group_ids" field.
func CustomScopeGroupIdsLT(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldLT(FieldCustomScopeGroupIds, v))
}

// CustomScopeGroupIdsLTE applies the LTE predicate on the "custom_scope_group_ids" field.
func CustomScopeGroupIdsLTE(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldLTE(FieldCustomScopeGroupIds, v))
}

// CustomScopeGroupIdsContains applies the Contains predicate on the "custom_scope_group_ids" field.
func CustomScopeGroupIdsContains(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldContains(FieldCustomScopeGroupIds, v))
}

// CustomScopeGroupIdsHasPrefix applies the HasPrefix predicate on the "custom_scope_group_ids" field.
func CustomScopeGroupIdsHasPrefix(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldHasPrefix(FieldCustomScopeGroupIds, v))
}

// CustomScopeGroupIdsHasSuffix applies the HasSuffix predicate on the "custom_scope_group_ids" field.
func CustomScopeGroupIdsHasSuffix(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldHasSuffix(FieldCustomScopeGroupIds, v))
}

// CustomScopeGroupIdsIsNil applies the IsNil predicate on the "custom_scope_group_ids" field.
func CustomScopeGroupIdsIsNil() predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldIsNull(FieldCustomScopeGroupIds))
}

// CustomScopeGroupIdsNotNil applies the NotNil predicate on the "custom_scope_group_ids" field.
func CustomScopeGroupIdsNotNil() predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldNotNull(FieldCustomScopeGroupIds))
}

// CustomScopeGroupIdsEqualFold applies the EqualFold predicate on the "custom_scope_group_ids" field.
func CustomScopeGroupIdsEqualFold(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldEqualFold(FieldCustomScopeGroupIds, v))
}

// CustomScopeGroupIdsContainsFold applies the ContainsFold predicate on the "custom_scope_group_ids" field.
func CustomScopeGroupIdsContainsFold(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldContainsFold(FieldCustomScopeGroupIds, v))
}

// CustomScopeOrgIdsEQ applies the EQ predicate on the "custom_scope_org_ids" field.
func CustomScopeOrgIdsEQ(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldEQ(FieldCustomScopeOrgIds, v))
}

// CustomScopeOrgIdsNEQ applies the NEQ predicate on the "custom_scope_org_ids" field.
func CustomScopeOrgIdsNEQ(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldNEQ(FieldCustomScopeOrgIds, v))
}

// CustomScopeOrgIdsIn applies the In predicate on the "custom_scope_org_ids" field.
func CustomScopeOrgIdsIn(vs ...string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldIn(FieldCustomScopeOrgIds, vs...))
}

// CustomScopeOrgIdsNotIn applies the NotIn predicate on the "custom_scope_org_ids" field.
func CustomScopeOrgIdsNotIn(vs ...string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldNotIn(FieldCustomScopeOrgIds, vs...))
}

// CustomScopeOrgIdsGT applies the GT predicate on the "custom_scope_org_ids" field.
func CustomScopeOrgIdsGT(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldGT(FieldCustomScopeOrgIds, v))
}

// CustomScopeOrgIdsGTE applies the GTE predicate on the "custom_scope_org_ids" field.
func CustomScopeOrgIdsGTE(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldGTE(FieldCustomScopeOrgIds, v))
}

// CustomScopeOrgIdsLT applies the LT predicate on the "custom_scope_org_ids" field.
func CustomScopeOrgIdsLT(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldLT(FieldCustomScopeOrgIds, v))
}

// CustomScopeOrgIdsLTE applies the LTE predicate on the "custom_scope_org_ids" field.
func CustomScopeOrgIdsLTE(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldLTE(FieldCustomScopeOrgIds, v))
}

// CustomScopeOrgIdsContains applies the Contains predicate on the "custom_scope_org_ids" field.
func CustomScopeOrgIdsContains(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldContains(FieldCustomScopeOrgIds, v))
}

// CustomScopeOrgIdsHasPrefix applies the HasPrefix predicate on the "custom_scope_org_ids" field.
func CustomScopeOrgIdsHasPrefix(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldHasPrefix(FieldCustomScopeOrgIds, v))
}

// CustomScopeOrgIdsHasSuffix applies the HasSuffix predicate on the "custom_scope_org_ids" field.
func CustomScopeOrgIdsHasSuffix(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldHasSuffix(FieldCustomScopeOrgIds, v))
}

// CustomScopeOrgIdsIsNil applies the IsNil predicate on the "custom_scope_org_ids" field.
func CustomScopeOrgIdsIsNil() predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldIsNull(FieldCustomScopeOrgIds))
}

// CustomScopeOrgIdsNotNil applies the NotNil predicate on the "custom_scope_org_ids" field.
func CustomScopeOrgIdsNotNil() predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldNotNull(FieldCustomScopeOrgIds))
}

// CustomScopeOrgIdsEqualFold applies the EqualFold predicate on the "custom_scope_org_ids" field.
func CustomScopeOrgIdsEqualFold(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldEqualFold(FieldCustomScopeOrgIds, v))
}

// CustomScopeOrgIdsContainsFold applies the ContainsFold predicate on the "custom_scope_org_ids" field.
func CustomScopeOrgIdsContainsFold(v string) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.FieldContainsFold(FieldCustomScopeOrgIds, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RelRolePermission) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RelRolePermission) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RelRolePermission) predicate.RelRolePermission {
	return predicate.RelRolePermission(sql.NotPredicates(p))
}
